# Generated by Django 4.2.14 on 2025-02-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionorderoraldiet',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='nutritionordersupplement',
            name='schedule',
        ),
        migrations.AddField(
            model_name='nutritionorderoraldiet',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nutrition_order_oral_diet_schedule', to='nutritionorders.nutritionorderschedule'),
        ),
        migrations.AddField(
            model_name='nutritionordersupplement',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nutrition_order_supplement_schedule', to='nutritionorders.nutritionorderschedule'),
        ),
    ]
