# Generated by Django 4.2.14 on 2025-02-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imagingselections", "0003_remove_imagingselection_subject_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagingselection",
            old_name="bodysite",
            new_name="body_site",
        ),
    ]
