
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-14T09:33:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0358befd6cc251489fb000edf2c1c8a5970093f7",
 "version": "1.0.0-pre.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
