# Generated by Django 5.1 on 2025-04-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_customer", "0024_remove_customerimportresult_file_and_more"),
        ("artd_location", "0002_alter_city_created_at_alter_city_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_country",
            field=models.ForeignKey(
                blank=True,
                default=45,
                help_text="Phone country of the customer.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_location.country",
                verbose_name="Phone country",
            ),
        ),
    ]
