# Generated by Django 4.2.14 on 2025-01-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_extendedcontactdetail_address_and_more'),
        ('locations', '0003_alter_locationorganizationreference_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCodeableReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_codeable_reference_concept', to='base.codeableconcept')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_codeable_reference_reference', to='locations.locationreference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
