# Generated by Django 4.2.14 on 2025-01-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locationcodeablereference'),
        ('locations', '0005_location_endpoint'),
    ]

    operations = [
    ]
