# Generated by Django 4.2.14 on 2025-03-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0009_encounterepisodeofcarereference'),
        ('coverages', '0005_coveragereference'),
        ('servicerequests', '0005_servicerequestplandefinitionreference_and_more'),
        ('practitioners', '0011_practitionerrolereference'),
        ('medicationrequests', '0006_alter_medicationrequest_event_history_and_more'),
        ('bodystructures', '0006_bodystructurecodeablereference'),
        ('visionprescriptions', '0001_initial'),
        ('locations', '0006_merge_20250129_1542'),
        ('claims', '0003_remove_claim_sub_type_claim_sub_type'),
        ('claimresponses', '0001_initial'),
        ('nutritionorders', '0005_rename_instantiated_nutritionorder_instantiates_and_more'),
        ('base', '0018_merge_20250307_1944'),
        ('patients', '0007_patientorganizationreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimresponseinsurance',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_insurance_coverage', to='coverages.coveragereference'),
        ),
        migrations.AddField(
            model_name='claimresponseevent',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_event_type', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseevent',
            name='when_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_event_when_period', to='base.period'),
        ),
        migrations.AddField(
            model_name='claimresponseerror',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_error_code', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_identifier', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='medication_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_medication_request', to='medicationrequests.medicationrequest'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='nutrition_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_nutrition_order', to='nutritionorders.nutritionorder'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_service_request', to='servicerequests.servicerequest'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='vision_prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_vision_prescription', to='visionprescriptions.visionprescription'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemproviderreference',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_provider_reference_identifier', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemproviderreference',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_provider_reference_organization', to='base.organizationreference'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemproviderreference',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_provider_reference_practitioner', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemproviderreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_provider_reference_practitioner_role', to='practitioners.practitionerrole'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='adjudication',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_sub_detail_adjudication', to='claimresponses.claimresponseitemadjudication'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='modifier',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_sub_detail_modifier', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='net',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_net', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='product_or_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_product_or_service', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='product_or_service_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_product_or_service_end', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_quantity', to='base.simplequantity'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='revenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_revenue', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='review_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_review_outcome', to='claimresponses.claimresponseitemreviewoutcome'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_tax', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='trace_number',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_sub_detail_trace_number', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetailsubdetail',
            name='unit_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_sub_detail_unit_price', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='adjudication',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_adjudication', to='claimresponses.claimresponseitemadjudication'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='modifier',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_modifier', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='net',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_net', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='product_or_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_product_or_service', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='product_or_service_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_product_or_service_end', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_quantity', to='base.simplequantity'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='revenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_revenue', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='review_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_review_outcome', to='claimresponses.claimresponseitemreviewoutcome'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='sub_detail',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_sub_detail', to='claimresponses.claimresponseadditemdetailsubdetail'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_tax', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='trace_number',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail_trace_number', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemdetail',
            name='unit_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_detail_unit_price', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditembodysite',
            name='site',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_body_site_body_site', to='bodystructures.bodystructurecodeablereference'),
        ),
        migrations.AddField(
            model_name='claimresponseadditembodysite',
            name='sub_site',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_body_site_sub_site', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='adjudication',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_adjudication', to='claimresponses.claimresponseitemadjudication'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='body_site',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_body_site', to='claimresponses.claimresponseadditembodysite'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='detail',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_detail', to='claimresponses.claimresponseadditemdetail'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='location_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_location_address', to='base.address'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='location_codeable_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_location_codeable_concept', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='location_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_location_reference', to='locations.locationreference'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='modifier',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_modifier', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='net',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_net', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='product_or_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_product_or_service', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='program_code',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_program_code', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='provider',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_provider', to='claimresponses.claimresponseadditemproviderreference'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='provider_or_service_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_provider_or_service_end', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_quantity', to='base.simplequantity'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_request', to='claimresponses.claimresponseadditemrequestreference'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='review_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_review_outcome', to='claimresponses.claimresponseitemreviewoutcome'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='serviced_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_serviced_period', to='base.period'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_tax', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='trace_number',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item_trace_number', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponseadditem',
            name='unit_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_unit_price', to='base.money'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='add_item',
            field=models.ManyToManyField(blank=True, related_name='claim_response_add_item', to='claimresponses.claimresponseadditem'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='adjudication',
            field=models.ManyToManyField(blank=True, related_name='claim_response_adjudication', to='claimresponses.claimresponseitemadjudication'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='diagnosis_related_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_diagnosis_related_group', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='encounter',
            field=models.ManyToManyField(blank=True, related_name='claim_response_encounter', to='encounters.encounterreference'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='error',
            field=models.ManyToManyField(blank=True, related_name='claim_response_error', to='claimresponses.claimresponseerror'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='claim_response_event', to='claimresponses.claimresponseevent'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_form', to='base.attachment'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='form_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_form_code', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='funds_reserve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_funds_reserve', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='identifier',
            field=models.ManyToManyField(blank=True, related_name='claim_response_identifier', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='insurance',
            field=models.ManyToManyField(blank=True, related_name='claim_response_insurance', to='claimresponses.claimresponseinsurance'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_insurer', to='base.organizationreference'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='claim_response_item', to='claimresponses.claimresponseitem'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_patient', to='patients.patientreference'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='payee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_payee_type', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_payment', to='claimresponses.claimresponsepayment'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='pre_auth_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_pre_auth_period', to='base.period'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='process_note',
            field=models.ManyToManyField(blank=True, related_name='claim_response_process_note', to='claimresponses.claimresponseprocessnote'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_request', to='claims.claimreference'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_requestor', to='claimresponses.claimresponserequestorreference'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_sub_type', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='total',
            field=models.ManyToManyField(blank=True, related_name='claim_response_total', to='claimresponses.claimresponsetotal'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='trace_number',
            field=models.ManyToManyField(blank=True, related_name='claim_response_trace_number', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_type', to='base.codeableconcept'),
        ),
    ]
