# Generated by Django 4.2.14 on 2025-02-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareservices", "0006_remove_healthcareservice_endpoint"),
        ("imagingstudy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingstudyseriesperformeractorreference",
            name="healthcare_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="imaging_study_series_performer_reference",
                to="healthcareservices.healthcareservice",
            ),
        ),
    ]
