# Generated by Django 4.2.14 on 2025-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_money'),
        ('paymentnotices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentnotice',
            name='identifier',
        ),
        migrations.AddField(
            model_name='paymentnotice',
            name='identifier',
            field=models.ManyToManyField(blank=True, related_name='payment_notice', to='base.identifier'),
        ),
    ]
