# Generated by Django 4.2.14 on 2025-03-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge_20250307_1944'),
        ('devicerequests', '0003_remove_devicerequest_occurrence_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='occurrence_timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_request_occurrence_timing', to='base.timing'),
        ),
    ]
