import pathlib
from datetime import datetime as datetime
from rdetoolkit.cmd.archive import CreateArtifactCommand as CreateArtifactCommand
from rdetoolkit.cmd.command import InitCommand as InitCommand, VersionCommand as VersionCommand
from rdetoolkit.cmd.gen_excelinvoice import GenerateExcelInvoiceCommand as GenerateExcelInvoiceCommand
from typing import Literal

def cli() -> None: ...
def init() -> None: ...
def version() -> None: ...
def make_excelinvoice(invoice_schema_json_path: pathlib.Path, output_path: pathlib.Path, mode: Literal['file', 'folder']) -> None: ...
def artifact(source_dir: str, output_archive: pathlib.Path | None, exclude: list[str] | None) -> None: ...
