# Generated by Django 4.2.8 on 2023-12-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='absencereason',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='absencereason',
            name='kolego_unique_short_name_per_site_absence_reason',
        ),
        migrations.RunSQL(
            "ALTER TABLE kolego_absencereason drop column if exists site_id;"
        ),
        migrations.AlterField(
            model_name='absencereason',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absencereason',
            name='short_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Short name'),
        ),
    ]
