# Generated by Django 4.2.14 on 2025-03-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practitioners", "0011_practitionerrolereference"),
        ("base", "0013_money"),
        (
            "paymentreconciliations",
            "0002_alter_paymentreconciliationallocation_target_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentreconciliation",
            name="issued_by",
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="form_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_reconciliation_form_code",
                to="base.codeableconcept",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="issuer_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_reconciliation_issuer_type",
                to="base.codeableconcept",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliationallocation",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="paymentreconciliationallocation",
            name="responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_reconciliation_allocation_responsible",
                to="practitioners.practitionerrolereference",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreconciliationallocation",
            name="target_item_positive_int",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
