# Generated by Django 4.2.14 on 2025-03-08 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_merge_20250307_1944"),
        ("appointmentresponses", "0001_initial"),
        (
            "imagingstudy",
            "0002_imagingstudyseriesperformeractorreference_healthcare_service",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingstudybasedonreference",
            name="appointment_response",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="imaging_study_based_on_reference",
                to="appointmentresponses.appointmentresponse",
            ),
        ),
        migrations.CreateModel(
            name="ImagingStudyReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(max_length=255, null=True)),
                ("display", models.CharField(max_length=255, null=True)),
                (
                    "identifier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="imaging_study_reference_identifier",
                        to="base.identifier",
                    ),
                ),
                (
                    "imaging_study",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="imaging_study_reference_imaging_study",
                        to="imagingstudy.imagingstudy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
