# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtLocation, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtLocation`

import PySide6.QtLocation
import PySide6.QtCore
import PySide6.QtPositioning

import os
import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QGeoCodeReply(PySide6.QtCore.QObject):

    aborted                  : typing.ClassVar[Signal] = ... # aborted()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QGeoCodeReply::Error,QString); errorOccurred(QGeoCodeReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished()

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        EngineNotSetError         = ...  # 0x1
        CommunicationError        = ...  # 0x2
        ParseError                = ...  # 0x3
        UnsupportedOptionError    = ...  # 0x4
        CombinationError          = ...  # 0x5
        UnknownError              = ...  # 0x6


    @typing.overload
    def __init__(self, error: PySide6.QtLocation.QGeoCodeReply.Error, errorString: str, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def abort(self, /) -> None: ...
    def add_location(self, location: PySide6.QtPositioning.QGeoLocation, /) -> None: ...
    def error(self, /) -> PySide6.QtLocation.QGeoCodeReply.Error: ...
    def error_string(self, /) -> str: ...
    def is_finished(self, /) -> bool: ...
    def limit(self, /) -> int: ...
    def locations(self, /) -> typing.List[PySide6.QtPositioning.QGeoLocation]: ...
    def offset(self, /) -> int: ...
    def set_error(self, error: PySide6.QtLocation.QGeoCodeReply.Error, errorString: str, /) -> None: ...
    def set_finished(self, finished: bool, /) -> None: ...
    def set_limit(self, limit: int, /) -> None: ...
    def set_locations(self, locations: collections.abc.Sequence[PySide6.QtPositioning.QGeoLocation], /) -> None: ...
    def set_offset(self, offset: int, /) -> None: ...
    def set_viewport(self, viewport: PySide6.QtPositioning.QGeoShape, /) -> None: ...
    def viewport(self, /) -> PySide6.QtPositioning.QGeoShape: ...


class QGeoCodingManager(PySide6.QtCore.QObject):

    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QGeoCodeReply*,QGeoCodeReply::Error,QString); errorOccurred(QGeoCodeReply*,QGeoCodeReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished(QGeoCodeReply*)
    @typing.overload
    def geocode(self, address: PySide6.QtPositioning.QGeoAddress, /, bounds: PySide6.QtPositioning.QGeoShape = ...) -> PySide6.QtLocation.QGeoCodeReply: ...
    @typing.overload
    def geocode(self, searchString: str, /, limit: int = ..., offset: int | None = ..., bounds: PySide6.QtPositioning.QGeoShape = ...) -> PySide6.QtLocation.QGeoCodeReply: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def manager_name(self, /) -> str: ...
    def manager_version(self, /) -> int: ...
    def reverse_geocode(self, coordinate: PySide6.QtPositioning.QGeoCoordinate, /, bounds: PySide6.QtPositioning.QGeoShape = ...) -> PySide6.QtLocation.QGeoCodeReply: ...
    def set_locale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...


class QGeoCodingManagerEngine(PySide6.QtCore.QObject):

    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QGeoCodeReply*,QGeoCodeReply::Error,QString); errorOccurred(QGeoCodeReply*,QGeoCodeReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished(QGeoCodeReply*)

    def __init__(self, parameters: typing.Dict[str, typing.Any], /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    @typing.overload
    def geocode(self, address: PySide6.QtPositioning.QGeoAddress, bounds: PySide6.QtPositioning.QGeoShape, /) -> PySide6.QtLocation.QGeoCodeReply: ...
    @typing.overload
    def geocode(self, address: str, limit: int, offset: int, bounds: PySide6.QtPositioning.QGeoShape, /) -> PySide6.QtLocation.QGeoCodeReply: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def manager_name(self, /) -> str: ...
    def manager_version(self, /) -> int: ...
    def reverse_geocode(self, coordinate: PySide6.QtPositioning.QGeoCoordinate, bounds: PySide6.QtPositioning.QGeoShape, /) -> PySide6.QtLocation.QGeoCodeReply: ...
    def set_locale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...


class QGeoManeuver(Shiboken.Object):

    class InstructionDirection(enum.Enum):

        NoDirection               = ...  # 0x0
        DirectionForward          = ...  # 0x1
        DirectionBearRight        = ...  # 0x2
        DirectionLightRight       = ...  # 0x3
        DirectionRight            = ...  # 0x4
        DirectionHardRight        = ...  # 0x5
        DirectionUTurnRight       = ...  # 0x6
        DirectionUTurnLeft        = ...  # 0x7
        DirectionHardLeft         = ...  # 0x8
        DirectionLeft             = ...  # 0x9
        DirectionLightLeft        = ...  # 0xa
        DirectionBearLeft         = ...  # 0xb


    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QGeoManeuver, /, *, valid: bool | None = ..., position: PySide6.QtPositioning.QGeoCoordinate | None = ..., instruction_text: str | None = ..., direction: PySide6.QtLocation.QGeoManeuver.InstructionDirection | None = ..., time_to_next_instruction: int | None = ..., distance_to_next_instruction: float | None = ..., waypoint: PySide6.QtPositioning.QGeoCoordinate | None = ..., extended_attributes: typing.Optional[typing.Dict[str, typing.Any]] = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, valid: bool | None = ..., position: PySide6.QtPositioning.QGeoCoordinate | None = ..., instruction_text: str | None = ..., direction: PySide6.QtLocation.QGeoManeuver.InstructionDirection | None = ..., time_to_next_instruction: int | None = ..., distance_to_next_instruction: float | None = ..., waypoint: PySide6.QtPositioning.QGeoCoordinate | None = ..., extended_attributes: typing.Optional[typing.Dict[str, typing.Any]] = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QGeoManeuver, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QGeoManeuver, /) -> bool: ...
    def direction(self, /) -> PySide6.QtLocation.QGeoManeuver.InstructionDirection: ...
    def distance_to_next_instruction(self, /) -> float: ...
    def extended_attributes(self, /) -> typing.Dict[str, typing.Any]: ...
    def instruction_text(self, /) -> str: ...
    def is_valid(self, /) -> bool: ...
    def position(self, /) -> PySide6.QtPositioning.QGeoCoordinate: ...
    def set_direction(self, direction: PySide6.QtLocation.QGeoManeuver.InstructionDirection, /) -> None: ...
    def set_distance_to_next_instruction(self, distance: float, /) -> None: ...
    def set_extended_attributes(self, extendedAttributes: typing.Dict[str, typing.Any], /) -> None: ...
    def set_instruction_text(self, instructionText: str, /) -> None: ...
    def set_position(self, position: PySide6.QtPositioning.QGeoCoordinate, /) -> None: ...
    def set_time_to_next_instruction(self, secs: int, /) -> None: ...
    def set_waypoint(self, coordinate: PySide6.QtPositioning.QGeoCoordinate, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QGeoManeuver, /) -> None: ...
    def time_to_next_instruction(self, /) -> int: ...
    def waypoint(self, /) -> PySide6.QtPositioning.QGeoCoordinate: ...


class QGeoRoute(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QGeoRoute, /, *, route_id: str | None = ..., bounds: PySide6.QtPositioning.QGeoRectangle | None = ..., travel_time: int | None = ..., distance: float | None = ..., path: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate] | None = ..., route_legs: collections.abc.Sequence[PySide6.QtLocation.QGeoRoute] | None = ..., extended_attributes: typing.Optional[typing.Dict[str, typing.Any]] = ..., leg_index: int | None = ..., overall_route: PySide6.QtLocation.QGeoRoute | None = ..., segments_count: int | None = ..., segments: collections.abc.Sequence[PySide6.QtLocation.QGeoRouteSegment] | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, route_id: str | None = ..., bounds: PySide6.QtPositioning.QGeoRectangle | None = ..., travel_time: int | None = ..., distance: float | None = ..., path: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate] | None = ..., route_legs: collections.abc.Sequence[PySide6.QtLocation.QGeoRoute] | None = ..., extended_attributes: typing.Optional[typing.Dict[str, typing.Any]] = ..., leg_index: int | None = ..., overall_route: PySide6.QtLocation.QGeoRoute | None = ..., segments_count: int | None = ..., segments: collections.abc.Sequence[PySide6.QtLocation.QGeoRouteSegment] | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QGeoRoute, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QGeoRoute, /) -> bool: ...
    def bounds(self, /) -> PySide6.QtPositioning.QGeoRectangle: ...
    def distance(self, /) -> float: ...
    def extended_attributes(self, /) -> typing.Dict[str, typing.Any]: ...
    def first_route_segment(self, /) -> PySide6.QtLocation.QGeoRouteSegment: ...
    def leg_index(self, /) -> int: ...
    def overall_route(self, /) -> PySide6.QtLocation.QGeoRoute: ...
    def path(self, /) -> typing.List[PySide6.QtPositioning.QGeoCoordinate]: ...
    def request(self, /) -> PySide6.QtLocation.QGeoRouteRequest: ...
    def route_id(self, /) -> str: ...
    def route_legs(self, /) -> typing.List[PySide6.QtLocation.QGeoRoute]: ...
    def segments(self, /) -> typing.List[PySide6.QtLocation.QGeoRouteSegment]: ...
    def segments_count(self, /) -> int: ...
    def set_bounds(self, bounds: PySide6.QtPositioning.QGeoRectangle | PySide6.QtPositioning.QGeoShape | collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate], /) -> None: ...
    def set_distance(self, distance: float, /) -> None: ...
    def set_extended_attributes(self, extendedAttributes: typing.Dict[str, typing.Any], /) -> None: ...
    def set_first_route_segment(self, routeSegment: PySide6.QtLocation.QGeoRouteSegment, /) -> None: ...
    def set_leg_index(self, idx: int, /) -> None: ...
    def set_overall_route(self, route: PySide6.QtLocation.QGeoRoute, /) -> None: ...
    def set_path(self, path: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate], /) -> None: ...
    def set_request(self, request: PySide6.QtLocation.QGeoRouteRequest, /) -> None: ...
    def set_route_id(self, id: str, /) -> None: ...
    def set_route_legs(self, legs: collections.abc.Sequence[PySide6.QtLocation.QGeoRoute], /) -> None: ...
    def set_travel_mode(self, mode: PySide6.QtLocation.QGeoRouteRequest.TravelMode, /) -> None: ...
    def set_travel_time(self, secs: int, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QGeoRoute, /) -> None: ...
    def travel_mode(self, /) -> PySide6.QtLocation.QGeoRouteRequest.TravelMode: ...
    def travel_time(self, /) -> int: ...


class QGeoRouteReply(PySide6.QtCore.QObject):

    aborted                  : typing.ClassVar[Signal] = ... # aborted()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QGeoRouteReply::Error,QString); errorOccurred(QGeoRouteReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished()

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        EngineNotSetError         = ...  # 0x1
        CommunicationError        = ...  # 0x2
        ParseError                = ...  # 0x3
        UnsupportedOptionError    = ...  # 0x4
        UnknownError              = ...  # 0x5


    @typing.overload
    def __init__(self, error: PySide6.QtLocation.QGeoRouteReply.Error, errorString: str, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, request: PySide6.QtLocation.QGeoRouteRequest, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def abort(self, /) -> None: ...
    def add_routes(self, routes: collections.abc.Sequence[PySide6.QtLocation.QGeoRoute], /) -> None: ...
    def error(self, /) -> PySide6.QtLocation.QGeoRouteReply.Error: ...
    def error_string(self, /) -> str: ...
    def is_finished(self, /) -> bool: ...
    def request(self, /) -> PySide6.QtLocation.QGeoRouteRequest: ...
    def routes(self, /) -> typing.List[PySide6.QtLocation.QGeoRoute]: ...
    def set_error(self, error: PySide6.QtLocation.QGeoRouteReply.Error, errorString: str, /) -> None: ...
    def set_finished(self, finished: bool, /) -> None: ...
    def set_routes(self, routes: collections.abc.Sequence[PySide6.QtLocation.QGeoRoute], /) -> None: ...


class QGeoRouteRequest(Shiboken.Object):

    class FeatureType(enum.Flag):

        NoFeature                 = ...  # 0x0
        TollFeature               = ...  # 0x1
        HighwayFeature            = ...  # 0x2
        PublicTransitFeature      = ...  # 0x4
        FerryFeature              = ...  # 0x8
        TunnelFeature             = ...  # 0x10
        DirtRoadFeature           = ...  # 0x20
        ParksFeature              = ...  # 0x40
        MotorPoolLaneFeature      = ...  # 0x80
        TrafficFeature            = ...  # 0x100

    class FeatureWeight(enum.Flag):

        NeutralFeatureWeight      = ...  # 0x0
        PreferFeatureWeight       = ...  # 0x1
        RequireFeatureWeight      = ...  # 0x2
        AvoidFeatureWeight        = ...  # 0x4
        DisallowFeatureWeight     = ...  # 0x8

    class ManeuverDetail(enum.Flag):

        NoManeuvers               = ...  # 0x0
        BasicManeuvers            = ...  # 0x1

    class RouteOptimization(enum.Flag):

        ShortestRoute             = ...  # 0x1
        FastestRoute              = ...  # 0x2
        MostEconomicRoute         = ...  # 0x4
        MostScenicRoute           = ...  # 0x8

    class SegmentDetail(enum.Flag):

        NoSegmentData             = ...  # 0x0
        BasicSegmentData          = ...  # 0x1

    class TravelMode(enum.Flag):

        CarTravel                 = ...  # 0x1
        PedestrianTravel          = ...  # 0x2
        BicycleTravel             = ...  # 0x4
        PublicTransitTravel       = ...  # 0x8
        TruckTravel               = ...  # 0x10


    @typing.overload
    def __init__(self, origin: PySide6.QtPositioning.QGeoCoordinate, destination: PySide6.QtPositioning.QGeoCoordinate, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QGeoRouteRequest, /) -> None: ...
    @typing.overload
    def __init__(self, /, waypoints: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate] = ...) -> None: ...

    def __eq__(self, rhs: PySide6.QtLocation.QGeoRouteRequest, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QGeoRouteRequest, /) -> bool: ...
    def departure_time(self, /) -> PySide6.QtCore.QDateTime: ...
    def exclude_areas(self, /) -> typing.List[PySide6.QtPositioning.QGeoRectangle]: ...
    def feature_types(self, /) -> typing.List[PySide6.QtLocation.QGeoRouteRequest.FeatureType]: ...
    def feature_weight(self, featureType: PySide6.QtLocation.QGeoRouteRequest.FeatureType, /) -> PySide6.QtLocation.QGeoRouteRequest.FeatureWeight: ...
    def maneuver_detail(self, /) -> PySide6.QtLocation.QGeoRouteRequest.ManeuverDetail: ...
    def number_alternative_routes(self, /) -> int: ...
    def route_optimization(self, /) -> PySide6.QtLocation.QGeoRouteRequest.RouteOptimization: ...
    def segment_detail(self, /) -> PySide6.QtLocation.QGeoRouteRequest.SegmentDetail: ...
    def set_departure_time(self, departureTime: PySide6.QtCore.QDateTime, /) -> None: ...
    def set_exclude_areas(self, areas: collections.abc.Sequence[PySide6.QtPositioning.QGeoRectangle], /) -> None: ...
    def set_feature_weight(self, featureType: PySide6.QtLocation.QGeoRouteRequest.FeatureType, featureWeight: PySide6.QtLocation.QGeoRouteRequest.FeatureWeight, /) -> None: ...
    def set_maneuver_detail(self, maneuverDetail: PySide6.QtLocation.QGeoRouteRequest.ManeuverDetail, /) -> None: ...
    def set_number_alternative_routes(self, alternatives: int, /) -> None: ...
    def set_route_optimization(self, optimization: PySide6.QtLocation.QGeoRouteRequest.RouteOptimization, /) -> None: ...
    def set_segment_detail(self, segmentDetail: PySide6.QtLocation.QGeoRouteRequest.SegmentDetail, /) -> None: ...
    def set_travel_modes(self, travelModes: PySide6.QtLocation.QGeoRouteRequest.TravelMode, /) -> None: ...
    def set_waypoints(self, waypoints: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate], /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QGeoRouteRequest, /) -> None: ...
    def travel_modes(self, /) -> PySide6.QtLocation.QGeoRouteRequest.TravelMode: ...
    def waypoints(self, /) -> typing.List[PySide6.QtPositioning.QGeoCoordinate]: ...


class QGeoRouteSegment(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QGeoRouteSegment, /, *, travel_time: int | None = ..., distance: float | None = ..., path: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate] | None = ..., maneuver: PySide6.QtLocation.QGeoManeuver | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, travel_time: int | None = ..., distance: float | None = ..., path: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate] | None = ..., maneuver: PySide6.QtLocation.QGeoManeuver | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QGeoRouteSegment, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QGeoRouteSegment, /) -> bool: ...
    def distance(self, /) -> float: ...
    def is_leg_last_segment(self, /) -> bool: ...
    def is_valid(self, /) -> bool: ...
    def maneuver(self, /) -> PySide6.QtLocation.QGeoManeuver: ...
    def next_route_segment(self, /) -> PySide6.QtLocation.QGeoRouteSegment: ...
    def path(self, /) -> typing.List[PySide6.QtPositioning.QGeoCoordinate]: ...
    def set_distance(self, distance: float, /) -> None: ...
    def set_maneuver(self, maneuver: PySide6.QtLocation.QGeoManeuver, /) -> None: ...
    def set_next_route_segment(self, routeSegment: PySide6.QtLocation.QGeoRouteSegment, /) -> None: ...
    def set_path(self, path: collections.abc.Sequence[PySide6.QtPositioning.QGeoCoordinate], /) -> None: ...
    def set_travel_time(self, secs: int, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QGeoRouteSegment, /) -> None: ...
    def travel_time(self, /) -> int: ...


class QGeoRoutingManager(PySide6.QtCore.QObject):

    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QGeoRouteReply*,QGeoRouteReply::Error,QString); errorOccurred(QGeoRouteReply*,QGeoRouteReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished(QGeoRouteReply*)
    def calculate_route(self, request: PySide6.QtLocation.QGeoRouteRequest, /) -> PySide6.QtLocation.QGeoRouteReply: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def manager_name(self, /) -> str: ...
    def manager_version(self, /) -> int: ...
    def measurement_system(self, /) -> PySide6.QtCore.QLocale.MeasurementSystem: ...
    def set_locale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...
    def set_measurement_system(self, system: PySide6.QtCore.QLocale.MeasurementSystem, /) -> None: ...
    def supported_feature_types(self, /) -> PySide6.QtLocation.QGeoRouteRequest.FeatureType: ...
    def supported_feature_weights(self, /) -> PySide6.QtLocation.QGeoRouteRequest.FeatureWeight: ...
    def supported_maneuver_details(self, /) -> PySide6.QtLocation.QGeoRouteRequest.ManeuverDetail: ...
    def supported_route_optimizations(self, /) -> PySide6.QtLocation.QGeoRouteRequest.RouteOptimization: ...
    def supported_segment_details(self, /) -> PySide6.QtLocation.QGeoRouteRequest.SegmentDetail: ...
    def supported_travel_modes(self, /) -> PySide6.QtLocation.QGeoRouteRequest.TravelMode: ...
    def update_route(self, route: PySide6.QtLocation.QGeoRoute, position: PySide6.QtPositioning.QGeoCoordinate, /) -> PySide6.QtLocation.QGeoRouteReply: ...


class QGeoRoutingManagerEngine(PySide6.QtCore.QObject):

    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QGeoRouteReply*,QGeoRouteReply::Error,QString); errorOccurred(QGeoRouteReply*,QGeoRouteReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished(QGeoRouteReply*)

    def __init__(self, parameters: typing.Dict[str, typing.Any], /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def calculate_route(self, request: PySide6.QtLocation.QGeoRouteRequest, /) -> PySide6.QtLocation.QGeoRouteReply: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def manager_name(self, /) -> str: ...
    def manager_version(self, /) -> int: ...
    def measurement_system(self, /) -> PySide6.QtCore.QLocale.MeasurementSystem: ...
    def set_locale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...
    def set_measurement_system(self, system: PySide6.QtCore.QLocale.MeasurementSystem, /) -> None: ...
    def set_supported_feature_types(self, featureTypes: PySide6.QtLocation.QGeoRouteRequest.FeatureType, /) -> None: ...
    def set_supported_feature_weights(self, featureWeights: PySide6.QtLocation.QGeoRouteRequest.FeatureWeight, /) -> None: ...
    def set_supported_maneuver_details(self, maneuverDetails: PySide6.QtLocation.QGeoRouteRequest.ManeuverDetail, /) -> None: ...
    def set_supported_route_optimizations(self, optimizations: PySide6.QtLocation.QGeoRouteRequest.RouteOptimization, /) -> None: ...
    def set_supported_segment_details(self, segmentDetails: PySide6.QtLocation.QGeoRouteRequest.SegmentDetail, /) -> None: ...
    def set_supported_travel_modes(self, travelModes: PySide6.QtLocation.QGeoRouteRequest.TravelMode, /) -> None: ...
    def supported_feature_types(self, /) -> PySide6.QtLocation.QGeoRouteRequest.FeatureType: ...
    def supported_feature_weights(self, /) -> PySide6.QtLocation.QGeoRouteRequest.FeatureWeight: ...
    def supported_maneuver_details(self, /) -> PySide6.QtLocation.QGeoRouteRequest.ManeuverDetail: ...
    def supported_route_optimizations(self, /) -> PySide6.QtLocation.QGeoRouteRequest.RouteOptimization: ...
    def supported_segment_details(self, /) -> PySide6.QtLocation.QGeoRouteRequest.SegmentDetail: ...
    def supported_travel_modes(self, /) -> PySide6.QtLocation.QGeoRouteRequest.TravelMode: ...
    def update_route(self, route: PySide6.QtLocation.QGeoRoute, position: PySide6.QtPositioning.QGeoCoordinate, /) -> PySide6.QtLocation.QGeoRouteReply: ...


class QGeoServiceProvider(PySide6.QtCore.QObject):

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        NotSupportedError         = ...  # 0x1
        UnknownParameterError     = ...  # 0x2
        MissingRequiredParameterError = ...  # 0x3
        ConnectionError           = ...  # 0x4
        LoaderError               = ...  # 0x5

    class GeocodingFeature(enum.Flag):

        AnyGeocodingFeatures      = ...  # -1
        NoGeocodingFeatures       = ...  # 0x0
        OnlineGeocodingFeature    = ...  # 0x1
        OfflineGeocodingFeature   = ...  # 0x2
        ReverseGeocodingFeature   = ...  # 0x4
        LocalizedGeocodingFeature = ...  # 0x8

    class MappingFeature(enum.Flag):

        AnyMappingFeatures        = ...  # -1
        NoMappingFeatures         = ...  # 0x0
        OnlineMappingFeature      = ...  # 0x1
        OfflineMappingFeature     = ...  # 0x2
        LocalizedMappingFeature   = ...  # 0x4

    class NavigationFeature(enum.Flag):

        AnyNavigationFeatures     = ...  # -1
        NoNavigationFeatures      = ...  # 0x0
        OnlineNavigationFeature   = ...  # 0x1
        OfflineNavigationFeature  = ...  # 0x2

    class PlacesFeature(enum.Flag):

        AnyPlacesFeatures         = ...  # -1
        NoPlacesFeatures          = ...  # 0x0
        OnlinePlacesFeature       = ...  # 0x1
        OfflinePlacesFeature      = ...  # 0x2
        SavePlaceFeature          = ...  # 0x4
        RemovePlaceFeature        = ...  # 0x8
        SaveCategoryFeature       = ...  # 0x10
        RemoveCategoryFeature     = ...  # 0x20
        PlaceRecommendationsFeature = ...  # 0x40
        SearchSuggestionsFeature  = ...  # 0x80
        LocalizedPlacesFeature    = ...  # 0x100
        NotificationsFeature      = ...  # 0x200
        PlaceMatchingFeature      = ...  # 0x400

    class RoutingFeature(enum.Flag):

        AnyRoutingFeatures        = ...  # -1
        NoRoutingFeatures         = ...  # 0x0
        OnlineRoutingFeature      = ...  # 0x1
        OfflineRoutingFeature     = ...  # 0x2
        LocalizedRoutingFeature   = ...  # 0x4
        RouteUpdatesFeature       = ...  # 0x8
        AlternativeRoutesFeature  = ...  # 0x10
        ExcludeAreasRoutingFeature = ...  # 0x20


    def __init__(self, providerName: str, /, parameters: typing.Dict[str, typing.Any] = ..., allowExperimental: bool = ...) -> None: ...

    @staticmethod
    def available_service_providers() -> typing.List[str]: ...
    def error(self, /) -> PySide6.QtLocation.QGeoServiceProvider.Error: ...
    def error_string(self, /) -> str: ...
    def geocoding_error(self, /) -> PySide6.QtLocation.QGeoServiceProvider.Error: ...
    def geocoding_error_string(self, /) -> str: ...
    def geocoding_features(self, /) -> PySide6.QtLocation.QGeoServiceProvider.GeocodingFeature: ...
    def geocoding_manager(self, /) -> PySide6.QtLocation.QGeoCodingManager: ...
    def mapping_error(self, /) -> PySide6.QtLocation.QGeoServiceProvider.Error: ...
    def mapping_error_string(self, /) -> str: ...
    def mapping_features(self, /) -> PySide6.QtLocation.QGeoServiceProvider.MappingFeature: ...
    def navigation_error(self, /) -> PySide6.QtLocation.QGeoServiceProvider.Error: ...
    def navigation_error_string(self, /) -> str: ...
    def navigation_features(self, /) -> PySide6.QtLocation.QGeoServiceProvider.NavigationFeature: ...
    def place_manager(self, /) -> PySide6.QtLocation.QPlaceManager: ...
    def places_error(self, /) -> PySide6.QtLocation.QGeoServiceProvider.Error: ...
    def places_error_string(self, /) -> str: ...
    def places_features(self, /) -> PySide6.QtLocation.QGeoServiceProvider.PlacesFeature: ...
    def routing_error(self, /) -> PySide6.QtLocation.QGeoServiceProvider.Error: ...
    def routing_error_string(self, /) -> str: ...
    def routing_features(self, /) -> PySide6.QtLocation.QGeoServiceProvider.RoutingFeature: ...
    def routing_manager(self, /) -> PySide6.QtLocation.QGeoRoutingManager: ...
    def set_allow_experimental(self, allow: bool, /) -> None: ...
    def set_locale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...
    def set_parameters(self, parameters: typing.Dict[str, typing.Any], /) -> None: ...


class QGeoServiceProviderFactory(Shiboken.Object):

    def __init__(self, /) -> None: ...

    def create_geocoding_manager_engine(self, parameters: typing.Dict[str, typing.Any], error: PySide6.QtLocation.QGeoServiceProvider.Error, /) -> typing.Tuple[PySide6.QtLocation.QGeoCodingManagerEngine, str]: ...
    def create_place_manager_engine(self, parameters: typing.Dict[str, typing.Any], error: PySide6.QtLocation.QGeoServiceProvider.Error, /) -> typing.Tuple[PySide6.QtLocation.QPlaceManagerEngine, str]: ...
    def create_routing_manager_engine(self, parameters: typing.Dict[str, typing.Any], error: PySide6.QtLocation.QGeoServiceProvider.Error, /) -> typing.Tuple[PySide6.QtLocation.QGeoRoutingManagerEngine, str]: ...


class QIntList: ...


class QLocation(Shiboken.Object):

    class Visibility(enum.Flag):

        UnspecifiedVisibility     = ...  # 0x0
        DeviceVisibility          = ...  # 0x1
        PrivateVisibility         = ...  # 0x2
        PublicVisibility          = ...  # 0x4


class QPlace(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlace, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlace, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlace, /) -> bool: ...
    def append_contact_detail(self, contactType: str, detail: PySide6.QtLocation.QPlaceContactDetail, /) -> None: ...
    def attribution(self, /) -> str: ...
    def categories(self, /) -> typing.List[PySide6.QtLocation.QPlaceCategory]: ...
    def contact_details(self, contactType: str, /) -> typing.List[PySide6.QtLocation.QPlaceContactDetail]: ...
    def contact_types(self, /) -> typing.List[str]: ...
    def content(self, type: PySide6.QtLocation.QPlaceContent.Type, /) -> typing.Dict[int, PySide6.QtLocation.QPlaceContent]: ...
    def details_fetched(self, /) -> bool: ...
    def extended_attribute(self, attributeType: str, /) -> PySide6.QtLocation.QPlaceAttribute: ...
    def extended_attribute_types(self, /) -> typing.List[str]: ...
    def icon(self, /) -> PySide6.QtLocation.QPlaceIcon: ...
    def insert_content(self, type: PySide6.QtLocation.QPlaceContent.Type, content: typing.Dict[int, PySide6.QtLocation.QPlaceContent], /) -> None: ...
    def is_empty(self, /) -> bool: ...
    def location(self, /) -> PySide6.QtPositioning.QGeoLocation: ...
    def name(self, /) -> str: ...
    def place_id(self, /) -> str: ...
    def primary_email(self, /) -> str: ...
    def primary_fax(self, /) -> str: ...
    def primary_phone(self, /) -> str: ...
    def primary_website(self, /) -> PySide6.QtCore.QUrl: ...
    def ratings(self, /) -> PySide6.QtLocation.QPlaceRatings: ...
    def remove_contact_details(self, contactType: str, /) -> None: ...
    def remove_extended_attribute(self, attributeType: str, /) -> None: ...
    def set_attribution(self, attribution: str, /) -> None: ...
    def set_categories(self, categories: collections.abc.Sequence[PySide6.QtLocation.QPlaceCategory], /) -> None: ...
    def set_category(self, category: PySide6.QtLocation.QPlaceCategory, /) -> None: ...
    def set_contact_details(self, contactType: str, details: collections.abc.Sequence[PySide6.QtLocation.QPlaceContactDetail], /) -> None: ...
    def set_content(self, type: PySide6.QtLocation.QPlaceContent.Type, content: typing.Dict[int, PySide6.QtLocation.QPlaceContent], /) -> None: ...
    def set_details_fetched(self, fetched: bool, /) -> None: ...
    def set_extended_attribute(self, attributeType: str, attribute: PySide6.QtLocation.QPlaceAttribute, /) -> None: ...
    def set_icon(self, icon: PySide6.QtLocation.QPlaceIcon, /) -> None: ...
    def set_location(self, location: PySide6.QtPositioning.QGeoLocation, /) -> None: ...
    def set_name(self, name: str, /) -> None: ...
    def set_place_id(self, identifier: str, /) -> None: ...
    def set_ratings(self, ratings: PySide6.QtLocation.QPlaceRatings, /) -> None: ...
    def set_supplier(self, supplier: PySide6.QtLocation.QPlaceSupplier, /) -> None: ...
    def set_total_content_count(self, type: PySide6.QtLocation.QPlaceContent.Type, total: int, /) -> None: ...
    def set_visibility(self, visibility: PySide6.QtLocation.QLocation.Visibility, /) -> None: ...
    def supplier(self, /) -> PySide6.QtLocation.QPlaceSupplier: ...
    def swap(self, other: PySide6.QtLocation.QPlace, /) -> None: ...
    def total_content_count(self, type: PySide6.QtLocation.QPlaceContent.Type, /) -> int: ...
    def visibility(self, /) -> PySide6.QtLocation.QLocation.Visibility: ...


class QPlaceAttribute(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceAttribute, /, *, label: str | None = ..., text: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, label: str | None = ..., text: str | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceAttribute, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceAttribute, /) -> bool: ...
    def is_empty(self, /) -> bool: ...
    def label(self, /) -> str: ...
    def set_label(self, label: str, /) -> None: ...
    def set_text(self, text: str, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceAttribute, /) -> None: ...
    def text(self, /) -> str: ...


class QPlaceCategory(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceCategory, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceCategory, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceCategory, /) -> bool: ...
    def category_id(self, /) -> str: ...
    def icon(self, /) -> PySide6.QtLocation.QPlaceIcon: ...
    def is_empty(self, /) -> bool: ...
    def name(self, /) -> str: ...
    def set_category_id(self, identifier: str, /) -> None: ...
    def set_icon(self, icon: PySide6.QtLocation.QPlaceIcon, /) -> None: ...
    def set_name(self, name: str, /) -> None: ...
    def set_visibility(self, visibility: PySide6.QtLocation.QLocation.Visibility, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceCategory, /) -> None: ...
    def visibility(self, /) -> PySide6.QtLocation.QLocation.Visibility: ...


class QPlaceContactDetail(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceContactDetail, /, *, label: str | None = ..., value: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, label: str | None = ..., value: str | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceContactDetail, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceContactDetail, /) -> bool: ...
    def clear(self, /) -> None: ...
    def label(self, /) -> str: ...
    def set_label(self, label: str, /) -> None: ...
    def set_value(self, value: str, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceContactDetail, /) -> None: ...
    def value(self, /) -> str: ...


class QPlaceContent(Shiboken.Object):

    class DataTag(enum.Enum):

        ContentSupplier           = ...  # 0x0
        ContentUser               = ...  # 0x1
        ContentAttribution        = ...  # 0x2
        ImageId                   = ...  # 0x3
        ImageUrl                  = ...  # 0x4
        ImageMimeType             = ...  # 0x5
        EditorialTitle            = ...  # 0x6
        EditorialText             = ...  # 0x7
        EditorialLanguage         = ...  # 0x8
        ReviewId                  = ...  # 0x9
        ReviewDateTime            = ...  # 0xa
        ReviewTitle               = ...  # 0xb
        ReviewText                = ...  # 0xc
        ReviewLanguage            = ...  # 0xd
        ReviewRating              = ...  # 0xe
        CustomDataTag             = ...  # 0x3e8

    class Type(enum.Enum):

        NoType                    = ...  # 0x0
        ImageType                 = ...  # 0x1
        ReviewType                = ...  # 0x2
        EditorialType             = ...  # 0x3
        CustomType                = ...  # 0x100


    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceContent, /) -> None: ...
    @typing.overload
    def __init__(self, /, type: PySide6.QtLocation.QPlaceContent.Type = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtLocation.QPlaceContent | PySide6.QtLocation.QPlaceContent.Type, /) -> bool: ...
    def __ne__(self, other: PySide6.QtLocation.QPlaceContent | PySide6.QtLocation.QPlaceContent.Type, /) -> bool: ...
    def attribution(self, /) -> str: ...
    def data_tags(self, /) -> typing.List[PySide6.QtLocation.QPlaceContent.DataTag]: ...
    def set_attribution(self, attribution: str, /) -> None: ...
    def set_supplier(self, supplier: PySide6.QtLocation.QPlaceSupplier, /) -> None: ...
    def set_user(self, user: PySide6.QtLocation.QPlaceUser, /) -> None: ...
    def set_value(self, tag: PySide6.QtLocation.QPlaceContent.DataTag, arg__2: typing.Any, /) -> None: ...
    def supplier(self, /) -> PySide6.QtLocation.QPlaceSupplier: ...
    def swap(self, other: PySide6.QtLocation.QPlaceContent | PySide6.QtLocation.QPlaceContent.Type, /) -> None: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceContent.Type: ...
    def user(self, /) -> PySide6.QtLocation.QPlaceUser: ...
    def value(self, tag: PySide6.QtLocation.QPlaceContent.DataTag, /) -> typing.Any: ...


class QPlaceContentReply(PySide6.QtLocation.QPlaceReply):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def content(self, /) -> typing.Dict[int, PySide6.QtLocation.QPlaceContent]: ...
    def next_page_request(self, /) -> PySide6.QtLocation.QPlaceContentRequest: ...
    def previous_page_request(self, /) -> PySide6.QtLocation.QPlaceContentRequest: ...
    def request(self, /) -> PySide6.QtLocation.QPlaceContentRequest: ...
    def set_content(self, content: typing.Dict[int, PySide6.QtLocation.QPlaceContent], /) -> None: ...
    def set_next_page_request(self, next: PySide6.QtLocation.QPlaceContentRequest, /) -> None: ...
    def set_previous_page_request(self, previous: PySide6.QtLocation.QPlaceContentRequest, /) -> None: ...
    def set_request(self, request: PySide6.QtLocation.QPlaceContentRequest, /) -> None: ...
    def set_total_count(self, total: int, /) -> None: ...
    def total_count(self, /) -> int: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceContentRequest(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceContentRequest, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceContentRequest, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceContentRequest, /) -> bool: ...
    def clear(self, /) -> None: ...
    def content_context(self, /) -> typing.Any: ...
    def content_type(self, /) -> PySide6.QtLocation.QPlaceContent.Type: ...
    def limit(self, /) -> int: ...
    def place_id(self, /) -> str: ...
    def set_content_context(self, context: typing.Any, /) -> None: ...
    def set_content_type(self, type: PySide6.QtLocation.QPlaceContent.Type, /) -> None: ...
    def set_limit(self, limit: int, /) -> None: ...
    def set_place_id(self, identifier: str, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceContentRequest, /) -> None: ...


class QPlaceDetailsReply(PySide6.QtLocation.QPlaceReply):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def place(self, /) -> PySide6.QtLocation.QPlace: ...
    def set_place(self, place: PySide6.QtLocation.QPlace, /) -> None: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceIcon(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceIcon, /, *, parameters: typing.Optional[typing.Dict[str, typing.Any]] = ..., manager: PySide6.QtLocation.QPlaceManager | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, parameters: typing.Optional[typing.Dict[str, typing.Any]] = ..., manager: PySide6.QtLocation.QPlaceManager | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceIcon, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceIcon, /) -> bool: ...
    def is_empty(self, /) -> bool: ...
    def manager(self, /) -> PySide6.QtLocation.QPlaceManager: ...
    def parameters(self, /) -> typing.Dict[str, typing.Any]: ...
    def set_manager(self, manager: PySide6.QtLocation.QPlaceManager, /) -> None: ...
    def set_parameters(self, parameters: typing.Dict[str, typing.Any], /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceIcon, /) -> None: ...
    def url(self, /, size: PySide6.QtCore.QSize = ...) -> PySide6.QtCore.QUrl: ...


class QPlaceIdReply(PySide6.QtLocation.QPlaceReply):

    class OperationType(enum.Enum):

        SavePlace                 = ...  # 0x0
        SaveCategory              = ...  # 0x1
        RemovePlace               = ...  # 0x2
        RemoveCategory            = ...  # 0x3


    def __init__(self, operationType: PySide6.QtLocation.QPlaceIdReply.OperationType, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def id(self, /) -> str: ...
    def operation_type(self, /) -> PySide6.QtLocation.QPlaceIdReply.OperationType: ...
    def set_id(self, identifier: str, /) -> None: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceManager(PySide6.QtCore.QObject):

    categoryAdded            : typing.ClassVar[Signal] = ... # categoryAdded(QPlaceCategory,QString)
    categoryRemoved          : typing.ClassVar[Signal] = ... # categoryRemoved(QString,QString)
    categoryUpdated          : typing.ClassVar[Signal] = ... # categoryUpdated(QPlaceCategory,QString)
    dataChanged              : typing.ClassVar[Signal] = ... # dataChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QPlaceReply*,QPlaceReply::Error,QString); errorOccurred(QPlaceReply*,QPlaceReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished(QPlaceReply*)
    placeAdded               : typing.ClassVar[Signal] = ... # placeAdded(QString)
    placeRemoved             : typing.ClassVar[Signal] = ... # placeRemoved(QString)
    placeUpdated             : typing.ClassVar[Signal] = ... # placeUpdated(QString)
    def category(self, categoryId: str, /) -> PySide6.QtLocation.QPlaceCategory: ...
    def child_categories(self, /, parentId: str = ...) -> typing.List[PySide6.QtLocation.QPlaceCategory]: ...
    def child_category_ids(self, /, parentId: str = ...) -> typing.List[str]: ...
    def compatible_place(self, place: PySide6.QtLocation.QPlace, /) -> PySide6.QtLocation.QPlace: ...
    def get_place_content(self, request: PySide6.QtLocation.QPlaceContentRequest, /) -> PySide6.QtLocation.QPlaceContentReply: ...
    def get_place_details(self, placeId: str, /) -> PySide6.QtLocation.QPlaceDetailsReply: ...
    def initialize_categories(self, /) -> PySide6.QtLocation.QPlaceReply: ...
    def locales(self, /) -> typing.List[PySide6.QtCore.QLocale]: ...
    def manager_name(self, /) -> str: ...
    def manager_version(self, /) -> int: ...
    def matching_places(self, request: PySide6.QtLocation.QPlaceMatchRequest, /) -> PySide6.QtLocation.QPlaceMatchReply: ...
    def parent_category_id(self, categoryId: str, /) -> str: ...
    def remove_category(self, categoryId: str, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def remove_place(self, placeId: str, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def save_category(self, category: PySide6.QtLocation.QPlaceCategory, /, parentId: str = ...) -> PySide6.QtLocation.QPlaceIdReply: ...
    def save_place(self, place: PySide6.QtLocation.QPlace, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def search(self, query: PySide6.QtLocation.QPlaceSearchRequest, /) -> PySide6.QtLocation.QPlaceSearchReply: ...
    def search_suggestions(self, request: PySide6.QtLocation.QPlaceSearchRequest, /) -> PySide6.QtLocation.QPlaceSearchSuggestionReply: ...
    def set_locale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...
    def set_locales(self, locale: collections.abc.Sequence[PySide6.QtCore.QLocale], /) -> None: ...


class QPlaceManagerEngine(PySide6.QtCore.QObject):

    categoryAdded            : typing.ClassVar[Signal] = ... # categoryAdded(QPlaceCategory,QString)
    categoryRemoved          : typing.ClassVar[Signal] = ... # categoryRemoved(QString,QString)
    categoryUpdated          : typing.ClassVar[Signal] = ... # categoryUpdated(QPlaceCategory,QString)
    dataChanged              : typing.ClassVar[Signal] = ... # dataChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QPlaceReply*,QPlaceReply::Error,QString); errorOccurred(QPlaceReply*,QPlaceReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished(QPlaceReply*)
    placeAdded               : typing.ClassVar[Signal] = ... # placeAdded(QString)
    placeRemoved             : typing.ClassVar[Signal] = ... # placeRemoved(QString)
    placeUpdated             : typing.ClassVar[Signal] = ... # placeUpdated(QString)

    def __init__(self, parameters: typing.Dict[str, typing.Any], /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def category(self, categoryId: str, /) -> PySide6.QtLocation.QPlaceCategory: ...
    def child_categories(self, parentId: str, /) -> typing.List[PySide6.QtLocation.QPlaceCategory]: ...
    def child_category_ids(self, categoryId: str, /) -> typing.List[str]: ...
    def compatible_place(self, original: PySide6.QtLocation.QPlace, /) -> PySide6.QtLocation.QPlace: ...
    def construct_icon_url(self, icon: PySide6.QtLocation.QPlaceIcon, size: PySide6.QtCore.QSize, /) -> PySide6.QtCore.QUrl: ...
    def get_place_content(self, request: PySide6.QtLocation.QPlaceContentRequest, /) -> PySide6.QtLocation.QPlaceContentReply: ...
    def get_place_details(self, placeId: str, /) -> PySide6.QtLocation.QPlaceDetailsReply: ...
    def initialize_categories(self, /) -> PySide6.QtLocation.QPlaceReply: ...
    def locales(self, /) -> typing.List[PySide6.QtCore.QLocale]: ...
    def manager(self, /) -> PySide6.QtLocation.QPlaceManager: ...
    def manager_name(self, /) -> str: ...
    def manager_version(self, /) -> int: ...
    def matching_places(self, request: PySide6.QtLocation.QPlaceMatchRequest, /) -> PySide6.QtLocation.QPlaceMatchReply: ...
    def parent_category_id(self, categoryId: str, /) -> str: ...
    def remove_category(self, categoryId: str, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def remove_place(self, placeId: str, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def save_category(self, category: PySide6.QtLocation.QPlaceCategory, parentId: str, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def save_place(self, place: PySide6.QtLocation.QPlace, /) -> PySide6.QtLocation.QPlaceIdReply: ...
    def search(self, request: PySide6.QtLocation.QPlaceSearchRequest, /) -> PySide6.QtLocation.QPlaceSearchReply: ...
    def search_suggestions(self, request: PySide6.QtLocation.QPlaceSearchRequest, /) -> PySide6.QtLocation.QPlaceSearchSuggestionReply: ...
    def set_locales(self, locales: collections.abc.Sequence[PySide6.QtCore.QLocale], /) -> None: ...


class QPlaceMatchReply(PySide6.QtLocation.QPlaceReply):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def places(self, /) -> typing.List[PySide6.QtLocation.QPlace]: ...
    def request(self, /) -> PySide6.QtLocation.QPlaceMatchRequest: ...
    def set_places(self, results: collections.abc.Sequence[PySide6.QtLocation.QPlace], /) -> None: ...
    def set_request(self, request: PySide6.QtLocation.QPlaceMatchRequest, /) -> None: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceMatchRequest(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceMatchRequest, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceMatchRequest, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceMatchRequest, /) -> bool: ...
    def clear(self, /) -> None: ...
    def parameters(self, /) -> typing.Dict[str, typing.Any]: ...
    def places(self, /) -> typing.List[PySide6.QtLocation.QPlace]: ...
    def set_parameters(self, parameters: typing.Dict[str, typing.Any], /) -> None: ...
    def set_places(self, places: collections.abc.Sequence[PySide6.QtLocation.QPlace], /) -> None: ...
    def set_results(self, results: collections.abc.Sequence[PySide6.QtLocation.QPlaceSearchResult], /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceMatchRequest, /) -> None: ...


class QPlaceProposedSearchResult(PySide6.QtLocation.QPlaceSearchResult):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceSearchResult, /) -> None: ...

    def search_request(self, /) -> PySide6.QtLocation.QPlaceSearchRequest: ...
    def set_search_request(self, request: PySide6.QtLocation.QPlaceSearchRequest, /) -> None: ...


class QPlaceRatings(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceRatings, /, *, average: float | None = ..., maximum: float | None = ..., count: int | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, average: float | None = ..., maximum: float | None = ..., count: int | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceRatings, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceRatings, /) -> bool: ...
    def average(self, /) -> float: ...
    def count(self, /) -> int: ...
    def is_empty(self, /) -> bool: ...
    def maximum(self, /) -> float: ...
    def set_average(self, average: float, /) -> None: ...
    def set_count(self, count: int, /) -> None: ...
    def set_maximum(self, max: float, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceRatings, /) -> None: ...


class QPlaceReply(PySide6.QtCore.QObject):

    aborted                  : typing.ClassVar[Signal] = ... # aborted()
    contentUpdated           : typing.ClassVar[Signal] = ... # contentUpdated()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QPlaceReply::Error,QString); errorOccurred(QPlaceReply::Error)
    finished                 : typing.ClassVar[Signal] = ... # finished()

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        PlaceDoesNotExistError    = ...  # 0x1
        CategoryDoesNotExistError = ...  # 0x2
        CommunicationError        = ...  # 0x3
        ParseError                = ...  # 0x4
        PermissionsError          = ...  # 0x5
        UnsupportedError          = ...  # 0x6
        BadArgumentError          = ...  # 0x7
        CancelError               = ...  # 0x8
        UnknownError              = ...  # 0x9

    class Type(enum.Enum):

        Reply                     = ...  # 0x0
        DetailsReply              = ...  # 0x1
        SearchReply               = ...  # 0x2
        SearchSuggestionReply     = ...  # 0x3
        ContentReply              = ...  # 0x4
        IdReply                   = ...  # 0x5
        MatchReply                = ...  # 0x6


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def abort(self, /) -> None: ...
    def error(self, /) -> PySide6.QtLocation.QPlaceReply.Error: ...
    def error_string(self, /) -> str: ...
    def is_finished(self, /) -> bool: ...
    def set_error(self, error: PySide6.QtLocation.QPlaceReply.Error, errorString: str, /) -> None: ...
    def set_finished(self, finished: bool, /) -> None: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceResult(PySide6.QtLocation.QPlaceSearchResult):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceSearchResult, /) -> None: ...

    def distance(self, /) -> float: ...
    def is_sponsored(self, /) -> bool: ...
    def place(self, /) -> PySide6.QtLocation.QPlace: ...
    def set_distance(self, distance: float, /) -> None: ...
    def set_place(self, place: PySide6.QtLocation.QPlace, /) -> None: ...
    def set_sponsored(self, sponsored: bool, /) -> None: ...


class QPlaceSearchReply(PySide6.QtLocation.QPlaceReply):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def next_page_request(self, /) -> PySide6.QtLocation.QPlaceSearchRequest: ...
    def previous_page_request(self, /) -> PySide6.QtLocation.QPlaceSearchRequest: ...
    def request(self, /) -> PySide6.QtLocation.QPlaceSearchRequest: ...
    def results(self, /) -> typing.List[PySide6.QtLocation.QPlaceSearchResult]: ...
    def set_next_page_request(self, next: PySide6.QtLocation.QPlaceSearchRequest, /) -> None: ...
    def set_previous_page_request(self, previous: PySide6.QtLocation.QPlaceSearchRequest, /) -> None: ...
    def set_request(self, request: PySide6.QtLocation.QPlaceSearchRequest, /) -> None: ...
    def set_results(self, results: collections.abc.Sequence[PySide6.QtLocation.QPlaceSearchResult], /) -> None: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceSearchRequest(Shiboken.Object):

    class RelevanceHint(enum.Enum):

        UnspecifiedHint           = ...  # 0x0
        DistanceHint              = ...  # 0x1
        LexicalPlaceNameHint      = ...  # 0x2


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceSearchRequest, /) -> None: ...

    def __eq__(self, rhs: PySide6.QtLocation.QPlaceSearchRequest, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceSearchRequest, /) -> bool: ...
    def categories(self, /) -> typing.List[PySide6.QtLocation.QPlaceCategory]: ...
    def clear(self, /) -> None: ...
    def limit(self, /) -> int: ...
    def recommendation_id(self, /) -> str: ...
    def relevance_hint(self, /) -> PySide6.QtLocation.QPlaceSearchRequest.RelevanceHint: ...
    def search_area(self, /) -> PySide6.QtPositioning.QGeoShape: ...
    def search_context(self, /) -> typing.Any: ...
    def search_term(self, /) -> str: ...
    def set_categories(self, categories: collections.abc.Sequence[PySide6.QtLocation.QPlaceCategory], /) -> None: ...
    def set_category(self, category: PySide6.QtLocation.QPlaceCategory, /) -> None: ...
    def set_limit(self, limit: int, /) -> None: ...
    def set_recommendation_id(self, recommendationId: str, /) -> None: ...
    def set_relevance_hint(self, hint: PySide6.QtLocation.QPlaceSearchRequest.RelevanceHint, /) -> None: ...
    def set_search_area(self, area: PySide6.QtPositioning.QGeoShape, /) -> None: ...
    def set_search_context(self, context: typing.Any, /) -> None: ...
    def set_search_term(self, term: str, /) -> None: ...
    def set_visibility_scope(self, visibilityScopes: PySide6.QtLocation.QLocation.Visibility, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceSearchRequest, /) -> None: ...
    def visibility_scope(self, /) -> PySide6.QtLocation.QLocation.Visibility: ...


class QPlaceSearchResult(Shiboken.Object):

    class SearchResultType(enum.Enum):

        UnknownSearchResult       = ...  # 0x0
        PlaceResult               = ...  # 0x1
        ProposedSearchResult      = ...  # 0x2


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceSearchResult, /) -> None: ...

    def __eq__(self, other: PySide6.QtLocation.QPlaceSearchResult, /) -> bool: ...
    def __ne__(self, other: PySide6.QtLocation.QPlaceSearchResult, /) -> bool: ...
    def icon(self, /) -> PySide6.QtLocation.QPlaceIcon: ...
    def set_icon(self, icon: PySide6.QtLocation.QPlaceIcon, /) -> None: ...
    def set_title(self, title: str, /) -> None: ...
    def title(self, /) -> str: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceSearchResult.SearchResultType: ...


class QPlaceSearchSuggestionReply(PySide6.QtLocation.QPlaceReply):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def set_suggestions(self, suggestions: collections.abc.Sequence[str], /) -> None: ...
    def suggestions(self, /) -> typing.List[str]: ...
    def type(self, /) -> PySide6.QtLocation.QPlaceReply.Type: ...


class QPlaceSupplier(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceSupplier, /, *, name: str | None = ..., supplier_id: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtLocation.QPlaceIcon | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, name: str | None = ..., supplier_id: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtLocation.QPlaceIcon | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceSupplier, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceSupplier, /) -> bool: ...
    def icon(self, /) -> PySide6.QtLocation.QPlaceIcon: ...
    def is_empty(self, /) -> bool: ...
    def name(self, /) -> str: ...
    def set_icon(self, icon: PySide6.QtLocation.QPlaceIcon, /) -> None: ...
    def set_name(self, data: str, /) -> None: ...
    def set_supplier_id(self, identifier: str, /) -> None: ...
    def set_url(self, data: PySide6.QtCore.QUrl | str, /) -> None: ...
    def supplier_id(self, /) -> str: ...
    def swap(self, other: PySide6.QtLocation.QPlaceSupplier, /) -> None: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QPlaceUser(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtLocation.QPlaceUser, /, *, user_id: str | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, user_id: str | None = ..., name: str | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtLocation.QPlaceUser, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtLocation.QPlaceUser, /) -> bool: ...
    def name(self, /) -> str: ...
    def set_name(self, name: str, /) -> None: ...
    def set_user_id(self, identifier: str, /) -> None: ...
    def swap(self, other: PySide6.QtLocation.QPlaceUser, /) -> None: ...
    def user_id(self, /) -> str: ...


# eof
