# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtMultimedia, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtMultimedia`

import PySide6.QtMultimedia
import PySide6.QtCore
import PySide6.QtGui

import os
import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QAbstractVideoBuffer(Shiboken.Object):

    class MapData(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, MapData: PySide6.QtMultimedia.QAbstractVideoBuffer.MapData, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...


    def __init__(self, /) -> None: ...

    def format(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat: ...
    def map(self, mode: PySide6.QtMultimedia.QVideoFrame.MapMode, /) -> PySide6.QtMultimedia.QAbstractVideoBuffer.MapData: ...
    def unmap(self, /) -> None: ...


class QAudio(Shiboken.Object):

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        OpenError                 = ...  # 0x1
        IOError                   = ...  # 0x2
        UnderrunError             = ...  # 0x3
        FatalError                = ...  # 0x4

    class State(enum.Enum):

        ActiveState               = ...  # 0x0
        SuspendedState            = ...  # 0x1
        StoppedState              = ...  # 0x2
        IdleState                 = ...  # 0x3

    class VolumeScale(enum.Enum):

        LinearVolumeScale         = ...  # 0x0
        CubicVolumeScale          = ...  # 0x1
        LogarithmicVolumeScale    = ...  # 0x2
        DecibelVolumeScale        = ...  # 0x3


    @staticmethod
    def convert_volume(volume: float, from_: PySide6.QtMultimedia.QAudio.VolumeScale, to: PySide6.QtMultimedia.QAudio.VolumeScale, /) -> float: ...


class QAudioBuffer(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QAudioBuffer, /) -> None: ...
    @typing.overload
    def __init__(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, format: PySide6.QtMultimedia.QAudioFormat, /, startTime: int = ...) -> None: ...
    @typing.overload
    def __init__(self, numFrames: int, format: PySide6.QtMultimedia.QAudioFormat, /, startTime: int = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def byte_count(self, /) -> int: ...
    def const_data(self, /) -> typing.Union[bytes, bytearray, memoryview]: ...
    def data(self, /) -> typing.Union[bytes, bytearray, memoryview]: ...
    def duration(self, /) -> int: ...
    def format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def frame_count(self, /) -> int: ...
    def is_valid(self, /) -> bool: ...
    def sample_count(self, /) -> int: ...
    def start_time(self, /) -> int: ...
    def swap(self, other: PySide6.QtMultimedia.QAudioBuffer, /) -> None: ...


class QAudioBufferInput(PySide6.QtCore.QObject):

    readyToSendAudioBuffer   : typing.ClassVar[Signal] = ... # readyToSendAudioBuffer()

    @typing.overload
    def __init__(self, format: PySide6.QtMultimedia.QAudioFormat, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def send_audio_buffer(self, audioBuffer: PySide6.QtMultimedia.QAudioBuffer, /) -> bool: ...


class QAudioBufferOutput(PySide6.QtCore.QObject):

    audioBufferReceived      : typing.ClassVar[Signal] = ... # audioBufferReceived(QAudioBuffer)

    @typing.overload
    def __init__(self, format: PySide6.QtMultimedia.QAudioFormat, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...


class QAudioDecoder(PySide6.QtCore.QObject):

    bufferAvailableChanged   : typing.ClassVar[Signal] = ... # bufferAvailableChanged(bool)
    bufferReady              : typing.ClassVar[Signal] = ... # bufferReady()
    durationChanged          : typing.ClassVar[Signal] = ... # durationChanged(qlonglong)
    finished                 : typing.ClassVar[Signal] = ... # finished()
    formatChanged            : typing.ClassVar[Signal] = ... # formatChanged(QAudioFormat)
    isDecodingChanged        : typing.ClassVar[Signal] = ... # isDecodingChanged(bool)
    positionChanged          : typing.ClassVar[Signal] = ... # positionChanged(qlonglong)
    sourceChanged            : typing.ClassVar[Signal] = ... # sourceChanged()

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        ResourceError             = ...  # 0x1
        FormatError               = ...  # 0x2
        AccessDeniedError         = ...  # 0x3
        NotSupportedError         = ...  # 0x4


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., is_decoding: bool | None = ..., error: str | None = ..., buffer_available: bool | None = ...) -> None: ...

    def audio_format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def buffer_available(self, /) -> bool: ...
    def duration(self, /) -> int: ...
    def error(self, /) -> PySide6.QtMultimedia.QAudioDecoder.Error: ...
    def error_string(self, /) -> str: ...
    def is_decoding(self, /) -> bool: ...
    def is_supported(self, /) -> bool: ...
    def position(self, /) -> int: ...
    def read(self, /) -> PySide6.QtMultimedia.QAudioBuffer: ...
    def set_audio_format(self, format: PySide6.QtMultimedia.QAudioFormat, /) -> None: ...
    def set_source(self, fileName: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_source_device(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def source_device(self, /) -> PySide6.QtCore.QIODevice: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...


class QAudioDevice(Shiboken.Object):

    class Mode(enum.Enum):

        Null                      = ...  # 0x0
        Input                     = ...  # 0x1
        Output                    = ...  # 0x2


    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QAudioDevice, /, *, id: PySide6.QtCore.QByteArray | None = ..., description: str | None = ..., is_default: bool | None = ..., mode: PySide6.QtMultimedia.QAudioDevice.Mode | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, id: PySide6.QtCore.QByteArray | None = ..., description: str | None = ..., is_default: bool | None = ..., mode: PySide6.QtMultimedia.QAudioDevice.Mode | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtMultimedia.QAudioDevice, /) -> bool: ...
    def __ne__(self, other: PySide6.QtMultimedia.QAudioDevice, /) -> bool: ...
    def channel_configuration(self, /) -> PySide6.QtMultimedia.QAudioFormat.ChannelConfig: ...
    def description(self, /) -> str: ...
    def id(self, /) -> PySide6.QtCore.QByteArray: ...
    def is_default(self, /) -> bool: ...
    def is_format_supported(self, format: PySide6.QtMultimedia.QAudioFormat, /) -> bool: ...
    def is_null(self, /) -> bool: ...
    def maximum_channel_count(self, /) -> int: ...
    def maximum_sample_rate(self, /) -> int: ...
    def minimum_channel_count(self, /) -> int: ...
    def minimum_sample_rate(self, /) -> int: ...
    def mode(self, /) -> PySide6.QtMultimedia.QAudioDevice.Mode: ...
    def preferred_format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def supported_sample_formats(self, /) -> typing.List[PySide6.QtMultimedia.QAudioFormat.SampleFormat]: ...
    def swap(self, other: PySide6.QtMultimedia.QAudioDevice, /) -> None: ...


class QAudioFormat(Shiboken.Object):

    class AudioChannelPosition(enum.Enum):

        UnknownPosition           = ...  # 0x0
        FrontLeft                 = ...  # 0x1
        FrontRight                = ...  # 0x2
        FrontCenter               = ...  # 0x3
        LFE                       = ...  # 0x4
        BackLeft                  = ...  # 0x5
        BackRight                 = ...  # 0x6
        FrontLeftOfCenter         = ...  # 0x7
        FrontRightOfCenter        = ...  # 0x8
        BackCenter                = ...  # 0x9
        SideLeft                  = ...  # 0xa
        SideRight                 = ...  # 0xb
        TopCenter                 = ...  # 0xc
        TopFrontLeft              = ...  # 0xd
        TopFrontCenter            = ...  # 0xe
        TopFrontRight             = ...  # 0xf
        TopBackLeft               = ...  # 0x10
        TopBackCenter             = ...  # 0x11
        TopBackRight              = ...  # 0x12
        LFE2                      = ...  # 0x13
        TopSideLeft               = ...  # 0x14
        TopSideRight              = ...  # 0x15
        BottomFrontCenter         = ...  # 0x16
        BottomFrontLeft           = ...  # 0x17
        BottomFrontRight          = ...  # 0x18

    class ChannelConfig(enum.Enum):

        ChannelConfigUnknown      = ...  # 0x0
        ChannelConfigStereo       = ...  # 0x6
        ChannelConfigMono         = ...  # 0x8
        ChannelConfig3Dot0        = ...  # 0xe
        ChannelConfig2Dot1        = ...  # 0x16
        ChannelConfig3Dot1        = ...  # 0x1e
        ChannelConfigSurround5Dot0 = ...  # 0x6e
        ChannelConfigSurround5Dot1 = ...  # 0x7e
        ChannelConfigSurround7Dot0 = ...  # 0xc6e
        ChannelConfigSurround7Dot1 = ...  # 0xc7e

    class SampleFormat(enum.Enum):

        Unknown                   = ...  # 0x0
        UInt8                     = ...  # 0x1
        Int16                     = ...  # 0x2
        Int32                     = ...  # 0x3
        Float                     = ...  # 0x4
        NSampleFormats            = ...  # 0x5


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, QAudioFormat: PySide6.QtMultimedia.QAudioFormat, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, b: PySide6.QtMultimedia.QAudioFormat, /) -> bool: ...
    def __ne__(self, b: PySide6.QtMultimedia.QAudioFormat, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def bytes_for_duration(self, microseconds: int, /) -> int: ...
    def bytes_for_frames(self, frameCount: int, /) -> int: ...
    def bytes_per_frame(self, /) -> int: ...
    def bytes_per_sample(self, /) -> int: ...
    def channel_config(self, /) -> PySide6.QtMultimedia.QAudioFormat.ChannelConfig: ...
    def channel_count(self, /) -> int: ...
    def channel_offset(self, channel: PySide6.QtMultimedia.QAudioFormat.AudioChannelPosition, /) -> int: ...
    @staticmethod
    def default_channel_config_for_channel_count(channelCount: int, /) -> PySide6.QtMultimedia.QAudioFormat.ChannelConfig: ...
    def duration_for_bytes(self, byteCount: int, /) -> int: ...
    def duration_for_frames(self, frameCount: int, /) -> int: ...
    def frames_for_bytes(self, byteCount: int, /) -> int: ...
    def frames_for_duration(self, microseconds: int, /) -> int: ...
    def is_valid(self, /) -> bool: ...
    def normalized_sample_value(self, sample: bytes | bytearray | memoryview, /) -> float: ...
    def sample_format(self, /) -> PySide6.QtMultimedia.QAudioFormat.SampleFormat: ...
    def sample_rate(self, /) -> int: ...
    def set_channel_config(self, config: PySide6.QtMultimedia.QAudioFormat.ChannelConfig, /) -> None: ...
    def set_channel_count(self, channelCount: int, /) -> None: ...
    def set_sample_format(self, f: PySide6.QtMultimedia.QAudioFormat.SampleFormat, /) -> None: ...
    def set_sample_rate(self, sampleRate: int, /) -> None: ...


class QAudioInput(PySide6.QtCore.QObject):

    deviceChanged            : typing.ClassVar[Signal] = ... # deviceChanged()
    mutedChanged             : typing.ClassVar[Signal] = ... # mutedChanged(bool)
    volumeChanged            : typing.ClassVar[Signal] = ... # volumeChanged(float)

    @typing.overload
    def __init__(self, deviceInfo: PySide6.QtMultimedia.QAudioDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, device: PySide6.QtMultimedia.QAudioDevice | None = ..., volume: float | None = ..., muted: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, device: PySide6.QtMultimedia.QAudioDevice | None = ..., volume: float | None = ..., muted: bool | None = ...) -> None: ...

    def device(self, /) -> PySide6.QtMultimedia.QAudioDevice: ...
    def is_muted(self, /) -> bool: ...
    def set_device(self, device: PySide6.QtMultimedia.QAudioDevice, /) -> None: ...
    def set_muted(self, muted: bool, /) -> None: ...
    def set_volume(self, volume: float, /) -> None: ...
    def volume(self, /) -> float: ...


class QAudioOutput(PySide6.QtCore.QObject):

    deviceChanged            : typing.ClassVar[Signal] = ... # deviceChanged()
    mutedChanged             : typing.ClassVar[Signal] = ... # mutedChanged(bool)
    volumeChanged            : typing.ClassVar[Signal] = ... # volumeChanged(float)

    @typing.overload
    def __init__(self, device: PySide6.QtMultimedia.QAudioDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, volume: float | None = ..., muted: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, device: PySide6.QtMultimedia.QAudioDevice | None = ..., volume: float | None = ..., muted: bool | None = ...) -> None: ...

    def device(self, /) -> PySide6.QtMultimedia.QAudioDevice: ...
    def is_muted(self, /) -> bool: ...
    def set_device(self, device: PySide6.QtMultimedia.QAudioDevice, /) -> None: ...
    def set_muted(self, muted: bool, /) -> None: ...
    def set_volume(self, volume: float, /) -> None: ...
    def volume(self, /) -> float: ...


class QAudioSink(PySide6.QtCore.QObject):

    stateChanged             : typing.ClassVar[Signal] = ... # stateChanged(QAudio::State)

    @typing.overload
    def __init__(self, audioDeviceInfo: PySide6.QtMultimedia.QAudioDevice, /, format: PySide6.QtMultimedia.QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, format: PySide6.QtMultimedia.QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def buffer_size(self, /) -> int: ...
    def bytes_free(self, /) -> int: ...
    def elapsedUSecs(self, /) -> int: ...
    def error(self, /) -> PySide6.QtMultimedia.QAudio.Error: ...
    def format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def is_null(self, /) -> bool: ...
    def processedUSecs(self, /) -> int: ...
    def reset(self, /) -> None: ...
    def resume(self, /) -> None: ...
    def set_buffer_size(self, bytes: int, /) -> None: ...
    def set_volume(self, arg__1: float, /) -> None: ...
    @typing.overload
    def start(self, /) -> PySide6.QtCore.QIODevice: ...
    @typing.overload
    def start(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def state(self, /) -> PySide6.QtMultimedia.QAudio.State: ...
    def stop(self, /) -> None: ...
    def suspend(self, /) -> None: ...
    def volume(self, /) -> float: ...


class QAudioSource(PySide6.QtCore.QObject):

    stateChanged             : typing.ClassVar[Signal] = ... # stateChanged(QAudio::State)

    @typing.overload
    def __init__(self, audioDeviceInfo: PySide6.QtMultimedia.QAudioDevice, /, format: PySide6.QtMultimedia.QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, format: PySide6.QtMultimedia.QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def buffer_size(self, /) -> int: ...
    def bytes_available(self, /) -> int: ...
    def elapsedUSecs(self, /) -> int: ...
    def error(self, /) -> PySide6.QtMultimedia.QAudio.Error: ...
    def format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def is_null(self, /) -> bool: ...
    def processedUSecs(self, /) -> int: ...
    def reset(self, /) -> None: ...
    def resume(self, /) -> None: ...
    def set_buffer_size(self, bytes: int, /) -> None: ...
    def set_volume(self, volume: float, /) -> None: ...
    @typing.overload
    def start(self, /) -> PySide6.QtCore.QIODevice: ...
    @typing.overload
    def start(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def state(self, /) -> PySide6.QtMultimedia.QAudio.State: ...
    def stop(self, /) -> None: ...
    def suspend(self, /) -> None: ...
    def volume(self, /) -> float: ...


class QCamera(PySide6.QtCore.QObject):

    activeChanged            : typing.ClassVar[Signal] = ... # activeChanged(bool)
    brightnessChanged        : typing.ClassVar[Signal] = ... # brightnessChanged()
    cameraDeviceChanged      : typing.ClassVar[Signal] = ... # cameraDeviceChanged()
    cameraFormatChanged      : typing.ClassVar[Signal] = ... # cameraFormatChanged()
    colorTemperatureChanged  : typing.ClassVar[Signal] = ... # colorTemperatureChanged()
    contrastChanged          : typing.ClassVar[Signal] = ... # contrastChanged()
    customFocusPointChanged  : typing.ClassVar[Signal] = ... # customFocusPointChanged()
    errorChanged             : typing.ClassVar[Signal] = ... # errorChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QCamera::Error,QString)
    exposureCompensationChanged: typing.ClassVar[Signal] = ... # exposureCompensationChanged(float)
    exposureModeChanged      : typing.ClassVar[Signal] = ... # exposureModeChanged()
    exposureTimeChanged      : typing.ClassVar[Signal] = ... # exposureTimeChanged(float)
    flashModeChanged         : typing.ClassVar[Signal] = ... # flashModeChanged()
    flashReady               : typing.ClassVar[Signal] = ... # flashReady(bool)
    focusDistanceChanged     : typing.ClassVar[Signal] = ... # focusDistanceChanged(float)
    focusModeChanged         : typing.ClassVar[Signal] = ... # focusModeChanged()
    focusPointChanged        : typing.ClassVar[Signal] = ... # focusPointChanged()
    hueChanged               : typing.ClassVar[Signal] = ... # hueChanged()
    isoSensitivityChanged    : typing.ClassVar[Signal] = ... # isoSensitivityChanged(int)
    manualExposureTimeChanged: typing.ClassVar[Signal] = ... # manualExposureTimeChanged(float)
    manualIsoSensitivityChanged: typing.ClassVar[Signal] = ... # manualIsoSensitivityChanged(int)
    maximumZoomFactorChanged : typing.ClassVar[Signal] = ... # maximumZoomFactorChanged(float)
    minimumZoomFactorChanged : typing.ClassVar[Signal] = ... # minimumZoomFactorChanged(float)
    saturationChanged        : typing.ClassVar[Signal] = ... # saturationChanged()
    supportedFeaturesChanged : typing.ClassVar[Signal] = ... # supportedFeaturesChanged()
    torchModeChanged         : typing.ClassVar[Signal] = ... # torchModeChanged()
    whiteBalanceModeChanged  : typing.ClassVar[Signal] = ... # whiteBalanceModeChanged()
    zoomFactorChanged        : typing.ClassVar[Signal] = ... # zoomFactorChanged(float)

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        CameraError               = ...  # 0x1

    class ExposureMode(enum.Enum):

        ExposureAuto              = ...  # 0x0
        ExposureManual            = ...  # 0x1
        ExposurePortrait          = ...  # 0x2
        ExposureNight             = ...  # 0x3
        ExposureSports            = ...  # 0x4
        ExposureSnow              = ...  # 0x5
        ExposureBeach             = ...  # 0x6
        ExposureAction            = ...  # 0x7
        ExposureLandscape         = ...  # 0x8
        ExposureNightPortrait     = ...  # 0x9
        ExposureTheatre           = ...  # 0xa
        ExposureSunset            = ...  # 0xb
        ExposureSteadyPhoto       = ...  # 0xc
        ExposureFireworks         = ...  # 0xd
        ExposureParty             = ...  # 0xe
        ExposureCandlelight       = ...  # 0xf
        ExposureBarcode           = ...  # 0x10

    class Feature(enum.Flag):

        ColorTemperature          = ...  # 0x1
        ExposureCompensation      = ...  # 0x2
        IsoSensitivity            = ...  # 0x4
        ManualExposureTime        = ...  # 0x8
        CustomFocusPoint          = ...  # 0x10
        FocusDistance             = ...  # 0x20

    class FlashMode(enum.Enum):

        FlashOff                  = ...  # 0x0
        FlashOn                   = ...  # 0x1
        FlashAuto                 = ...  # 0x2

    class FocusMode(enum.Enum):

        FocusModeAuto             = ...  # 0x0
        FocusModeAutoNear         = ...  # 0x1
        FocusModeAutoFar          = ...  # 0x2
        FocusModeHyperfocal       = ...  # 0x3
        FocusModeInfinity         = ...  # 0x4
        FocusModeManual           = ...  # 0x5

    class TorchMode(enum.Enum):

        TorchOff                  = ...  # 0x0
        TorchOn                   = ...  # 0x1
        TorchAuto                 = ...  # 0x2

    class WhiteBalanceMode(enum.Enum):

        WhiteBalanceAuto          = ...  # 0x0
        WhiteBalanceManual        = ...  # 0x1
        WhiteBalanceSunlight      = ...  # 0x2
        WhiteBalanceCloudy        = ...  # 0x3
        WhiteBalanceShade         = ...  # 0x4
        WhiteBalanceTungsten      = ...  # 0x5
        WhiteBalanceFluorescent   = ...  # 0x6
        WhiteBalanceFlash         = ...  # 0x7
        WhiteBalanceSunset        = ...  # 0x8


    @typing.overload
    def __init__(self, position: PySide6.QtMultimedia.QCameraDevice.Position, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., camera_device: PySide6.QtMultimedia.QCameraDevice | None = ..., error: PySide6.QtMultimedia.QCamera.Error | None = ..., error_string: str | None = ..., camera_format: PySide6.QtMultimedia.QCameraFormat | None = ..., focus_mode: PySide6.QtMultimedia.QCamera.FocusMode | None = ..., focus_point: PySide6.QtCore.QPointF | None = ..., custom_focus_point: PySide6.QtCore.QPointF | None = ..., focus_distance: float | None = ..., minimum_zoom_factor: float | None = ..., maximum_zoom_factor: float | None = ..., zoom_factor: float | None = ..., exposure_time: float | None = ..., manual_exposure_time: float | None = ..., iso_sensitivity: int | None = ..., manual_iso_sensitivity: int | None = ..., exposure_compensation: float | None = ..., exposure_mode: PySide6.QtMultimedia.QCamera.ExposureMode | None = ..., flash_ready: bool | None = ..., flash_mode: PySide6.QtMultimedia.QCamera.FlashMode | None = ..., torch_mode: PySide6.QtMultimedia.QCamera.TorchMode | None = ..., white_balance_mode: PySide6.QtMultimedia.QCamera.WhiteBalanceMode | None = ..., color_temperature: int | None = ..., supported_features: PySide6.QtMultimedia.QCamera.Feature | None = ...) -> None: ...
    @typing.overload
    def __init__(self, camera_device: PySide6.QtMultimedia.QCameraDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., error: PySide6.QtMultimedia.QCamera.Error | None = ..., error_string: str | None = ..., camera_format: PySide6.QtMultimedia.QCameraFormat | None = ..., focus_mode: PySide6.QtMultimedia.QCamera.FocusMode | None = ..., focus_point: PySide6.QtCore.QPointF | None = ..., custom_focus_point: PySide6.QtCore.QPointF | None = ..., focus_distance: float | None = ..., minimum_zoom_factor: float | None = ..., maximum_zoom_factor: float | None = ..., zoom_factor: float | None = ..., exposure_time: float | None = ..., manual_exposure_time: float | None = ..., iso_sensitivity: int | None = ..., manual_iso_sensitivity: int | None = ..., exposure_compensation: float | None = ..., exposure_mode: PySide6.QtMultimedia.QCamera.ExposureMode | None = ..., flash_ready: bool | None = ..., flash_mode: PySide6.QtMultimedia.QCamera.FlashMode | None = ..., torch_mode: PySide6.QtMultimedia.QCamera.TorchMode | None = ..., white_balance_mode: PySide6.QtMultimedia.QCamera.WhiteBalanceMode | None = ..., color_temperature: int | None = ..., supported_features: PySide6.QtMultimedia.QCamera.Feature | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., camera_device: PySide6.QtMultimedia.QCameraDevice | None = ..., error: PySide6.QtMultimedia.QCamera.Error | None = ..., error_string: str | None = ..., camera_format: PySide6.QtMultimedia.QCameraFormat | None = ..., focus_mode: PySide6.QtMultimedia.QCamera.FocusMode | None = ..., focus_point: PySide6.QtCore.QPointF | None = ..., custom_focus_point: PySide6.QtCore.QPointF | None = ..., focus_distance: float | None = ..., minimum_zoom_factor: float | None = ..., maximum_zoom_factor: float | None = ..., zoom_factor: float | None = ..., exposure_time: float | None = ..., manual_exposure_time: float | None = ..., iso_sensitivity: int | None = ..., manual_iso_sensitivity: int | None = ..., exposure_compensation: float | None = ..., exposure_mode: PySide6.QtMultimedia.QCamera.ExposureMode | None = ..., flash_ready: bool | None = ..., flash_mode: PySide6.QtMultimedia.QCamera.FlashMode | None = ..., torch_mode: PySide6.QtMultimedia.QCamera.TorchMode | None = ..., white_balance_mode: PySide6.QtMultimedia.QCamera.WhiteBalanceMode | None = ..., color_temperature: int | None = ..., supported_features: PySide6.QtMultimedia.QCamera.Feature | None = ...) -> None: ...

    def camera_device(self, /) -> PySide6.QtMultimedia.QCameraDevice: ...
    def camera_format(self, /) -> PySide6.QtMultimedia.QCameraFormat: ...
    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def color_temperature(self, /) -> int: ...
    def custom_focus_point(self, /) -> PySide6.QtCore.QPointF: ...
    def error(self, /) -> PySide6.QtMultimedia.QCamera.Error: ...
    def error_string(self, /) -> str: ...
    def exposure_compensation(self, /) -> float: ...
    def exposure_mode(self, /) -> PySide6.QtMultimedia.QCamera.ExposureMode: ...
    def exposure_time(self, /) -> float: ...
    def flash_mode(self, /) -> PySide6.QtMultimedia.QCamera.FlashMode: ...
    def focus_distance(self, /) -> float: ...
    def focus_mode(self, /) -> PySide6.QtMultimedia.QCamera.FocusMode: ...
    def focus_point(self, /) -> PySide6.QtCore.QPointF: ...
    def is_active(self, /) -> bool: ...
    def is_available(self, /) -> bool: ...
    def is_exposure_mode_supported(self, mode: PySide6.QtMultimedia.QCamera.ExposureMode, /) -> bool: ...
    def is_flash_mode_supported(self, mode: PySide6.QtMultimedia.QCamera.FlashMode, /) -> bool: ...
    def is_flash_ready(self, /) -> bool: ...
    def is_focus_mode_supported(self, mode: PySide6.QtMultimedia.QCamera.FocusMode, /) -> bool: ...
    def is_torch_mode_supported(self, mode: PySide6.QtMultimedia.QCamera.TorchMode, /) -> bool: ...
    def is_white_balance_mode_supported(self, mode: PySide6.QtMultimedia.QCamera.WhiteBalanceMode, /) -> bool: ...
    def iso_sensitivity(self, /) -> int: ...
    def manual_exposure_time(self, /) -> float: ...
    def manual_iso_sensitivity(self, /) -> int: ...
    def maximum_exposure_time(self, /) -> float: ...
    def maximum_iso_sensitivity(self, /) -> int: ...
    def maximum_zoom_factor(self, /) -> float: ...
    def minimum_exposure_time(self, /) -> float: ...
    def minimum_iso_sensitivity(self, /) -> int: ...
    def minimum_zoom_factor(self, /) -> float: ...
    def set_active(self, active: bool, /) -> None: ...
    def set_auto_exposure_time(self, /) -> None: ...
    def set_auto_iso_sensitivity(self, /) -> None: ...
    def set_camera_device(self, cameraDevice: PySide6.QtMultimedia.QCameraDevice, /) -> None: ...
    def set_camera_format(self, format: PySide6.QtMultimedia.QCameraFormat, /) -> None: ...
    def set_color_temperature(self, colorTemperature: int, /) -> None: ...
    def set_custom_focus_point(self, point: PySide6.QtCore.QPointF | PySide6.QtCore.QPoint | PySide6.QtGui.QPainterPath.Element, /) -> None: ...
    def set_exposure_compensation(self, ev: float, /) -> None: ...
    def set_exposure_mode(self, mode: PySide6.QtMultimedia.QCamera.ExposureMode, /) -> None: ...
    def set_flash_mode(self, mode: PySide6.QtMultimedia.QCamera.FlashMode, /) -> None: ...
    def set_focus_distance(self, d: float, /) -> None: ...
    def set_focus_mode(self, mode: PySide6.QtMultimedia.QCamera.FocusMode, /) -> None: ...
    def set_manual_exposure_time(self, seconds: float, /) -> None: ...
    def set_manual_iso_sensitivity(self, iso: int, /) -> None: ...
    def set_torch_mode(self, mode: PySide6.QtMultimedia.QCamera.TorchMode, /) -> None: ...
    def set_white_balance_mode(self, mode: PySide6.QtMultimedia.QCamera.WhiteBalanceMode, /) -> None: ...
    def set_zoom_factor(self, factor: float, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...
    def supported_features(self, /) -> PySide6.QtMultimedia.QCamera.Feature: ...
    def torch_mode(self, /) -> PySide6.QtMultimedia.QCamera.TorchMode: ...
    def white_balance_mode(self, /) -> PySide6.QtMultimedia.QCamera.WhiteBalanceMode: ...
    def zoom_factor(self, /) -> float: ...
    def zoom_to(self, zoom: float, rate: float, /) -> None: ...


class QCameraDevice(Shiboken.Object):

    class Position(enum.Enum):

        UnspecifiedPosition       = ...  # 0x0
        BackFace                  = ...  # 0x1
        FrontFace                 = ...  # 0x2


    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QCameraDevice, /, *, id: PySide6.QtCore.QByteArray | None = ..., description: str | None = ..., is_default: bool | None = ..., position: PySide6.QtMultimedia.QCameraDevice.Position | None = ..., video_formats: collections.abc.Sequence[PySide6.QtMultimedia.QCameraFormat] | None = ..., correction_angle: PySide6.QtMultimedia.QtVideo.Rotation | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, id: PySide6.QtCore.QByteArray | None = ..., description: str | None = ..., is_default: bool | None = ..., position: PySide6.QtMultimedia.QCameraDevice.Position | None = ..., video_formats: collections.abc.Sequence[PySide6.QtMultimedia.QCameraFormat] | None = ..., correction_angle: PySide6.QtMultimedia.QtVideo.Rotation | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtMultimedia.QCameraDevice, /) -> bool: ...
    def __ne__(self, other: PySide6.QtMultimedia.QCameraDevice, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def correction_angle(self, /) -> PySide6.QtMultimedia.QtVideo.Rotation: ...
    def description(self, /) -> str: ...
    def id(self, /) -> PySide6.QtCore.QByteArray: ...
    def is_default(self, /) -> bool: ...
    def is_null(self, /) -> bool: ...
    def photo_resolutions(self, /) -> typing.List[PySide6.QtCore.QSize]: ...
    def position(self, /) -> PySide6.QtMultimedia.QCameraDevice.Position: ...
    def video_formats(self, /) -> typing.List[PySide6.QtMultimedia.QCameraFormat]: ...


class QCameraFormat(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QCameraFormat, /, *, resolution: PySide6.QtCore.QSize | None = ..., pixel_format: PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat | None = ..., min_frame_rate: float | None = ..., max_frame_rate: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, resolution: PySide6.QtCore.QSize | None = ..., pixel_format: PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat | None = ..., min_frame_rate: float | None = ..., max_frame_rate: float | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtMultimedia.QCameraFormat, /) -> bool: ...
    def __ne__(self, other: PySide6.QtMultimedia.QCameraFormat, /) -> bool: ...
    def is_null(self, /) -> bool: ...
    def max_frame_rate(self, /) -> float: ...
    def min_frame_rate(self, /) -> float: ...
    def pixel_format(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat: ...
    def resolution(self, /) -> PySide6.QtCore.QSize: ...


class QCapturableWindow(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QCapturableWindow, /, *, description: str | None = ..., is_valid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, description: str | None = ..., is_valid: bool | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __ne__(self, rhs: PySide6.QtMultimedia.QCapturableWindow, /) -> bool: ...
    def description(self, /) -> str: ...
    def is_valid(self, /) -> bool: ...
    def swap(self, other: PySide6.QtMultimedia.QCapturableWindow, /) -> None: ...


class QImageCapture(PySide6.QtCore.QObject):

    errorChanged             : typing.ClassVar[Signal] = ... # errorChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(int,QImageCapture::Error,QString)
    fileFormatChanged        : typing.ClassVar[Signal] = ... # fileFormatChanged()
    imageAvailable           : typing.ClassVar[Signal] = ... # imageAvailable(int,QVideoFrame)
    imageCaptured            : typing.ClassVar[Signal] = ... # imageCaptured(int,QImage)
    imageExposed             : typing.ClassVar[Signal] = ... # imageExposed(int)
    imageMetadataAvailable   : typing.ClassVar[Signal] = ... # imageMetadataAvailable(int,QMediaMetaData)
    imageSaved               : typing.ClassVar[Signal] = ... # imageSaved(int,QString)
    metaDataChanged          : typing.ClassVar[Signal] = ... # metaDataChanged()
    qualityChanged           : typing.ClassVar[Signal] = ... # qualityChanged()
    readyForCaptureChanged   : typing.ClassVar[Signal] = ... # readyForCaptureChanged(bool)
    resolutionChanged        : typing.ClassVar[Signal] = ... # resolutionChanged()

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        NotReadyError             = ...  # 0x1
        ResourceError             = ...  # 0x2
        OutOfSpaceError           = ...  # 0x3
        NotSupportedFeatureError  = ...  # 0x4
        FormatError               = ...  # 0x5

    class FileFormat(enum.Enum):

        UnspecifiedFormat         = ...  # 0x0
        JPEG                      = ...  # 0x1
        PNG                       = ...  # 0x2
        WebP                      = ...  # 0x3
        LastFileFormat            = ...  # 0x4
        Tiff                      = ...  # 0x4

    class Quality(enum.Enum):

        VeryLowQuality            = ...  # 0x0
        LowQuality                = ...  # 0x1
        NormalQuality             = ...  # 0x2
        HighQuality               = ...  # 0x3
        VeryHighQuality           = ...  # 0x4


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, ready_for_capture: bool | None = ..., meta_data: PySide6.QtMultimedia.QMediaMetaData | None = ..., error: PySide6.QtMultimedia.QImageCapture.Error | None = ..., error_string: str | None = ..., file_format: PySide6.QtMultimedia.QImageCapture.FileFormat | None = ..., quality: PySide6.QtMultimedia.QImageCapture.Quality | None = ...) -> None: ...

    def add_meta_data(self, metaData: PySide6.QtMultimedia.QMediaMetaData, /) -> None: ...
    def capture(self, /) -> int: ...
    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def capture_to_file(self, /, location: str = ...) -> int: ...
    def error(self, /) -> PySide6.QtMultimedia.QImageCapture.Error: ...
    def error_string(self, /) -> str: ...
    def file_format(self, /) -> PySide6.QtMultimedia.QImageCapture.FileFormat: ...
    @staticmethod
    def file_format_description(c: PySide6.QtMultimedia.QImageCapture.FileFormat, /) -> str: ...
    @staticmethod
    def file_format_name(c: PySide6.QtMultimedia.QImageCapture.FileFormat, /) -> str: ...
    def is_available(self, /) -> bool: ...
    def is_ready_for_capture(self, /) -> bool: ...
    def meta_data(self, /) -> PySide6.QtMultimedia.QMediaMetaData: ...
    def quality(self, /) -> PySide6.QtMultimedia.QImageCapture.Quality: ...
    def resolution(self, /) -> PySide6.QtCore.QSize: ...
    def set_file_format(self, format: PySide6.QtMultimedia.QImageCapture.FileFormat, /) -> None: ...
    def set_meta_data(self, metaData: PySide6.QtMultimedia.QMediaMetaData, /) -> None: ...
    def set_quality(self, quality: PySide6.QtMultimedia.QImageCapture.Quality, /) -> None: ...
    @typing.overload
    def set_resolution(self, arg__1: PySide6.QtCore.QSize, /) -> None: ...
    @typing.overload
    def set_resolution(self, width: int, height: int, /) -> None: ...
    @staticmethod
    def supported_formats() -> typing.List[PySide6.QtMultimedia.QImageCapture.FileFormat]: ...


class QIntList: ...


class QMediaCaptureSession(PySide6.QtCore.QObject):

    audioBufferInputChanged  : typing.ClassVar[Signal] = ... # audioBufferInputChanged()
    audioInputChanged        : typing.ClassVar[Signal] = ... # audioInputChanged()
    audioOutputChanged       : typing.ClassVar[Signal] = ... # audioOutputChanged()
    cameraChanged            : typing.ClassVar[Signal] = ... # cameraChanged()
    imageCaptureChanged      : typing.ClassVar[Signal] = ... # imageCaptureChanged()
    recorderChanged          : typing.ClassVar[Signal] = ... # recorderChanged()
    screenCaptureChanged     : typing.ClassVar[Signal] = ... # screenCaptureChanged()
    videoFrameInputChanged   : typing.ClassVar[Signal] = ... # videoFrameInputChanged()
    videoOutputChanged       : typing.ClassVar[Signal] = ... # videoOutputChanged()
    windowCaptureChanged     : typing.ClassVar[Signal] = ... # windowCaptureChanged()

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, audio_input: PySide6.QtMultimedia.QAudioInput | None = ..., audio_buffer_input: PySide6.QtMultimedia.QAudioBufferInput | None = ..., audio_output: PySide6.QtMultimedia.QAudioOutput | None = ..., camera: PySide6.QtMultimedia.QCamera | None = ..., screen_capture: PySide6.QtMultimedia.QScreenCapture | None = ..., window_capture: PySide6.QtMultimedia.QWindowCapture | None = ..., video_frame_input: PySide6.QtMultimedia.QVideoFrameInput | None = ..., image_capture: PySide6.QtMultimedia.QImageCapture | None = ..., recorder: PySide6.QtMultimedia.QMediaRecorder | None = ..., video_output: PySide6.QtCore.QObject | None = ...) -> None: ...

    def audio_buffer_input(self, /) -> PySide6.QtMultimedia.QAudioBufferInput: ...
    def audio_input(self, /) -> PySide6.QtMultimedia.QAudioInput: ...
    def audio_output(self, /) -> PySide6.QtMultimedia.QAudioOutput: ...
    def camera(self, /) -> PySide6.QtMultimedia.QCamera: ...
    def image_capture(self, /) -> PySide6.QtMultimedia.QImageCapture: ...
    def recorder(self, /) -> PySide6.QtMultimedia.QMediaRecorder: ...
    def screen_capture(self, /) -> PySide6.QtMultimedia.QScreenCapture: ...
    def set_audio_buffer_input(self, input: PySide6.QtMultimedia.QAudioBufferInput, /) -> None: ...
    def set_audio_input(self, input: PySide6.QtMultimedia.QAudioInput, /) -> None: ...
    def set_audio_output(self, output: PySide6.QtMultimedia.QAudioOutput, /) -> None: ...
    def set_camera(self, camera: PySide6.QtMultimedia.QCamera, /) -> None: ...
    def set_image_capture(self, imageCapture: PySide6.QtMultimedia.QImageCapture, /) -> None: ...
    def set_recorder(self, recorder: PySide6.QtMultimedia.QMediaRecorder, /) -> None: ...
    def set_screen_capture(self, screenCapture: PySide6.QtMultimedia.QScreenCapture, /) -> None: ...
    def set_video_frame_input(self, input: PySide6.QtMultimedia.QVideoFrameInput, /) -> None: ...
    def set_video_output(self, output: PySide6.QtCore.QObject, /) -> None: ...
    def set_video_sink(self, sink: PySide6.QtMultimedia.QVideoSink, /) -> None: ...
    def set_window_capture(self, windowCapture: PySide6.QtMultimedia.QWindowCapture, /) -> None: ...
    def video_frame_input(self, /) -> PySide6.QtMultimedia.QVideoFrameInput: ...
    def video_output(self, /) -> PySide6.QtCore.QObject: ...
    def video_sink(self, /) -> PySide6.QtMultimedia.QVideoSink: ...
    def window_capture(self, /) -> PySide6.QtMultimedia.QWindowCapture: ...


class QMediaDevices(PySide6.QtCore.QObject):

    audioInputsChanged       : typing.ClassVar[Signal] = ... # audioInputsChanged()
    audioOutputsChanged      : typing.ClassVar[Signal] = ... # audioOutputsChanged()
    videoInputsChanged       : typing.ClassVar[Signal] = ... # videoInputsChanged()

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, audio_inputs: collections.abc.Sequence[PySide6.QtMultimedia.QAudioDevice] | None = ..., audio_outputs: collections.abc.Sequence[PySide6.QtMultimedia.QAudioDevice] | None = ..., video_inputs: collections.abc.Sequence[PySide6.QtMultimedia.QCameraDevice] | None = ..., default_audio_input: PySide6.QtMultimedia.QAudioDevice | None = ..., default_audio_output: PySide6.QtMultimedia.QAudioDevice | None = ..., default_video_input: PySide6.QtMultimedia.QCameraDevice | None = ...) -> None: ...

    @staticmethod
    def audio_inputs() -> typing.List[PySide6.QtMultimedia.QAudioDevice]: ...
    @staticmethod
    def audio_outputs() -> typing.List[PySide6.QtMultimedia.QAudioDevice]: ...
    def connect_notify(self, signal: PySide6.QtCore.QMetaMethod, /) -> None: ...
    @staticmethod
    def default_audio_input() -> PySide6.QtMultimedia.QAudioDevice: ...
    @staticmethod
    def default_audio_output() -> PySide6.QtMultimedia.QAudioDevice: ...
    @staticmethod
    def default_video_input() -> PySide6.QtMultimedia.QCameraDevice: ...
    @staticmethod
    def video_inputs() -> typing.List[PySide6.QtMultimedia.QCameraDevice]: ...


class QMediaFormat(Shiboken.Object):

    class AudioCodec(enum.Enum):

        Unspecified               = ...  # -1
        MP3                       = ...  # 0x0
        AAC                       = ...  # 0x1
        AC3                       = ...  # 0x2
        EAC3                      = ...  # 0x3
        FLAC                      = ...  # 0x4
        DolbyTrueHD               = ...  # 0x5
        Opus                      = ...  # 0x6
        Vorbis                    = ...  # 0x7
        Wave                      = ...  # 0x8
        WMA                       = ...  # 0x9
        ALAC                      = ...  # 0xa
        LastAudioCodec            = ...  # 0xa

    class ConversionMode(enum.Enum):

        Encode                    = ...  # 0x0
        Decode                    = ...  # 0x1

    class FileFormat(enum.Enum):

        UnspecifiedFormat         = ...  # -1
        WMV                       = ...  # 0x0
        AVI                       = ...  # 0x1
        Matroska                  = ...  # 0x2
        MPEG4                     = ...  # 0x3
        Ogg                       = ...  # 0x4
        QuickTime                 = ...  # 0x5
        WebM                      = ...  # 0x6
        Mpeg4Audio                = ...  # 0x7
        AAC                       = ...  # 0x8
        WMA                       = ...  # 0x9
        MP3                       = ...  # 0xa
        FLAC                      = ...  # 0xb
        LastFileFormat            = ...  # 0xc
        Wave                      = ...  # 0xc

    class ResolveFlags(enum.Enum):

        NoFlags                   = ...  # 0x0
        RequiresVideo             = ...  # 0x1

    class VideoCodec(enum.Enum):

        Unspecified               = ...  # -1
        MPEG1                     = ...  # 0x0
        MPEG2                     = ...  # 0x1
        MPEG4                     = ...  # 0x2
        H264                      = ...  # 0x3
        H265                      = ...  # 0x4
        VP8                       = ...  # 0x5
        VP9                       = ...  # 0x6
        AV1                       = ...  # 0x7
        Theora                    = ...  # 0x8
        WMV                       = ...  # 0x9
        LastVideoCodec            = ...  # 0xa
        MotionJPEG                = ...  # 0xa


    @typing.overload
    def __init__(self, /, format: PySide6.QtMultimedia.QMediaFormat.FileFormat = ..., *, file_format: PySide6.QtMultimedia.QMediaFormat.FileFormat | None = ..., audio_codec: PySide6.QtMultimedia.QMediaFormat.AudioCodec | None = ..., video_codec: PySide6.QtMultimedia.QMediaFormat.VideoCodec | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QMediaFormat, /, *, file_format: PySide6.QtMultimedia.QMediaFormat.FileFormat | None = ..., audio_codec: PySide6.QtMultimedia.QMediaFormat.AudioCodec | None = ..., video_codec: PySide6.QtMultimedia.QMediaFormat.VideoCodec | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtMultimedia.QMediaFormat | PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> bool: ...
    def __ne__(self, other: PySide6.QtMultimedia.QMediaFormat | PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> bool: ...
    def audio_codec(self, /) -> PySide6.QtMultimedia.QMediaFormat.AudioCodec: ...
    @staticmethod
    def audio_codec_description(codec: PySide6.QtMultimedia.QMediaFormat.AudioCodec, /) -> str: ...
    @staticmethod
    def audio_codec_name(codec: PySide6.QtMultimedia.QMediaFormat.AudioCodec, /) -> str: ...
    def file_format(self, /) -> PySide6.QtMultimedia.QMediaFormat.FileFormat: ...
    @staticmethod
    def file_format_description(fileFormat: PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> str: ...
    @staticmethod
    def file_format_name(fileFormat: PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> str: ...
    def is_supported(self, mode: PySide6.QtMultimedia.QMediaFormat.ConversionMode, /) -> bool: ...
    def mime_type(self, /) -> PySide6.QtCore.QMimeType: ...
    def resolve_for_encoding(self, flags: PySide6.QtMultimedia.QMediaFormat.ResolveFlags, /) -> None: ...
    def set_audio_codec(self, codec: PySide6.QtMultimedia.QMediaFormat.AudioCodec, /) -> None: ...
    def set_file_format(self, f: PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> None: ...
    def set_video_codec(self, codec: PySide6.QtMultimedia.QMediaFormat.VideoCodec, /) -> None: ...
    def supported_audio_codecs(self, m: PySide6.QtMultimedia.QMediaFormat.ConversionMode, /) -> typing.List[PySide6.QtMultimedia.QMediaFormat.AudioCodec]: ...
    def supported_file_formats(self, m: PySide6.QtMultimedia.QMediaFormat.ConversionMode, /) -> typing.List[PySide6.QtMultimedia.QMediaFormat.FileFormat]: ...
    def supported_video_codecs(self, m: PySide6.QtMultimedia.QMediaFormat.ConversionMode, /) -> typing.List[PySide6.QtMultimedia.QMediaFormat.VideoCodec]: ...
    def swap(self, other: PySide6.QtMultimedia.QMediaFormat | PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> None: ...
    def video_codec(self, /) -> PySide6.QtMultimedia.QMediaFormat.VideoCodec: ...
    @staticmethod
    def video_codec_description(codec: PySide6.QtMultimedia.QMediaFormat.VideoCodec, /) -> str: ...
    @staticmethod
    def video_codec_name(codec: PySide6.QtMultimedia.QMediaFormat.VideoCodec, /) -> str: ...


class QMediaMetaData(Shiboken.Object):

    class Key(enum.Enum):

        Title                     = ...  # 0x0
        Author                    = ...  # 0x1
        Comment                   = ...  # 0x2
        Description               = ...  # 0x3
        Genre                     = ...  # 0x4
        Date                      = ...  # 0x5
        Language                  = ...  # 0x6
        Publisher                 = ...  # 0x7
        Copyright                 = ...  # 0x8
        Url                       = ...  # 0x9
        Duration                  = ...  # 0xa
        MediaType                 = ...  # 0xb
        FileFormat                = ...  # 0xc
        AudioBitRate              = ...  # 0xd
        AudioCodec                = ...  # 0xe
        VideoBitRate              = ...  # 0xf
        VideoCodec                = ...  # 0x10
        VideoFrameRate            = ...  # 0x11
        AlbumTitle                = ...  # 0x12
        AlbumArtist               = ...  # 0x13
        ContributingArtist        = ...  # 0x14
        TrackNumber               = ...  # 0x15
        Composer                  = ...  # 0x16
        LeadPerformer             = ...  # 0x17
        ThumbnailImage            = ...  # 0x18
        CoverArtImage             = ...  # 0x19
        Orientation               = ...  # 0x1a
        Resolution                = ...  # 0x1b
        HasHdrContent             = ...  # 0x1c


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, QMediaMetaData: PySide6.QtMultimedia.QMediaMetaData, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, b: PySide6.QtMultimedia.QMediaMetaData, /) -> bool: ...
    def __ne__(self, b: PySide6.QtMultimedia.QMediaMetaData, /) -> bool: ...
    def clear(self, /) -> None: ...
    def insert(self, k: PySide6.QtMultimedia.QMediaMetaData.Key, value: typing.Any, /) -> None: ...
    def is_empty(self, /) -> bool: ...
    @staticmethod
    def key_type(key: PySide6.QtMultimedia.QMediaMetaData.Key, /) -> PySide6.QtCore.QMetaType: ...
    def keys(self, /) -> typing.List[PySide6.QtMultimedia.QMediaMetaData.Key]: ...
    @staticmethod
    def meta_data_key_to_string(k: PySide6.QtMultimedia.QMediaMetaData.Key, /) -> str: ...
    def remove(self, k: PySide6.QtMultimedia.QMediaMetaData.Key, /) -> None: ...
    def string_value(self, k: PySide6.QtMultimedia.QMediaMetaData.Key, /) -> str: ...
    def value(self, k: PySide6.QtMultimedia.QMediaMetaData.Key, /) -> typing.Any: ...


class QMediaPlayer(PySide6.QtCore.QObject):

    activeTracksChanged      : typing.ClassVar[Signal] = ... # activeTracksChanged()
    audioBufferOutputChanged : typing.ClassVar[Signal] = ... # audioBufferOutputChanged()
    audioOutputChanged       : typing.ClassVar[Signal] = ... # audioOutputChanged()
    bufferProgressChanged    : typing.ClassVar[Signal] = ... # bufferProgressChanged(float)
    durationChanged          : typing.ClassVar[Signal] = ... # durationChanged(qlonglong)
    errorChanged             : typing.ClassVar[Signal] = ... # errorChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QMediaPlayer::Error,QString)
    hasAudioChanged          : typing.ClassVar[Signal] = ... # hasAudioChanged(bool)
    hasVideoChanged          : typing.ClassVar[Signal] = ... # hasVideoChanged(bool)
    loopsChanged             : typing.ClassVar[Signal] = ... # loopsChanged()
    mediaStatusChanged       : typing.ClassVar[Signal] = ... # mediaStatusChanged(QMediaPlayer::MediaStatus)
    metaDataChanged          : typing.ClassVar[Signal] = ... # metaDataChanged()
    playbackRateChanged      : typing.ClassVar[Signal] = ... # playbackRateChanged(double)
    playbackStateChanged     : typing.ClassVar[Signal] = ... # playbackStateChanged(QMediaPlayer::PlaybackState)
    playingChanged           : typing.ClassVar[Signal] = ... # playingChanged(bool)
    positionChanged          : typing.ClassVar[Signal] = ... # positionChanged(qlonglong)
    seekableChanged          : typing.ClassVar[Signal] = ... # seekableChanged(bool)
    sourceChanged            : typing.ClassVar[Signal] = ... # sourceChanged(QUrl)
    tracksChanged            : typing.ClassVar[Signal] = ... # tracksChanged()
    videoOutputChanged       : typing.ClassVar[Signal] = ... # videoOutputChanged()

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        ResourceError             = ...  # 0x1
        FormatError               = ...  # 0x2
        NetworkError              = ...  # 0x3
        AccessDeniedError         = ...  # 0x4

    class Loops(enum.IntEnum):

        Infinite                  = ...  # -1
        Once                      = ...  # 0x1

    class MediaStatus(enum.Enum):

        NoMedia                   = ...  # 0x0
        LoadingMedia              = ...  # 0x1
        LoadedMedia               = ...  # 0x2
        StalledMedia              = ...  # 0x3
        BufferingMedia            = ...  # 0x4
        BufferedMedia             = ...  # 0x5
        EndOfMedia                = ...  # 0x6
        InvalidMedia              = ...  # 0x7

    class PlaybackState(enum.Enum):

        StoppedState              = ...  # 0x0
        PlayingState              = ...  # 0x1
        PausedState               = ...  # 0x2


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., duration: int | None = ..., position: int | None = ..., buffer_progress: float | None = ..., has_audio: bool | None = ..., has_video: bool | None = ..., seekable: bool | None = ..., playing: bool | None = ..., playback_rate: float | None = ..., loops: int | None = ..., playback_state: PySide6.QtMultimedia.QMediaPlayer.PlaybackState | None = ..., media_status: PySide6.QtMultimedia.QMediaPlayer.MediaStatus | None = ..., meta_data: PySide6.QtMultimedia.QMediaMetaData | None = ..., error: PySide6.QtMultimedia.QMediaPlayer.Error | None = ..., error_string: str | None = ..., video_output: PySide6.QtCore.QObject | None = ..., audio_output: PySide6.QtMultimedia.QAudioOutput | None = ..., audio_buffer_output: PySide6.QtMultimedia.QAudioBufferOutput | None = ..., audio_tracks: collections.abc.Sequence[PySide6.QtMultimedia.QMediaMetaData] | None = ..., video_tracks: collections.abc.Sequence[PySide6.QtMultimedia.QMediaMetaData] | None = ..., subtitle_tracks: collections.abc.Sequence[PySide6.QtMultimedia.QMediaMetaData] | None = ..., active_audio_track: int | None = ..., active_video_track: int | None = ..., active_subtitle_track: int | None = ...) -> None: ...

    def active_audio_track(self, /) -> int: ...
    def active_subtitle_track(self, /) -> int: ...
    def active_video_track(self, /) -> int: ...
    def audio_buffer_output(self, /) -> PySide6.QtMultimedia.QAudioBufferOutput: ...
    def audio_output(self, /) -> PySide6.QtMultimedia.QAudioOutput: ...
    def audio_tracks(self, /) -> typing.List[PySide6.QtMultimedia.QMediaMetaData]: ...
    def buffer_progress(self, /) -> float: ...
    def buffered_time_range(self, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    def duration(self, /) -> int: ...
    def error(self, /) -> PySide6.QtMultimedia.QMediaPlayer.Error: ...
    def error_string(self, /) -> str: ...
    def has_audio(self, /) -> bool: ...
    def has_video(self, /) -> bool: ...
    def is_available(self, /) -> bool: ...
    def is_playing(self, /) -> bool: ...
    def is_seekable(self, /) -> bool: ...
    def loops(self, /) -> int: ...
    def media_status(self, /) -> PySide6.QtMultimedia.QMediaPlayer.MediaStatus: ...
    def meta_data(self, /) -> PySide6.QtMultimedia.QMediaMetaData: ...
    def pause(self, /) -> None: ...
    def play(self, /) -> None: ...
    def playback_rate(self, /) -> float: ...
    def playback_state(self, /) -> PySide6.QtMultimedia.QMediaPlayer.PlaybackState: ...
    def position(self, /) -> int: ...
    def set_active_audio_track(self, index: int, /) -> None: ...
    def set_active_subtitle_track(self, index: int, /) -> None: ...
    def set_active_video_track(self, index: int, /) -> None: ...
    def set_audio_buffer_output(self, output: PySide6.QtMultimedia.QAudioBufferOutput, /) -> None: ...
    def set_audio_output(self, output: PySide6.QtMultimedia.QAudioOutput, /) -> None: ...
    def set_loops(self, loops: int, /) -> None: ...
    def set_playback_rate(self, rate: float, /) -> None: ...
    def set_position(self, position: int, /) -> None: ...
    def set_source(self, source: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_source_device(self, device: PySide6.QtCore.QIODevice, /, sourceUrl: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def set_video_output(self, arg__1: PySide6.QtCore.QObject, /) -> None: ...
    def set_video_sink(self, sink: PySide6.QtMultimedia.QVideoSink, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def source_device(self, /) -> PySide6.QtCore.QIODevice: ...
    def stop(self, /) -> None: ...
    def subtitle_tracks(self, /) -> typing.List[PySide6.QtMultimedia.QMediaMetaData]: ...
    def video_output(self, /) -> PySide6.QtCore.QObject: ...
    def video_sink(self, /) -> PySide6.QtMultimedia.QVideoSink: ...
    def video_tracks(self, /) -> typing.List[PySide6.QtMultimedia.QMediaMetaData]: ...


class QMediaRecorder(PySide6.QtCore.QObject):

    actualLocationChanged    : typing.ClassVar[Signal] = ... # actualLocationChanged(QUrl)
    audioBitRateChanged      : typing.ClassVar[Signal] = ... # audioBitRateChanged()
    audioChannelCountChanged : typing.ClassVar[Signal] = ... # audioChannelCountChanged()
    audioSampleRateChanged   : typing.ClassVar[Signal] = ... # audioSampleRateChanged()
    autoStopChanged          : typing.ClassVar[Signal] = ... # autoStopChanged()
    durationChanged          : typing.ClassVar[Signal] = ... # durationChanged(qlonglong)
    encoderSettingsChanged   : typing.ClassVar[Signal] = ... # encoderSettingsChanged()
    encodingModeChanged      : typing.ClassVar[Signal] = ... # encodingModeChanged()
    errorChanged             : typing.ClassVar[Signal] = ... # errorChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(Error,QString)
    mediaFormatChanged       : typing.ClassVar[Signal] = ... # mediaFormatChanged()
    metaDataChanged          : typing.ClassVar[Signal] = ... # metaDataChanged()
    qualityChanged           : typing.ClassVar[Signal] = ... # qualityChanged()
    recorderStateChanged     : typing.ClassVar[Signal] = ... # recorderStateChanged(RecorderState)
    videoBitRateChanged      : typing.ClassVar[Signal] = ... # videoBitRateChanged()
    videoFrameRateChanged    : typing.ClassVar[Signal] = ... # videoFrameRateChanged()
    videoResolutionChanged   : typing.ClassVar[Signal] = ... # videoResolutionChanged()

    class EncodingMode(enum.Enum):

        ConstantQualityEncoding   = ...  # 0x0
        ConstantBitRateEncoding   = ...  # 0x1
        AverageBitRateEncoding    = ...  # 0x2
        TwoPassEncoding           = ...  # 0x3

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        ResourceError             = ...  # 0x1
        FormatError               = ...  # 0x2
        OutOfSpaceError           = ...  # 0x3
        LocationNotWritable       = ...  # 0x4

    class Quality(enum.Enum):

        VeryLowQuality            = ...  # 0x0
        LowQuality                = ...  # 0x1
        NormalQuality             = ...  # 0x2
        HighQuality               = ...  # 0x3
        VeryHighQuality           = ...  # 0x4

    class RecorderState(enum.Enum):

        StoppedState              = ...  # 0x0
        RecordingState            = ...  # 0x1
        PausedState               = ...  # 0x2


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, recorder_state: PySide6.QtMultimedia.QMediaRecorder.RecorderState | None = ..., duration: int | None = ..., output_location: PySide6.QtCore.QUrl | None = ..., actual_location: PySide6.QtCore.QUrl | None = ..., meta_data: PySide6.QtMultimedia.QMediaMetaData | None = ..., error: PySide6.QtMultimedia.QMediaRecorder.Error | None = ..., error_string: str | None = ..., media_format: PySide6.QtMultimedia.QMediaFormat | None = ..., quality: PySide6.QtMultimedia.QMediaRecorder.Quality | None = ..., encoding_mode: PySide6.QtMultimedia.QMediaRecorder.EncodingMode | None = ..., video_resolution: PySide6.QtCore.QSize | None = ..., video_frame_rate: float | None = ..., video_bit_rate: int | None = ..., audio_bit_rate: int | None = ..., audio_channel_count: int | None = ..., audio_sample_rate: int | None = ..., auto_stop: bool | None = ...) -> None: ...

    def actual_location(self, /) -> PySide6.QtCore.QUrl: ...
    def add_meta_data(self, metaData: PySide6.QtMultimedia.QMediaMetaData, /) -> None: ...
    def audio_bit_rate(self, /) -> int: ...
    def audio_channel_count(self, /) -> int: ...
    def audio_sample_rate(self, /) -> int: ...
    def auto_stop(self, /) -> bool: ...
    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def duration(self, /) -> int: ...
    def encoding_mode(self, /) -> PySide6.QtMultimedia.QMediaRecorder.EncodingMode: ...
    def error(self, /) -> PySide6.QtMultimedia.QMediaRecorder.Error: ...
    def error_string(self, /) -> str: ...
    def is_available(self, /) -> bool: ...
    def media_format(self, /) -> PySide6.QtMultimedia.QMediaFormat: ...
    def meta_data(self, /) -> PySide6.QtMultimedia.QMediaMetaData: ...
    def output_device(self, /) -> PySide6.QtCore.QIODevice: ...
    def output_location(self, /) -> PySide6.QtCore.QUrl: ...
    def pause(self, /) -> None: ...
    def quality(self, /) -> PySide6.QtMultimedia.QMediaRecorder.Quality: ...
    def record(self, /) -> None: ...
    def recorder_state(self, /) -> PySide6.QtMultimedia.QMediaRecorder.RecorderState: ...
    def set_audio_bit_rate(self, bitRate: int, /) -> None: ...
    def set_audio_channel_count(self, channels: int, /) -> None: ...
    def set_audio_sample_rate(self, sampleRate: int, /) -> None: ...
    def set_auto_stop(self, autoStop: bool, /) -> None: ...
    def set_encoding_mode(self, arg__1: PySide6.QtMultimedia.QMediaRecorder.EncodingMode, /) -> None: ...
    def set_media_format(self, format: PySide6.QtMultimedia.QMediaFormat | PySide6.QtMultimedia.QMediaFormat.FileFormat, /) -> None: ...
    def set_meta_data(self, metaData: PySide6.QtMultimedia.QMediaMetaData, /) -> None: ...
    def set_output_device(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def set_output_location(self, location: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_quality(self, quality: PySide6.QtMultimedia.QMediaRecorder.Quality, /) -> None: ...
    def set_video_bit_rate(self, bitRate: int, /) -> None: ...
    def set_video_frame_rate(self, frameRate: float, /) -> None: ...
    @typing.overload
    def set_video_resolution(self, arg__1: PySide6.QtCore.QSize, /) -> None: ...
    @typing.overload
    def set_video_resolution(self, width: int, height: int, /) -> None: ...
    def stop(self, /) -> None: ...
    def video_bit_rate(self, /) -> int: ...
    def video_frame_rate(self, /) -> float: ...
    def video_resolution(self, /) -> PySide6.QtCore.QSize: ...


class QMediaTimeRange(Shiboken.Object):

    class Interval(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, Interval: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...
        @typing.overload
        def __init__(self, start: int, end: int, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...
        def __eq__(self, rhs: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> bool: ...
        def __ne__(self, rhs: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> bool: ...
        def __repr__(self, /) -> str: ...
        def contains(self, time: int, /) -> bool: ...
        def end(self, /) -> int: ...
        def is_normal(self, /) -> bool: ...
        def normalized(self, /) -> PySide6.QtMultimedia.QMediaTimeRange.Interval: ...
        def start(self, /) -> int: ...
        def translated(self, offset: int, /) -> PySide6.QtMultimedia.QMediaTimeRange.Interval: ...


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...
    @typing.overload
    def __init__(self, range: PySide6.QtMultimedia.QMediaTimeRange, /) -> None: ...
    @typing.overload
    def __init__(self, start: int, end: int, /) -> None: ...

    def __add__(self, r2: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> bool: ...
    @typing.overload  # type: ignore[misc]
    def __iadd__(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    @typing.overload
    def __iadd__(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    @typing.overload  # type: ignore[misc]
    def __isub__(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    @typing.overload
    def __isub__(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    def __ne__(self, rhs: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __sub__(self, r2: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> PySide6.QtMultimedia.QMediaTimeRange: ...
    @typing.overload
    def add_interval(self, interval: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...
    @typing.overload
    def add_interval(self, start: int, end: int, /) -> None: ...
    def add_time_range(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...
    def clear(self, /) -> None: ...
    def contains(self, time: int, /) -> bool: ...
    def earliest_time(self, /) -> int: ...
    def intervals(self, /) -> typing.List[PySide6.QtMultimedia.QMediaTimeRange.Interval]: ...
    def is_continuous(self, /) -> bool: ...
    def is_empty(self, /) -> bool: ...
    def latest_time(self, /) -> int: ...
    @typing.overload
    def remove_interval(self, interval: PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...
    @typing.overload
    def remove_interval(self, start: int, end: int, /) -> None: ...
    def remove_time_range(self, arg__1: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...
    def swap(self, other: PySide6.QtMultimedia.QMediaTimeRange | PySide6.QtMultimedia.QMediaTimeRange.Interval, /) -> None: ...


class QScreenCapture(PySide6.QtCore.QObject):

    activeChanged            : typing.ClassVar[Signal] = ... # activeChanged(bool)
    errorChanged             : typing.ClassVar[Signal] = ... # errorChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QScreenCapture::Error,QString)
    screenChanged            : typing.ClassVar[Signal] = ... # screenChanged(QScreen*)

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        InternalError             = ...  # 0x1
        CapturingNotSupported     = ...  # 0x2
        CaptureFailed             = ...  # 0x4
        NotFound                  = ...  # 0x5


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., screen: PySide6.QtGui.QScreen | None = ..., error: PySide6.QtMultimedia.QScreenCapture.Error | None = ..., error_string: str | None = ...) -> None: ...

    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def error(self, /) -> PySide6.QtMultimedia.QScreenCapture.Error: ...
    def error_string(self, /) -> str: ...
    def is_active(self, /) -> bool: ...
    def screen(self, /) -> PySide6.QtGui.QScreen: ...
    def set_active(self, active: bool, /) -> None: ...
    def set_screen(self, screen: PySide6.QtGui.QScreen, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...


class QSoundEffect(PySide6.QtCore.QObject):

    audioDeviceChanged       : typing.ClassVar[Signal] = ... # audioDeviceChanged()
    loadedChanged            : typing.ClassVar[Signal] = ... # loadedChanged()
    loopCountChanged         : typing.ClassVar[Signal] = ... # loopCountChanged()
    loopsRemainingChanged    : typing.ClassVar[Signal] = ... # loopsRemainingChanged()
    mutedChanged             : typing.ClassVar[Signal] = ... # mutedChanged()
    playingChanged           : typing.ClassVar[Signal] = ... # playingChanged()
    sourceChanged            : typing.ClassVar[Signal] = ... # sourceChanged()
    statusChanged            : typing.ClassVar[Signal] = ... # statusChanged()
    volumeChanged            : typing.ClassVar[Signal] = ... # volumeChanged()

    class Loop(enum.Enum):

        Infinite                  = ...  # -2

    class Status(enum.Enum):

        Null                      = ...  # 0x0
        Loading                   = ...  # 0x1
        Ready                     = ...  # 0x2
        Error                     = ...  # 0x3


    @typing.overload
    def __init__(self, audio_device: PySide6.QtMultimedia.QAudioDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., loops: int | None = ..., loops_remaining: int | None = ..., volume: float | None = ..., muted: bool | None = ..., playing: bool | None = ..., status: PySide6.QtMultimedia.QSoundEffect.Status | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., loops: int | None = ..., loops_remaining: int | None = ..., volume: float | None = ..., muted: bool | None = ..., playing: bool | None = ..., status: PySide6.QtMultimedia.QSoundEffect.Status | None = ..., audio_device: PySide6.QtMultimedia.QAudioDevice | None = ...) -> None: ...

    def audio_device(self, /) -> PySide6.QtMultimedia.QAudioDevice: ...
    def is_loaded(self, /) -> bool: ...
    def is_muted(self, /) -> bool: ...
    def is_playing(self, /) -> bool: ...
    def loop_count(self, /) -> int: ...
    def loops_remaining(self, /) -> int: ...
    def play(self, /) -> None: ...
    def set_audio_device(self, device: PySide6.QtMultimedia.QAudioDevice, /) -> None: ...
    def set_loop_count(self, loopCount: int, /) -> None: ...
    def set_muted(self, muted: bool, /) -> None: ...
    def set_source(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_volume(self, volume: float, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def status(self, /) -> PySide6.QtMultimedia.QSoundEffect.Status: ...
    def stop(self, /) -> None: ...
    @staticmethod
    def supported_mime_types() -> typing.List[str]: ...
    def volume(self, /) -> float: ...


class QVideoFrame(Shiboken.Object):

    class HandleType(enum.Enum):

        NoHandle                  = ...  # 0x0
        RhiTextureHandle          = ...  # 0x1

    class MapMode(enum.Enum):

        NotMapped                 = ...  # 0x0
        ReadOnly                  = ...  # 0x1
        WriteOnly                 = ...  # 0x2
        ReadWrite                 = ...  # 0x3

    class PaintOptions(Shiboken.Object):

        class PaintFlag(enum.Flag):

            DontDrawSubtitles         = ...  # 0x1


        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, PaintOptions: PySide6.QtMultimedia.QVideoFrame.PaintOptions, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...

    class RotationAngle(enum.Enum):

        Rotation0                 = ...  # 0x0
        Rotation90                = ...  # 0x5a
        Rotation180               = ...  # 0xb4
        Rotation270               = ...  # 0x10e


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, image: PySide6.QtGui.QImage, /) -> None: ...
    @typing.overload
    def __init__(self, buffer: PySide6.QtMultimedia.QAbstractVideoBuffer, format: PySide6.QtMultimedia.QVideoFrameFormat, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtMultimedia.QVideoFrame, /) -> None: ...
    @typing.overload
    def __init__(self, format: PySide6.QtMultimedia.QVideoFrameFormat, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtMultimedia.QVideoFrame | PySide6.QtMultimedia.QVideoFrameFormat, /) -> bool: ...
    def __ne__(self, other: PySide6.QtMultimedia.QVideoFrame | PySide6.QtMultimedia.QVideoFrameFormat, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def bits(self, plane: int, /) -> typing.Union[bytes, bytearray, memoryview]: ...
    def bytes_per_line(self, plane: int, /) -> int: ...
    def end_time(self, /) -> int: ...
    def handle_type(self, /) -> PySide6.QtMultimedia.QVideoFrame.HandleType: ...
    def height(self, /) -> int: ...
    def is_mapped(self, /) -> bool: ...
    def is_readable(self, /) -> bool: ...
    def is_valid(self, /) -> bool: ...
    def is_writable(self, /) -> bool: ...
    def map(self, mode: PySide6.QtMultimedia.QVideoFrame.MapMode, /) -> bool: ...
    def map_mode(self, /) -> PySide6.QtMultimedia.QVideoFrame.MapMode: ...
    def mapped_bytes(self, plane: int, /) -> int: ...
    def mirrored(self, /) -> bool: ...
    def paint(self, painter: PySide6.QtGui.QPainter, rect: PySide6.QtCore.QRectF | PySide6.QtCore.QRect, options: PySide6.QtMultimedia.QVideoFrame.PaintOptions, /) -> None: ...
    def pixel_format(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat: ...
    def plane_count(self, /) -> int: ...
    def rotation(self, /) -> PySide6.QtMultimedia.QtVideo.Rotation: ...
    def rotation_angle(self, /) -> PySide6.QtMultimedia.QVideoFrame.RotationAngle: ...
    def set_end_time(self, time: int, /) -> None: ...
    def set_mirrored(self, arg__1: bool, /) -> None: ...
    def set_rotation(self, angle: PySide6.QtMultimedia.QtVideo.Rotation, /) -> None: ...
    def set_rotation_angle(self, angle: PySide6.QtMultimedia.QVideoFrame.RotationAngle, /) -> None: ...
    def set_start_time(self, time: int, /) -> None: ...
    def set_stream_frame_rate(self, rate: float, /) -> None: ...
    def set_subtitle_text(self, text: str, /) -> None: ...
    def size(self, /) -> PySide6.QtCore.QSize: ...
    def start_time(self, /) -> int: ...
    def stream_frame_rate(self, /) -> float: ...
    def subtitle_text(self, /) -> str: ...
    def surface_format(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat: ...
    def swap(self, other: PySide6.QtMultimedia.QVideoFrame | PySide6.QtMultimedia.QVideoFrameFormat, /) -> None: ...
    def to_image(self, /) -> PySide6.QtGui.QImage: ...
    def unmap(self, /) -> None: ...
    def video_buffer(self, /) -> PySide6.QtMultimedia.QAbstractVideoBuffer: ...
    def width(self, /) -> int: ...


class QVideoFrameFormat(Shiboken.Object):

    class ColorRange(enum.Enum):

        ColorRange_Unknown        = ...  # 0x0
        ColorRange_Video          = ...  # 0x1
        ColorRange_Full           = ...  # 0x2

    class ColorSpace(enum.Enum):

        ColorSpace_Undefined      = ...  # 0x0
        ColorSpace_BT601          = ...  # 0x1
        ColorSpace_BT709          = ...  # 0x2
        ColorSpace_AdobeRgb       = ...  # 0x5
        ColorSpace_BT2020         = ...  # 0x6

    class ColorTransfer(enum.Enum):

        ColorTransfer_Unknown     = ...  # 0x0
        ColorTransfer_BT709       = ...  # 0x1
        ColorTransfer_BT601       = ...  # 0x2
        ColorTransfer_Linear      = ...  # 0x3
        ColorTransfer_Gamma22     = ...  # 0x4
        ColorTransfer_Gamma28     = ...  # 0x5
        ColorTransfer_ST2084      = ...  # 0x6
        ColorTransfer_STD_B67     = ...  # 0x7

    class Direction(enum.Enum):

        TopToBottom               = ...  # 0x0
        BottomToTop               = ...  # 0x1

    class PixelFormat(enum.Enum):

        Format_Invalid            = ...  # 0x0
        Format_ARGB8888           = ...  # 0x1
        Format_ARGB8888_Premultiplied = ...  # 0x2
        Format_XRGB8888           = ...  # 0x3
        Format_BGRA8888           = ...  # 0x4
        Format_BGRA8888_Premultiplied = ...  # 0x5
        Format_BGRX8888           = ...  # 0x6
        Format_ABGR8888           = ...  # 0x7
        Format_XBGR8888           = ...  # 0x8
        Format_RGBA8888           = ...  # 0x9
        Format_RGBX8888           = ...  # 0xa
        Format_AYUV               = ...  # 0xb
        Format_AYUV_Premultiplied = ...  # 0xc
        Format_YUV420P            = ...  # 0xd
        Format_YUV422P            = ...  # 0xe
        Format_YV12               = ...  # 0xf
        Format_UYVY               = ...  # 0x10
        Format_YUYV               = ...  # 0x11
        Format_NV12               = ...  # 0x12
        Format_NV21               = ...  # 0x13
        Format_IMC1               = ...  # 0x14
        Format_IMC2               = ...  # 0x15
        Format_IMC3               = ...  # 0x16
        Format_IMC4               = ...  # 0x17
        Format_Y8                 = ...  # 0x18
        Format_Y16                = ...  # 0x19
        Format_P010               = ...  # 0x1a
        Format_P016               = ...  # 0x1b
        Format_SamplerExternalOES = ...  # 0x1c
        Format_Jpeg               = ...  # 0x1d
        Format_SamplerRect        = ...  # 0x1e
        Format_YUV420P10          = ...  # 0x1f

    class YCbCrColorSpace(enum.Enum):

        YCbCr_Undefined           = ...  # 0x0
        YCbCr_BT601               = ...  # 0x1
        YCbCr_BT709               = ...  # 0x2
        YCbCr_xvYCC601            = ...  # 0x3
        YCbCr_xvYCC709            = ...  # 0x4
        YCbCr_JPEG                = ...  # 0x5
        YCbCr_BT2020              = ...  # 0x6


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, size: PySide6.QtCore.QSize, pixelFormat: PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat, /) -> None: ...
    @typing.overload
    def __init__(self, format: PySide6.QtMultimedia.QVideoFrameFormat, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, format: PySide6.QtMultimedia.QVideoFrameFormat, /) -> bool: ...
    def __ne__(self, format: PySide6.QtMultimedia.QVideoFrameFormat, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def color_range(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.ColorRange: ...
    def color_space(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.ColorSpace: ...
    def color_transfer(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.ColorTransfer: ...
    def fragment_shader_file_name(self, /) -> str: ...
    def frame_height(self, /) -> int: ...
    def frame_rate(self, /) -> float: ...
    def frame_size(self, /) -> PySide6.QtCore.QSize: ...
    def frame_width(self, /) -> int: ...
    @staticmethod
    def image_format_from_pixel_format(format: PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat, /) -> PySide6.QtGui.QImage.Format: ...
    def is_mirrored(self, /) -> bool: ...
    def is_valid(self, /) -> bool: ...
    def max_luminance(self, /) -> float: ...
    def pixel_format(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat: ...
    @staticmethod
    def pixel_format_from_image_format(format: PySide6.QtGui.QImage.Format, /) -> PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat: ...
    @staticmethod
    def pixel_format_to_string(pixelFormat: PySide6.QtMultimedia.QVideoFrameFormat.PixelFormat, /) -> str: ...
    def plane_count(self, /) -> int: ...
    def rotation(self, /) -> PySide6.QtMultimedia.QtVideo.Rotation: ...
    def scan_line_direction(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.Direction: ...
    def setYCbCrColorSpace(self, colorSpace: PySide6.QtMultimedia.QVideoFrameFormat.YCbCrColorSpace, /) -> None: ...
    def set_color_range(self, range: PySide6.QtMultimedia.QVideoFrameFormat.ColorRange, /) -> None: ...
    def set_color_space(self, colorSpace: PySide6.QtMultimedia.QVideoFrameFormat.ColorSpace, /) -> None: ...
    def set_color_transfer(self, colorTransfer: PySide6.QtMultimedia.QVideoFrameFormat.ColorTransfer, /) -> None: ...
    def set_frame_rate(self, rate: float, /) -> None: ...
    @typing.overload
    def set_frame_size(self, size: PySide6.QtCore.QSize, /) -> None: ...
    @typing.overload
    def set_frame_size(self, width: int, height: int, /) -> None: ...
    def set_max_luminance(self, lum: float, /) -> None: ...
    def set_mirrored(self, mirrored: bool, /) -> None: ...
    def set_rotation(self, rotation: PySide6.QtMultimedia.QtVideo.Rotation, /) -> None: ...
    def set_scan_line_direction(self, direction: PySide6.QtMultimedia.QVideoFrameFormat.Direction, /) -> None: ...
    def set_stream_frame_rate(self, rate: float, /) -> None: ...
    def set_viewport(self, viewport: PySide6.QtCore.QRect, /) -> None: ...
    def stream_frame_rate(self, /) -> float: ...
    def swap(self, other: PySide6.QtMultimedia.QVideoFrameFormat, /) -> None: ...
    def update_uniform_data(self, dst: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, frame: PySide6.QtMultimedia.QVideoFrame | PySide6.QtMultimedia.QVideoFrameFormat, transform: PySide6.QtGui.QMatrix4x4 | PySide6.QtGui.QTransform, opacity: float, /) -> None: ...
    def vertex_shader_file_name(self, /) -> str: ...
    def viewport(self, /) -> PySide6.QtCore.QRect: ...
    def y_cb_cr_color_space(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat.YCbCrColorSpace: ...


class QVideoFrameInput(PySide6.QtCore.QObject):

    readyToSendVideoFrame    : typing.ClassVar[Signal] = ... # readyToSendVideoFrame()

    @typing.overload
    def __init__(self, format: PySide6.QtMultimedia.QVideoFrameFormat, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def format(self, /) -> PySide6.QtMultimedia.QVideoFrameFormat: ...
    def send_video_frame(self, frame: PySide6.QtMultimedia.QVideoFrame | PySide6.QtMultimedia.QVideoFrameFormat, /) -> bool: ...


class QVideoSink(PySide6.QtCore.QObject):

    subtitleTextChanged      : typing.ClassVar[Signal] = ... # subtitleTextChanged(QString)
    videoFrameChanged        : typing.ClassVar[Signal] = ... # videoFrameChanged(QVideoFrame)
    videoSizeChanged         : typing.ClassVar[Signal] = ... # videoSizeChanged()

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, subtitle_text: str | None = ..., video_size: PySide6.QtCore.QSize | None = ...) -> None: ...

    def rhi(self, /) -> PySide6.QtGui.QRhi: ...
    def set_rhi(self, rhi: PySide6.QtGui.QRhi, /) -> None: ...
    def set_subtitle_text(self, subtitle: str, /) -> None: ...
    def set_video_frame(self, frame: PySide6.QtMultimedia.QVideoFrame | PySide6.QtMultimedia.QVideoFrameFormat, /) -> None: ...
    def subtitle_text(self, /) -> str: ...
    def video_frame(self, /) -> PySide6.QtMultimedia.QVideoFrame: ...
    def video_size(self, /) -> PySide6.QtCore.QSize: ...


class QWaveDecoder(PySide6.QtCore.QIODevice):

    formatKnown              : typing.ClassVar[Signal] = ... # formatKnown()
    parsingError             : typing.ClassVar[Signal] = ... # parsingError()

    @typing.overload
    def __init__(self, device: PySide6.QtCore.QIODevice, format: PySide6.QtMultimedia.QAudioFormat, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, device: PySide6.QtCore.QIODevice, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def audio_format(self, /) -> PySide6.QtMultimedia.QAudioFormat: ...
    def bytes_available(self, /) -> int: ...
    def close(self, /) -> None: ...
    def duration(self, /) -> int: ...
    def get_device(self, /) -> PySide6.QtCore.QIODevice: ...
    @staticmethod
    def header_length() -> int: ...
    def is_sequential(self, /) -> bool: ...
    def open(self, mode: PySide6.QtCore.QIODeviceBase.OpenModeFlag, /) -> bool: ...
    def pos(self, /) -> int: ...
    def read_data(self, maxlen: int, /) -> object: ...
    def seek(self, pos: int, /) -> bool: ...
    def size(self, /) -> int: ...
    def write_data(self, data: bytes | bytearray | memoryview, len: int, /) -> int: ...


class QWindowCapture(PySide6.QtCore.QObject):

    activeChanged            : typing.ClassVar[Signal] = ... # activeChanged(bool)
    errorChanged             : typing.ClassVar[Signal] = ... # errorChanged()
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QWindowCapture::Error,QString)
    windowChanged            : typing.ClassVar[Signal] = ... # windowChanged(QCapturableWindow)

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        InternalError             = ...  # 0x1
        CapturingNotSupported     = ...  # 0x2
        CaptureFailed             = ...  # 0x4
        NotFound                  = ...  # 0x5


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., window: PySide6.QtMultimedia.QCapturableWindow | None = ..., error: PySide6.QtMultimedia.QWindowCapture.Error | None = ..., error_string: str | None = ...) -> None: ...

    @staticmethod
    def capturable_windows() -> typing.List[PySide6.QtMultimedia.QCapturableWindow]: ...
    def capture_session(self, /) -> PySide6.QtMultimedia.QMediaCaptureSession: ...
    def error(self, /) -> PySide6.QtMultimedia.QWindowCapture.Error: ...
    def error_string(self, /) -> str: ...
    def is_active(self, /) -> bool: ...
    def set_active(self, active: bool, /) -> None: ...
    def set_window(self, window: PySide6.QtMultimedia.QCapturableWindow, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...
    def window(self, /) -> PySide6.QtMultimedia.QCapturableWindow: ...


class QtVideo(Shiboken.Object):

    class Rotation(enum.Enum):

        None_                     = ...  # 0x0
        Clockwise90               = ...  # 0x5a
        Clockwise180              = ...  # 0xb4
        Clockwise270              = ...  # 0x10e


# eof
