# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtPrintSupport, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtPrintSupport`

import PySide6.QtPrintSupport
import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtWidgets

import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QAbstractPrintDialog(PySide6.QtWidgets.QDialog):

    class PrintDialogOption(enum.Flag):

        PrintToFile               = ...  # 0x1
        PrintSelection            = ...  # 0x2
        PrintPageRange            = ...  # 0x4
        PrintShowPageSize         = ...  # 0x8
        PrintCollateCopies        = ...  # 0x10
        PrintCurrentPage          = ...  # 0x40

    class PrintRange(enum.Enum):

        AllPages                  = ...  # 0x0
        Selection                 = ...  # 0x1
        PageRange                 = ...  # 0x2
        CurrentPage               = ...  # 0x3


    def __init__(self, printer: PySide6.QtPrintSupport.QPrinter, /, parent: PySide6.QtWidgets.QWidget | None = ...) -> None: ...

    def from_page(self, /) -> int: ...
    def max_page(self, /) -> int: ...
    def min_page(self, /) -> int: ...
    def print_range(self, /) -> PySide6.QtPrintSupport.QAbstractPrintDialog.PrintRange: ...
    def printer(self, /) -> PySide6.QtPrintSupport.QPrinter: ...
    def set_from_to(self, fromPage: int, toPage: int, /) -> None: ...
    def set_min_max(self, min: int, max: int, /) -> None: ...
    def set_option_tabs(self, tabs: collections.abc.Sequence[PySide6.QtWidgets.QWidget], /) -> None: ...
    def set_print_range(self, range: PySide6.QtPrintSupport.QAbstractPrintDialog.PrintRange, /) -> None: ...
    def to_page(self, /) -> int: ...


class QIntList: ...


class QPageSetupDialog(PySide6.QtWidgets.QDialog):

    @typing.overload
    def __init__(self, printer: PySide6.QtPrintSupport.QPrinter, /, parent: PySide6.QtWidgets.QWidget | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ...) -> None: ...

    def done(self, result: int, /) -> None: ...
    def exec(self, /) -> int: ...
    def exec_(self, /) -> int: ...
    @typing.overload
    def open(self, /) -> None: ...
    @typing.overload
    def open(self, receiver: PySide6.QtCore.QObject, member: bytes | bytearray | memoryview, /) -> None: ...
    def printer(self, /) -> PySide6.QtPrintSupport.QPrinter: ...
    def set_visible(self, visible: bool, /) -> None: ...


class QPrintDialog(PySide6.QtPrintSupport.QAbstractPrintDialog):

    accepted                 : typing.ClassVar[Signal] = ... # accepted(QPrinter*)

    @typing.overload
    def __init__(self, printer: PySide6.QtPrintSupport.QPrinter, /, parent: PySide6.QtWidgets.QWidget | None = ..., *, options: PySide6.QtPrintSupport.QAbstractPrintDialog.PrintDialogOption | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ..., *, options: PySide6.QtPrintSupport.QAbstractPrintDialog.PrintDialogOption | None = ...) -> None: ...

    def done(self, result: int, /) -> None: ...
    def exec(self, /) -> int: ...
    def exec_(self, /) -> int: ...
    def open(self, receiver: PySide6.QtCore.QObject, member: bytes | bytearray | memoryview, /) -> None: ...
    def options(self, /) -> PySide6.QtPrintSupport.QAbstractPrintDialog.PrintDialogOption: ...
    def set_option(self, option: PySide6.QtPrintSupport.QAbstractPrintDialog.PrintDialogOption, /, on: bool = ...) -> None: ...
    def set_options(self, options: PySide6.QtPrintSupport.QAbstractPrintDialog.PrintDialogOption, /) -> None: ...
    def set_visible(self, visible: bool, /) -> None: ...
    def test_option(self, option: PySide6.QtPrintSupport.QAbstractPrintDialog.PrintDialogOption, /) -> bool: ...


class QPrintEngine(Shiboken.Object):

    class PrintEnginePropertyKey(enum.Enum):

        PPK_CollateCopies         = ...  # 0x0
        PPK_ColorMode             = ...  # 0x1
        PPK_Creator               = ...  # 0x2
        PPK_DocumentName          = ...  # 0x3
        PPK_FullPage              = ...  # 0x4
        PPK_NumberOfCopies        = ...  # 0x5
        PPK_Orientation           = ...  # 0x6
        PPK_OutputFileName        = ...  # 0x7
        PPK_PageOrder             = ...  # 0x8
        PPK_PageRect              = ...  # 0x9
        PPK_PageSize              = ...  # 0xa
        PPK_PaperSize             = ...  # 0xa
        PPK_PaperRect             = ...  # 0xb
        PPK_PaperSource           = ...  # 0xc
        PPK_PrinterName           = ...  # 0xd
        PPK_PrinterProgram        = ...  # 0xe
        PPK_Resolution            = ...  # 0xf
        PPK_SelectionOption       = ...  # 0x10
        PPK_SupportedResolutions  = ...  # 0x11
        PPK_WindowsPageSize       = ...  # 0x12
        PPK_FontEmbedding         = ...  # 0x13
        PPK_Duplex                = ...  # 0x14
        PPK_PaperSources          = ...  # 0x15
        PPK_CustomPaperSize       = ...  # 0x16
        PPK_PageMargins           = ...  # 0x17
        PPK_CopyCount             = ...  # 0x18
        PPK_SupportsMultipleCopies = ...  # 0x19
        PPK_PaperName             = ...  # 0x1a
        PPK_QPageSize             = ...  # 0x1b
        PPK_QPageMargins          = ...  # 0x1c
        PPK_QPageLayout           = ...  # 0x1d
        PPK_CustomBase            = ...  # 0xff00


    def __init__(self, /) -> None: ...

    def abort(self, /) -> bool: ...
    def metric(self, arg__1: PySide6.QtGui.QPaintDevice.PaintDeviceMetric, /) -> int: ...
    def new_page(self, /) -> bool: ...
    def printer_state(self, /) -> PySide6.QtPrintSupport.QPrinter.PrinterState: ...
    def property(self, key: PySide6.QtPrintSupport.QPrintEngine.PrintEnginePropertyKey, /) -> typing.Any: ...
    def set_property(self, key: PySide6.QtPrintSupport.QPrintEngine.PrintEnginePropertyKey, value: typing.Any, /) -> None: ...


class QPrintPreviewDialog(PySide6.QtWidgets.QDialog):

    paintRequested           : typing.ClassVar[Signal] = ... # paintRequested(QPrinter*)

    @typing.overload
    def __init__(self, printer: PySide6.QtPrintSupport.QPrinter, /, parent: PySide6.QtWidgets.QWidget | None = ..., flags: PySide6.QtCore.Qt.WindowType = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ..., flags: PySide6.QtCore.Qt.WindowType = ...) -> None: ...

    def done(self, result: int, /) -> None: ...
    @typing.overload
    def open(self, /) -> None: ...
    @typing.overload
    def open(self, receiver: PySide6.QtCore.QObject, member: bytes | bytearray | memoryview, /) -> None: ...
    def printer(self, /) -> PySide6.QtPrintSupport.QPrinter: ...
    def set_visible(self, visible: bool, /) -> None: ...


class QPrintPreviewWidget(PySide6.QtWidgets.QWidget):

    paintRequested           : typing.ClassVar[Signal] = ... # paintRequested(QPrinter*)
    previewChanged           : typing.ClassVar[Signal] = ... # previewChanged()

    class ViewMode(enum.Enum):

        SinglePageView            = ...  # 0x0
        FacingPagesView           = ...  # 0x1
        AllPagesView              = ...  # 0x2

    class ZoomMode(enum.Enum):

        CustomZoom                = ...  # 0x0
        FitToWidth                = ...  # 0x1
        FitInView                 = ...  # 0x2


    @typing.overload
    def __init__(self, printer: PySide6.QtPrintSupport.QPrinter, /, parent: PySide6.QtWidgets.QWidget | None = ..., flags: PySide6.QtCore.Qt.WindowType = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ..., flags: PySide6.QtCore.Qt.WindowType = ...) -> None: ...

    def current_page(self, /) -> int: ...
    def fit_in_view(self, /) -> None: ...
    def fit_to_width(self, /) -> None: ...
    def orientation(self, /) -> PySide6.QtGui.QPageLayout.Orientation: ...
    def page_count(self, /) -> int: ...
    def print_(self, /) -> None: ...
    def set_all_pages_view_mode(self, /) -> None: ...
    def set_current_page(self, pageNumber: int, /) -> None: ...
    def set_facing_pages_view_mode(self, /) -> None: ...
    def set_landscape_orientation(self, /) -> None: ...
    def set_orientation(self, orientation: PySide6.QtGui.QPageLayout.Orientation, /) -> None: ...
    def set_portrait_orientation(self, /) -> None: ...
    def set_single_page_view_mode(self, /) -> None: ...
    def set_view_mode(self, viewMode: PySide6.QtPrintSupport.QPrintPreviewWidget.ViewMode, /) -> None: ...
    def set_visible(self, visible: bool, /) -> None: ...
    def set_zoom_factor(self, zoomFactor: float, /) -> None: ...
    def set_zoom_mode(self, zoomMode: PySide6.QtPrintSupport.QPrintPreviewWidget.ZoomMode, /) -> None: ...
    def update_preview(self, /) -> None: ...
    def view_mode(self, /) -> PySide6.QtPrintSupport.QPrintPreviewWidget.ViewMode: ...
    def zoom_factor(self, /) -> float: ...
    def zoom_in(self, /, zoom: float = ...) -> None: ...
    def zoom_mode(self, /) -> PySide6.QtPrintSupport.QPrintPreviewWidget.ZoomMode: ...
    def zoom_out(self, /, zoom: float = ...) -> None: ...


class QPrinter(PySide6.QtGui.QPagedPaintDevice):

    class ColorMode(enum.Enum):

        GrayScale                 = ...  # 0x0
        Color                     = ...  # 0x1

    class DuplexMode(enum.Enum):

        DuplexNone                = ...  # 0x0
        DuplexAuto                = ...  # 0x1
        DuplexLongSide            = ...  # 0x2
        DuplexShortSide           = ...  # 0x3

    class OutputFormat(enum.Enum):

        NativeFormat              = ...  # 0x0
        PdfFormat                 = ...  # 0x1

    class PageOrder(enum.Enum):

        FirstPageFirst            = ...  # 0x0
        LastPageFirst             = ...  # 0x1

    class PaperSource(enum.Enum):

        OnlyOne                   = ...  # 0x0
        Upper                     = ...  # 0x0
        Lower                     = ...  # 0x1
        Middle                    = ...  # 0x2
        Manual                    = ...  # 0x3
        Envelope                  = ...  # 0x4
        EnvelopeManual            = ...  # 0x5
        Auto                      = ...  # 0x6
        Tractor                   = ...  # 0x7
        SmallFormat               = ...  # 0x8
        LargeFormat               = ...  # 0x9
        LargeCapacity             = ...  # 0xa
        Cassette                  = ...  # 0xb
        FormSource                = ...  # 0xc
        MaxPageSource             = ...  # 0xd
        CustomSource              = ...  # 0xe
        LastPaperSource           = ...  # 0xe

    class PrintRange(enum.Enum):

        AllPages                  = ...  # 0x0
        Selection                 = ...  # 0x1
        PageRange                 = ...  # 0x2
        CurrentPage               = ...  # 0x3

    class PrinterMode(enum.Enum):

        ScreenResolution          = ...  # 0x0
        PrinterResolution         = ...  # 0x1
        HighResolution            = ...  # 0x2

    class PrinterState(enum.Enum):

        Idle                      = ...  # 0x0
        Active                    = ...  # 0x1
        Aborted                   = ...  # 0x2
        Error                     = ...  # 0x3

    class Unit(enum.Enum):

        Millimeter                = ...  # 0x0
        Point                     = ...  # 0x1
        Inch                      = ...  # 0x2
        Pica                      = ...  # 0x3
        Didot                     = ...  # 0x4
        Cicero                    = ...  # 0x5
        DevicePixel               = ...  # 0x6


    @typing.overload
    def __init__(self, /, mode: PySide6.QtPrintSupport.QPrinter.PrinterMode = ...) -> None: ...
    @typing.overload
    def __init__(self, printer: PySide6.QtPrintSupport.QPrinterInfo, /, mode: PySide6.QtPrintSupport.QPrinter.PrinterMode = ...) -> None: ...

    def abort(self, /) -> bool: ...
    def collate_copies(self, /) -> bool: ...
    def color_mode(self, /) -> PySide6.QtPrintSupport.QPrinter.ColorMode: ...
    def copy_count(self, /) -> int: ...
    def creator(self, /) -> str: ...
    def dev_type(self, /) -> int: ...
    def doc_name(self, /) -> str: ...
    def duplex(self, /) -> PySide6.QtPrintSupport.QPrinter.DuplexMode: ...
    def font_embedding_enabled(self, /) -> bool: ...
    def from_page(self, /) -> int: ...
    def full_page(self, /) -> bool: ...
    def is_valid(self, /) -> bool: ...
    def metric(self, arg__1: PySide6.QtGui.QPaintDevice.PaintDeviceMetric, /) -> int: ...
    def new_page(self, /) -> bool: ...
    def output_file_name(self, /) -> str: ...
    def output_format(self, /) -> PySide6.QtPrintSupport.QPrinter.OutputFormat: ...
    def page_order(self, /) -> PySide6.QtPrintSupport.QPrinter.PageOrder: ...
    def page_rect(self, arg__1: PySide6.QtPrintSupport.QPrinter.Unit, /) -> PySide6.QtCore.QRectF: ...
    def paint_engine(self, /) -> PySide6.QtGui.QPaintEngine: ...
    def paper_rect(self, arg__1: PySide6.QtPrintSupport.QPrinter.Unit, /) -> PySide6.QtCore.QRectF: ...
    def paper_source(self, /) -> PySide6.QtPrintSupport.QPrinter.PaperSource: ...
    def pdf_version(self, /) -> PySide6.QtGui.QPagedPaintDevice.PdfVersion: ...
    def print_engine(self, /) -> PySide6.QtPrintSupport.QPrintEngine: ...
    def print_program(self, /) -> str: ...
    def print_range(self, /) -> PySide6.QtPrintSupport.QPrinter.PrintRange: ...
    def printer_name(self, /) -> str: ...
    def printer_selection_option(self, /) -> str: ...
    def printer_state(self, /) -> PySide6.QtPrintSupport.QPrinter.PrinterState: ...
    def resolution(self, /) -> int: ...
    def set_collate_copies(self, collate: bool, /) -> None: ...
    def set_color_mode(self, arg__1: PySide6.QtPrintSupport.QPrinter.ColorMode, /) -> None: ...
    def set_copy_count(self, arg__1: int, /) -> None: ...
    def set_creator(self, arg__1: str, /) -> None: ...
    def set_doc_name(self, arg__1: str, /) -> None: ...
    def set_duplex(self, duplex: PySide6.QtPrintSupport.QPrinter.DuplexMode, /) -> None: ...
    def set_engines(self, printEngine: PySide6.QtPrintSupport.QPrintEngine, paintEngine: PySide6.QtGui.QPaintEngine, /) -> None: ...
    def set_font_embedding_enabled(self, enable: bool, /) -> None: ...
    def set_from_to(self, fromPage: int, toPage: int, /) -> None: ...
    def set_full_page(self, arg__1: bool, /) -> None: ...
    def set_output_file_name(self, arg__1: str, /) -> None: ...
    def set_output_format(self, format: PySide6.QtPrintSupport.QPrinter.OutputFormat, /) -> None: ...
    def set_page_order(self, arg__1: PySide6.QtPrintSupport.QPrinter.PageOrder, /) -> None: ...
    def set_page_size(self, size: PySide6.QtGui.QPageSize | PySide6.QtGui.QPageSize.PageSizeId | PySide6.QtCore.QSize, /) -> bool: ...
    def set_paper_source(self, arg__1: PySide6.QtPrintSupport.QPrinter.PaperSource, /) -> None: ...
    def set_pdf_version(self, version: PySide6.QtGui.QPagedPaintDevice.PdfVersion, /) -> None: ...
    def set_print_program(self, arg__1: str, /) -> None: ...
    def set_print_range(self, range: PySide6.QtPrintSupport.QPrinter.PrintRange, /) -> None: ...
    def set_printer_name(self, arg__1: str, /) -> None: ...
    def set_printer_selection_option(self, arg__1: str, /) -> None: ...
    def set_resolution(self, arg__1: int, /) -> None: ...
    def supported_resolutions(self, /) -> typing.List[int]: ...
    def supports_multiple_copies(self, /) -> bool: ...
    def to_page(self, /) -> int: ...


class QPrinterInfo(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, printer: PySide6.QtPrintSupport.QPrinter, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtPrintSupport.QPrinterInfo, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    @staticmethod
    def available_printer_names() -> typing.List[str]: ...
    @staticmethod
    def available_printers() -> typing.List[PySide6.QtPrintSupport.QPrinterInfo]: ...
    def default_color_mode(self, /) -> PySide6.QtPrintSupport.QPrinter.ColorMode: ...
    def default_duplex_mode(self, /) -> PySide6.QtPrintSupport.QPrinter.DuplexMode: ...
    def default_page_size(self, /) -> PySide6.QtGui.QPageSize: ...
    @staticmethod
    def default_printer() -> PySide6.QtPrintSupport.QPrinterInfo: ...
    @staticmethod
    def default_printer_name() -> str: ...
    def description(self, /) -> str: ...
    def is_default(self, /) -> bool: ...
    def is_null(self, /) -> bool: ...
    def is_remote(self, /) -> bool: ...
    def location(self, /) -> str: ...
    def make_and_model(self, /) -> str: ...
    def maximum_physical_page_size(self, /) -> PySide6.QtGui.QPageSize: ...
    def minimum_physical_page_size(self, /) -> PySide6.QtGui.QPageSize: ...
    @staticmethod
    def printer_info(printerName: str, /) -> PySide6.QtPrintSupport.QPrinterInfo: ...
    def printer_name(self, /) -> str: ...
    def state(self, /) -> PySide6.QtPrintSupport.QPrinter.PrinterState: ...
    def supported_color_modes(self, /) -> typing.List[PySide6.QtPrintSupport.QPrinter.ColorMode]: ...
    def supported_duplex_modes(self, /) -> typing.List[PySide6.QtPrintSupport.QPrinter.DuplexMode]: ...
    def supported_page_sizes(self, /) -> typing.List[PySide6.QtGui.QPageSize]: ...
    def supported_resolutions(self, /) -> typing.List[int]: ...
    def supports_custom_page_sizes(self, /) -> bool: ...


# eof
