# Generated by Django 4.2.14 on 2025-01-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('birth_date', models.DateField(null=True)),
                ('deceased_boolean', models.BooleanField(null=True)),
                ('deceased_date_time', models.DateTimeField(null=True)),
                ('address', models.ManyToManyField(blank=True, related_name='persons_address', to='base.address')),
                ('identifier', models.ManyToManyField(blank=True, related_name='persons_identifier', to='base.identifier')),
                ('managing_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_managing_organization', to='base.organizationreference')),
                ('marital_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_marital_status', to='base.codeableconcept')),
                ('name', models.ManyToManyField(blank=True, related_name='persons_name', to='base.humanname')),
                ('photo', models.ManyToManyField(blank=True, related_name='persons_photo', to='base.attachment')),
                ('telecom', models.ManyToManyField(blank=True, related_name='persons_telecom', to='base.contactpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('display', models.CharField(max_length=255, null=True)),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_reference_identifier', to='base.identifier')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_reference_person', to='persons.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
