# Generated by Django 4.2.14 on 2025-01-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('locations', '0002_locationorganizationreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationorganizationreference',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_organization_reference', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='locationorganizationreference',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_organization_reference', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='locationreference',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_reference', to='locations.location'),
        ),
    ]
