def decompress(decompress_bytes: bytes, uncompressed_size: int) -> bytes: ...

def decompress_buffer(
    decompress_bytes: bytes | bytearray | memoryview, uncompressed_size: int
) -> bytes: ...
