# Generated by Django 4.2.14 on 2025-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plandefinitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandefinitionaction',
            name='action',
            field=models.ManyToManyField(blank=True, to='plandefinitions.plandefinitionaction'),
        ),
    ]
