# Generated by Django 4.2.14 on 2025-03-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biologicallyderivedproducts', '0001_initial'),
        ('substances', '0002_substancecodeablereference'),
        ('medications', '0004_medicationreference_medicationcodeablereference'),
        ('base', '0021_alter_relatedartifact_display'),
        ('specimens', '0002_rename_specimencollections_specimencollection_and_more'),
        ('plandefinitions', '0002_alter_plandefinitionaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandefinitionactoroptiontypereferencereference',
            name='biologically_derived_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_definition_actor_option_type_reference_reference_biologically_derived_product', to='biologicallyderivedproducts.biologicallyderivedproduct'),
        ),
        migrations.AddField(
            model_name='plandefinitionactoroptiontypereferencereference',
            name='medication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_definition_actor_option_type_reference_reference_medication', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='plandefinitionactoroptiontypereferencereference',
            name='specimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_definition_actor_option_type_reference_reference_specimen', to='specimens.specimen'),
        ),
        migrations.AddField(
            model_name='plandefinitionactoroptiontypereferencereference',
            name='substance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_definition_actor_option_type_reference_reference_substance', to='substances.substance'),
        ),
        migrations.AlterField(
            model_name='plandefinition',
            name='approval_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plandefinition',
            name='last_review_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='plandefinitionaction',
            name='code',
        ),
        migrations.AlterField(
            model_name='plandefinitionaction',
            name='documentation',
            field=models.ManyToManyField(blank=True, related_name='plan_definition_action_documentation', to='base.relatedartifact'),
        ),
        migrations.AlterField(
            model_name='plandefinitionaction',
            name='reason',
            field=models.ManyToManyField(blank=True, related_name='plan_definition_action_reason', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='plandefinitionaction',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_definition_action_code', to='base.codeableconcept'),
        ),
    ]
