from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="clipsight",
    version="0.2.1",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    install_requires=[
        "fastapi>=0.68.1",
        "uvicorn>=0.15.0",
        "python-dotenv>=0.19.0",
        "loguru>=0.5.3",
        "playwright>=1.20.0",
        "minio>=7.1.0",
        "redis>=4.0.2",
        "elasticsearch>=7.17.0",
        "celery>=5.2.0",
        "aiohttp>=3.8.0",
        "pillow>=8.3.0",
        "numpy>=1.21.0",
        "scikit-learn>=0.24.0",
        "python-multipart>=0.0.5",
        "pydantic>=1.8.0",
        "httpx>=0.23.0",
        "tenacity>=8.0.0",
        "prometheus-client>=0.12.0",
        "opencv-python>=4.5.0",
        "tensorflow>=2.8.0",
        "transformers>=4.15.0",
        "torch>=1.10.0",
        "torchvision>=0.11.0",
        "faiss-cpu>=1.7.0",
        "sentence-transformers>=2.2.0",
        "beautifulsoup4>=4.9.0",
        "lxml>=4.9.0",
        "requests>=2.26.0",
        "aiofiles>=0.8.0",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "bcrypt>=3.2.0",
        "pytest>=6.2.5",
        "pytest-asyncio>=0.16.0",
        "pytest-cov>=2.12.0",
        "black>=21.7b0",
        "isort>=5.9.0",
        "flake8>=3.9.0",
        "mypy>=0.910",
        "pre-commit>=2.15.0",
        "setuptools>=45.0.0",
        "wheel>=0.37.0",
        "twine>=3.4.0",
        "build>=0.7.0",
        "setuptools_scm>=6.2.0",
    ],
    entry_points={
        "console_scripts": [
            "clipsight=web.app:main",
            "clipsight-worker=worker.main:main",
        ],
    },
    author="duckweeds7",
    author_email="duckweeds7@gmail.com",
    description="A distributed image crawling system based on Playwright",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://gitee.com/duckweeds7/clip-sight",
    project_urls={
        "Bug Tracker": "https://gitee.com/duckweeds7/clip-sight/issues",
        "Documentation": "https://gitee.com/duckweeds7/clip-sight/wikis",
        "Source Code": "https://gitee.com/duckweeds7/clip-sight",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Multimedia :: Graphics",
    ],
    python_requires=">=3.8",
    package_data={
        "": ["*.json", "*.yaml", "*.yml", "*.txt", "*.md"],
    },
    zip_safe=False,
) 