# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtSerialPort, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtSerialPort`

import PySide6.QtSerialPort
import PySide6.QtCore

import enum
import typing
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QIntList: ...


class QSerialPort(PySide6.QtCore.QIODevice):

    baudRateChanged          : typing.ClassVar[Signal] = ... # baudRateChanged(int,QSerialPort::Directions)
    breakEnabledChanged      : typing.ClassVar[Signal] = ... # breakEnabledChanged(bool)
    dataBitsChanged          : typing.ClassVar[Signal] = ... # dataBitsChanged(QSerialPort::DataBits)
    dataTerminalReadyChanged : typing.ClassVar[Signal] = ... # dataTerminalReadyChanged(bool)
    errorOccurred            : typing.ClassVar[Signal] = ... # errorOccurred(QSerialPort::SerialPortError)
    flowControlChanged       : typing.ClassVar[Signal] = ... # flowControlChanged(QSerialPort::FlowControl)
    parityChanged            : typing.ClassVar[Signal] = ... # parityChanged(QSerialPort::Parity)
    requestToSendChanged     : typing.ClassVar[Signal] = ... # requestToSendChanged(bool)
    stopBitsChanged          : typing.ClassVar[Signal] = ... # stopBitsChanged(QSerialPort::StopBits)

    class BaudRate(enum.IntEnum):

        Baud1200                  = ...  # 0x4b0
        Baud2400                  = ...  # 0x960
        Baud4800                  = ...  # 0x12c0
        Baud9600                  = ...  # 0x2580
        Baud19200                 = ...  # 0x4b00
        Baud38400                 = ...  # 0x9600
        Baud57600                 = ...  # 0xe100
        Baud115200                = ...  # 0x1c200

    class DataBits(enum.Enum):

        Data5                     = ...  # 0x5
        Data6                     = ...  # 0x6
        Data7                     = ...  # 0x7
        Data8                     = ...  # 0x8

    class Direction(enum.Flag):

        Input                     = ...  # 0x1
        Output                    = ...  # 0x2
        AllDirections             = ...  # 0x3

    class FlowControl(enum.Enum):

        NoFlowControl             = ...  # 0x0
        HardwareControl           = ...  # 0x1
        SoftwareControl           = ...  # 0x2

    class Parity(enum.Enum):

        NoParity                  = ...  # 0x0
        EvenParity                = ...  # 0x2
        OddParity                 = ...  # 0x3
        SpaceParity               = ...  # 0x4
        MarkParity                = ...  # 0x5

    class PinoutSignal(enum.Flag):

        NoSignal                  = ...  # 0x0
        DataTerminalReadySignal   = ...  # 0x4
        DataCarrierDetectSignal   = ...  # 0x8
        DataSetReadySignal        = ...  # 0x10
        RingIndicatorSignal       = ...  # 0x20
        RequestToSendSignal       = ...  # 0x40
        ClearToSendSignal         = ...  # 0x80
        SecondaryTransmittedDataSignal = ...  # 0x100
        SecondaryReceivedDataSignal = ...  # 0x200

    class SerialPortError(enum.Enum):

        NoError                   = ...  # 0x0
        DeviceNotFoundError       = ...  # 0x1
        PermissionError           = ...  # 0x2
        OpenError                 = ...  # 0x3
        WriteError                = ...  # 0x4
        ReadError                 = ...  # 0x5
        ResourceError             = ...  # 0x6
        UnsupportedOperationError = ...  # 0x7
        UnknownError              = ...  # 0x8
        TimeoutError              = ...  # 0x9
        NotOpenError              = ...  # 0xa

    class StopBits(enum.Enum):

        OneStop                   = ...  # 0x1
        TwoStop                   = ...  # 0x2
        OneAndHalfStop            = ...  # 0x3


    @typing.overload
    def __init__(self, info: PySide6.QtSerialPort.QSerialPortInfo, /, parent: PySide6.QtCore.QObject | None = ..., *, baud_rate: int | None = ..., data_bits: PySide6.QtSerialPort.QSerialPort.DataBits | None = ..., parity: PySide6.QtSerialPort.QSerialPort.Parity | None = ..., stop_bits: PySide6.QtSerialPort.QSerialPort.StopBits | None = ..., flow_control: PySide6.QtSerialPort.QSerialPort.FlowControl | None = ..., data_terminal_ready: bool | None = ..., request_to_send: bool | None = ..., error: PySide6.QtSerialPort.QSerialPort.SerialPortError | None = ..., break_enabled: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, name: str, /, parent: PySide6.QtCore.QObject | None = ..., *, baud_rate: int | None = ..., data_bits: PySide6.QtSerialPort.QSerialPort.DataBits | None = ..., parity: PySide6.QtSerialPort.QSerialPort.Parity | None = ..., stop_bits: PySide6.QtSerialPort.QSerialPort.StopBits | None = ..., flow_control: PySide6.QtSerialPort.QSerialPort.FlowControl | None = ..., data_terminal_ready: bool | None = ..., request_to_send: bool | None = ..., error: PySide6.QtSerialPort.QSerialPort.SerialPortError | None = ..., break_enabled: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, baud_rate: int | None = ..., data_bits: PySide6.QtSerialPort.QSerialPort.DataBits | None = ..., parity: PySide6.QtSerialPort.QSerialPort.Parity | None = ..., stop_bits: PySide6.QtSerialPort.QSerialPort.StopBits | None = ..., flow_control: PySide6.QtSerialPort.QSerialPort.FlowControl | None = ..., data_terminal_ready: bool | None = ..., request_to_send: bool | None = ..., error: PySide6.QtSerialPort.QSerialPort.SerialPortError | None = ..., break_enabled: bool | None = ...) -> None: ...

    def baud_rate(self, /, directions: PySide6.QtSerialPort.QSerialPort.Direction = ...) -> int: ...
    def bytes_available(self, /) -> int: ...
    def bytes_to_write(self, /) -> int: ...
    def can_read_line(self, /) -> bool: ...
    def clear(self, /, directions: PySide6.QtSerialPort.QSerialPort.Direction = ...) -> bool: ...
    def clear_error(self, /) -> None: ...
    def close(self, /) -> None: ...
    def data_bits(self, /) -> PySide6.QtSerialPort.QSerialPort.DataBits: ...
    def error(self, /) -> PySide6.QtSerialPort.QSerialPort.SerialPortError: ...
    def flow_control(self, /) -> PySide6.QtSerialPort.QSerialPort.FlowControl: ...
    def flush(self, /) -> bool: ...
    def handle(self, /) -> int: ...
    def is_break_enabled(self, /) -> bool: ...
    def is_data_terminal_ready(self, /) -> bool: ...
    def is_request_to_send(self, /) -> bool: ...
    def is_sequential(self, /) -> bool: ...
    def open(self, mode: PySide6.QtCore.QIODeviceBase.OpenModeFlag, /) -> bool: ...
    def parity(self, /) -> PySide6.QtSerialPort.QSerialPort.Parity: ...
    def pinout_signals(self, /) -> PySide6.QtSerialPort.QSerialPort.PinoutSignal: ...
    def port_name(self, /) -> str: ...
    def read_buffer_size(self, /) -> int: ...
    def read_data(self, maxSize: int, /) -> object: ...
    def read_line_data(self, maxSize: int, /) -> object: ...
    def set_baud_rate(self, baudRate: int, /, directions: PySide6.QtSerialPort.QSerialPort.Direction = ...) -> bool: ...
    def set_break_enabled(self, /, set: bool = ...) -> bool: ...
    def set_data_bits(self, dataBits: PySide6.QtSerialPort.QSerialPort.DataBits, /) -> bool: ...
    def set_data_terminal_ready(self, set: bool, /) -> bool: ...
    def set_flow_control(self, flowControl: PySide6.QtSerialPort.QSerialPort.FlowControl, /) -> bool: ...
    def set_parity(self, parity: PySide6.QtSerialPort.QSerialPort.Parity, /) -> bool: ...
    def set_port(self, info: PySide6.QtSerialPort.QSerialPortInfo, /) -> None: ...
    def set_port_name(self, name: str, /) -> None: ...
    def set_read_buffer_size(self, size: int, /) -> None: ...
    def set_request_to_send(self, set: bool, /) -> bool: ...
    def set_stop_bits(self, stopBits: PySide6.QtSerialPort.QSerialPort.StopBits, /) -> bool: ...
    def stop_bits(self, /) -> PySide6.QtSerialPort.QSerialPort.StopBits: ...
    def wait_for_bytes_written(self, /, msecs: int = ...) -> bool: ...
    def wait_for_ready_read(self, /, msecs: int = ...) -> bool: ...
    def write_data(self, data: bytes | bytearray | memoryview, maxSize: int, /) -> int: ...


class QSerialPortInfo(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, port: PySide6.QtSerialPort.QSerialPort, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtSerialPort.QSerialPortInfo, /) -> None: ...
    @typing.overload
    def __init__(self, name: str, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    @staticmethod
    def available_ports() -> typing.List[PySide6.QtSerialPort.QSerialPortInfo]: ...
    def description(self, /) -> str: ...
    def has_product_identifier(self, /) -> bool: ...
    def has_vendor_identifier(self, /) -> bool: ...
    def is_null(self, /) -> bool: ...
    def manufacturer(self, /) -> str: ...
    def port_name(self, /) -> str: ...
    def product_identifier(self, /) -> int: ...
    def serial_number(self, /) -> str: ...
    @staticmethod
    def standard_baud_rates() -> typing.List[int]: ...
    def swap(self, other: PySide6.QtSerialPort.QSerialPortInfo, /) -> None: ...
    def system_location(self, /) -> str: ...
    def vendor_identifier(self, /) -> int: ...


# eof
