# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtUiTools, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtUiTools`

import PySide6.QtUiTools
import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtWidgets

import os
import typing


class QIntList: ...


class QUiLoader(PySide6.QtCore.QObject):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def add_plugin_path(self, path: str, /) -> None: ...
    def available_layouts(self, /) -> typing.List[str]: ...
    def available_widgets(self, /) -> typing.List[str]: ...
    def clear_plugin_paths(self, /) -> None: ...
    def create_action(self, /, parent: PySide6.QtCore.QObject | None = ..., name: str = ...) -> PySide6.QtGui.QAction: ...
    def create_action_group(self, /, parent: PySide6.QtCore.QObject | None = ..., name: str = ...) -> PySide6.QtGui.QActionGroup: ...
    def create_layout(self, className: str, /, parent: PySide6.QtCore.QObject | None = ..., name: str = ...) -> PySide6.QtWidgets.QLayout: ...
    def create_widget(self, className: str, /, parent: PySide6.QtWidgets.QWidget | None = ..., name: str = ...) -> PySide6.QtWidgets.QWidget: ...
    def error_string(self, /) -> str: ...
    def is_language_change_enabled(self, /) -> bool: ...
    def is_translation_enabled(self, /) -> bool: ...
    @typing.overload
    def load(self, device: PySide6.QtCore.QIODevice, /, parentWidget: PySide6.QtWidgets.QWidget | None = ...) -> PySide6.QtWidgets.QWidget: ...
    @typing.overload
    def load(self, arg__1: str | bytes | os.PathLike[str], /, parentWidget: PySide6.QtWidgets.QWidget | None = ...) -> PySide6.QtWidgets.QWidget: ...
    def plugin_paths(self, /) -> typing.List[str]: ...
    def register_custom_widget(self, customWidgetType: object, /) -> None: ...
    def set_language_change_enabled(self, enabled: bool, /) -> None: ...
    def set_translation_enabled(self, enabled: bool, /) -> None: ...
    def set_working_directory(self, dir: PySide6.QtCore.QDir, /) -> None: ...
    def working_directory(self, /) -> PySide6.QtCore.QDir: ...


def loadUiType(uifile: str, /) -> object: ...


# eof
