# Generated by Django 4.2.14 on 2025-03-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_triggerdefinition'),
        ('schedules', '0002_schedulereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerdefinition',
            name='timing_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trigger_definition_timing_reference', to='schedules.schedulereference'),
        ),
        migrations.AddField(
            model_name='triggerdefinition',
            name='timing_timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trigger_definition_timing_timing', to='base.timing'),
        ),
    ]
