import bot_hosting_wrapper
bot_hosting_wrapper.LOGGING_ENABLED = True

acc = bot_hosting_wrapper.Account("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjExMTM4OTY2NTg3ODMxNzg4MzIiLCJhdmF0YXIiOiJmZDYwYzE4ODg1OWU0ZWVhNjJiNGMyMWJkZjBjYTNhNiIsInVzZXJuYW1lIjoibWlzdGFrZW5fc3dpdGNoIiwianRpIjoiNzU5NzAzMzYtMWMxZS00YzZhLTk2MzYtMDhkNjM1YzIxZDViIiwiaWF0IjoxNzM1ODMxNzE5LCJleHAiOjE3MzcwNDE3MTl9.dg-uFjSpJeheQoi1-sORM23VlmjS9IT5dwkKiIfGWr0")
acc.coins_amount()