# Generated by Django 4.2.14 on 2025-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_friendly_remove_contract_legal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttermaction',
            name='subject',
        ),
        migrations.AddField(
            model_name='contracttermaction',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='contract_term_action_subject', to='contracts.contracttermactionsubject'),
        ),
    ]
