from __future__ import annotations

class PokerEngineError(Exception):
    def __init__(self, message: str) -> None: ...
    def __str__(self) -> str: ...
    @property
    def class_name(self) -> str: ...
    @property
    def message(self) -> str: ...
