# coding: utf-8

"""
    Onboarding Buddy API Specification

    This specification details all the operations available to call in the Onboarding Buddy API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "onboarding-buddy-client"
VERSION = "1.0.3"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Onboarding Buddy API Specification",
    author="OpenAPI Generator community",
    author_email="support@onboardingbuddy.co",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Onboarding Buddy API Specification"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    This specification details all the operations available to call in the Onboarding Buddy API
    """,  # noqa: E501
    package_data={"onboarding_buddy_client": ["py.typed"]},
)