# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtWebEngineCore, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtWebEngineCore`

import PySide6.QtWebEngineCore
import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtNetwork
import PySide6.QtWebChannel

import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QIntList: ...


class QWebEngineCertificateError(Shiboken.Object):

    class Type(enum.Enum):

        SslObsoleteVersion        = ...  # -218
        CertificateKnownInterceptionBlocked = ...  # -217
        CertificateSymantecLegacy = ...  # -215
        CertificateTransparencyRequired = ...  # -214
        CertificateValidityTooLong = ...  # -213
        CertificateNameConstraintViolation = ...  # -212
        CertificateWeakKey        = ...  # -211
        CertificateNonUniqueName  = ...  # -210
        CertificateWeakSignatureAlgorithm = ...  # -208
        CertificateInvalid        = ...  # -207
        CertificateRevoked        = ...  # -206
        CertificateUnableToCheckRevocation = ...  # -205
        CertificateNoRevocationMechanism = ...  # -204
        CertificateContainsErrors = ...  # -203
        CertificateAuthorityInvalid = ...  # -202
        CertificateDateInvalid    = ...  # -201
        CertificateCommonNameInvalid = ...  # -200
        SslPinnedKeyNotInCertificateChain = ...  # -150


    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineCertificateError, /, *, url: PySide6.QtCore.QUrl | None = ..., type: PySide6.QtWebEngineCore.QWebEngineCertificateError.Type | None = ..., description: str | None = ..., overridable: bool | None = ..., is_main_frame: bool | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def accept_certificate(self, /) -> None: ...
    def certificate_chain(self, /) -> typing.List[PySide6.QtNetwork.QSslCertificate]: ...
    def defer(self, /) -> None: ...
    def description(self, /) -> str: ...
    def is_main_frame(self, /) -> bool: ...
    def is_overridable(self, /) -> bool: ...
    def reject_certificate(self, /) -> None: ...
    def type(self, /) -> PySide6.QtWebEngineCore.QWebEngineCertificateError.Type: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineClientCertificateSelection(Shiboken.Object):

    def __init__(self, arg__1: PySide6.QtWebEngineCore.QWebEngineClientCertificateSelection, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def certificates(self, /) -> typing.List[PySide6.QtNetwork.QSslCertificate]: ...
    def host(self, /) -> PySide6.QtCore.QUrl: ...
    def select(self, certificate: PySide6.QtNetwork.QSslCertificate | PySide6.QtCore.QIODevice, /) -> None: ...
    def select_none(self, /) -> None: ...


class QWebEngineClientCertificateStore(Shiboken.Object):
    def add(self, certificate: PySide6.QtNetwork.QSslCertificate | PySide6.QtCore.QIODevice, privateKey: PySide6.QtNetwork.QSslKey | int, /) -> None: ...
    def certificates(self, /) -> typing.List[PySide6.QtNetwork.QSslCertificate]: ...
    def clear(self, /) -> None: ...
    def remove(self, certificate: PySide6.QtNetwork.QSslCertificate | PySide6.QtCore.QIODevice, /) -> None: ...


class QWebEngineClientHints(PySide6.QtCore.QObject):
    def arch(self, /) -> str: ...
    def bitness(self, /) -> str: ...
    def full_version(self, /) -> str: ...
    def full_version_list(self, /) -> typing.Dict[str, typing.Any]: ...
    def is_all_client_hints_enabled(self, /) -> bool: ...
    def is_mobile(self, /) -> bool: ...
    def is_wow64(self, /) -> bool: ...
    def model(self, /) -> str: ...
    def platform(self, /) -> str: ...
    def platform_version(self, /) -> str: ...
    def qt_qml_marker_uncreatable(self, /) -> None: ...
    def reset_all(self, /) -> None: ...
    def set_all_client_hints_enabled(self, enabled: bool, /) -> None: ...
    def set_arch(self, arg__1: str, /) -> None: ...
    def set_bitness(self, arg__1: str, /) -> None: ...
    def set_full_version(self, arg__1: str, /) -> None: ...
    def set_full_version_list(self, arg__1: typing.Dict[str, typing.Any], /) -> None: ...
    def set_is_mobile(self, arg__1: bool, /) -> None: ...
    def set_is_wow64(self, arg__1: bool, /) -> None: ...
    def set_model(self, arg__1: str, /) -> None: ...
    def set_platform(self, arg__1: str, /) -> None: ...
    def set_platform_version(self, arg__1: str, /) -> None: ...


class QWebEngineContextMenuRequest(PySide6.QtCore.QObject):

    class EditFlag(enum.Flag):

        CanUndo                   = ...  # 0x1
        CanRedo                   = ...  # 0x2
        CanCut                    = ...  # 0x4
        CanCopy                   = ...  # 0x8
        CanPaste                  = ...  # 0x10
        CanDelete                 = ...  # 0x20
        CanSelectAll              = ...  # 0x40
        CanTranslate              = ...  # 0x80
        CanEditRichly             = ...  # 0x100

    class MediaFlag(enum.Flag):

        MediaInError              = ...  # 0x1
        MediaPaused               = ...  # 0x2
        MediaMuted                = ...  # 0x4
        MediaLoop                 = ...  # 0x8
        MediaCanSave              = ...  # 0x10
        MediaHasAudio             = ...  # 0x20
        MediaCanToggleControls    = ...  # 0x40
        MediaControls             = ...  # 0x80
        MediaCanPrint             = ...  # 0x100
        MediaCanRotate            = ...  # 0x200

    class MediaType(enum.Enum):

        MediaTypeNone             = ...  # 0x0
        MediaTypeImage            = ...  # 0x1
        MediaTypeVideo            = ...  # 0x2
        MediaTypeAudio            = ...  # 0x3
        MediaTypeCanvas           = ...  # 0x4
        MediaTypeFile             = ...  # 0x5
        MediaTypePlugin           = ...  # 0x6


    def edit_flags(self, /) -> PySide6.QtWebEngineCore.QWebEngineContextMenuRequest.EditFlag: ...
    def is_accepted(self, /) -> bool: ...
    def is_content_editable(self, /) -> bool: ...
    def link_text(self, /) -> str: ...
    def link_url(self, /) -> PySide6.QtCore.QUrl: ...
    def media_flags(self, /) -> PySide6.QtWebEngineCore.QWebEngineContextMenuRequest.MediaFlag: ...
    def media_type(self, /) -> PySide6.QtWebEngineCore.QWebEngineContextMenuRequest.MediaType: ...
    def media_url(self, /) -> PySide6.QtCore.QUrl: ...
    def misspelled_word(self, /) -> str: ...
    def position(self, /) -> PySide6.QtCore.QPoint: ...
    def selected_text(self, /) -> str: ...
    def set_accepted(self, accepted: bool, /) -> None: ...
    def spell_checker_suggestions(self, /) -> typing.List[str]: ...


class QWebEngineCookieStore(PySide6.QtCore.QObject):

    cookieAdded              : typing.ClassVar[Signal] = ... # cookieAdded(QNetworkCookie)
    cookieRemoved            : typing.ClassVar[Signal] = ... # cookieRemoved(QNetworkCookie)

    class FilterRequest(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, FilterRequest: PySide6.QtWebEngineCore.QWebEngineCookieStore.FilterRequest, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...


    def delete_all_cookies(self, /) -> None: ...
    def delete_cookie(self, cookie: PySide6.QtNetwork.QNetworkCookie, /, origin: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def delete_session_cookies(self, /) -> None: ...
    def load_all_cookies(self, /) -> None: ...
    def set_cookie(self, cookie: PySide6.QtNetwork.QNetworkCookie, /, origin: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def set_cookie_filter(self, filterCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...


class QWebEngineDesktopMediaRequest(Shiboken.Object):

    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineDesktopMediaRequest, /, *, screens_model: PySide6.QtCore.QAbstractListModel | None = ..., windows_model: PySide6.QtCore.QAbstractListModel | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def cancel(self, /) -> None: ...
    def screens_model(self, /) -> PySide6.QtCore.QAbstractListModel: ...
    def select_screen(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> None: ...
    def select_window(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> None: ...
    def windows_model(self, /) -> PySide6.QtCore.QAbstractListModel: ...


class QWebEngineDownloadRequest(PySide6.QtCore.QObject):

    downloadDirectoryChanged : typing.ClassVar[Signal] = ... # downloadDirectoryChanged()
    downloadFileNameChanged  : typing.ClassVar[Signal] = ... # downloadFileNameChanged()
    interruptReasonChanged   : typing.ClassVar[Signal] = ... # interruptReasonChanged()
    isFinishedChanged        : typing.ClassVar[Signal] = ... # isFinishedChanged()
    isPausedChanged          : typing.ClassVar[Signal] = ... # isPausedChanged()
    receivedBytesChanged     : typing.ClassVar[Signal] = ... # receivedBytesChanged()
    savePageFormatChanged    : typing.ClassVar[Signal] = ... # savePageFormatChanged()
    stateChanged             : typing.ClassVar[Signal] = ... # stateChanged(QWebEngineDownloadRequest::DownloadState)
    totalBytesChanged        : typing.ClassVar[Signal] = ... # totalBytesChanged()

    class DownloadInterruptReason(enum.Enum):

        NoReason                  = ...  # 0x0
        FileFailed                = ...  # 0x1
        FileAccessDenied          = ...  # 0x2
        FileNoSpace               = ...  # 0x3
        FileNameTooLong           = ...  # 0x5
        FileTooLarge              = ...  # 0x6
        FileVirusInfected         = ...  # 0x7
        FileTransientError        = ...  # 0xa
        FileBlocked               = ...  # 0xb
        FileSecurityCheckFailed   = ...  # 0xc
        FileTooShort              = ...  # 0xd
        FileHashMismatch          = ...  # 0xe
        NetworkFailed             = ...  # 0x14
        NetworkTimeout            = ...  # 0x15
        NetworkDisconnected       = ...  # 0x16
        NetworkServerDown         = ...  # 0x17
        NetworkInvalidRequest     = ...  # 0x18
        ServerFailed              = ...  # 0x1e
        ServerBadContent          = ...  # 0x21
        ServerUnauthorized        = ...  # 0x22
        ServerCertProblem         = ...  # 0x23
        ServerForbidden           = ...  # 0x24
        ServerUnreachable         = ...  # 0x25
        UserCanceled              = ...  # 0x28

    class DownloadState(enum.Enum):

        DownloadRequested         = ...  # 0x0
        DownloadInProgress        = ...  # 0x1
        DownloadCompleted         = ...  # 0x2
        DownloadCancelled         = ...  # 0x3
        DownloadInterrupted       = ...  # 0x4

    class SavePageFormat(enum.Enum):

        UnknownSaveFormat         = ...  # -1
        SingleHtmlSaveFormat      = ...  # 0x0
        CompleteHtmlSaveFormat    = ...  # 0x1
        MimeHtmlSaveFormat        = ...  # 0x2


    def accept(self, /) -> None: ...
    def cancel(self, /) -> None: ...
    def download_directory(self, /) -> str: ...
    def download_file_name(self, /) -> str: ...
    def id(self, /) -> int: ...
    def interrupt_reason(self, /) -> PySide6.QtWebEngineCore.QWebEngineDownloadRequest.DownloadInterruptReason: ...
    def interrupt_reason_string(self, /) -> str: ...
    def is_finished(self, /) -> bool: ...
    def is_paused(self, /) -> bool: ...
    def is_save_page_download(self, /) -> bool: ...
    def mime_type(self, /) -> str: ...
    def page(self, /) -> PySide6.QtWebEngineCore.QWebEnginePage: ...
    def pause(self, /) -> None: ...
    def received_bytes(self, /) -> int: ...
    def resume(self, /) -> None: ...
    def save_page_format(self, /) -> PySide6.QtWebEngineCore.QWebEngineDownloadRequest.SavePageFormat: ...
    def set_download_directory(self, directory: str, /) -> None: ...
    def set_download_file_name(self, fileName: str, /) -> None: ...
    def set_save_page_format(self, format: PySide6.QtWebEngineCore.QWebEngineDownloadRequest.SavePageFormat, /) -> None: ...
    def state(self, /) -> PySide6.QtWebEngineCore.QWebEngineDownloadRequest.DownloadState: ...
    def suggested_file_name(self, /) -> str: ...
    def total_bytes(self, /) -> int: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineFileSystemAccessRequest(Shiboken.Object):

    class AccessFlag(enum.Flag):

        Read                      = ...  # 0x1
        Write                     = ...  # 0x2

    class HandleType(enum.Enum):

        File                      = ...  # 0x0
        Directory                 = ...  # 0x1


    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest, /, *, origin: PySide6.QtCore.QUrl | None = ..., file_path: PySide6.QtCore.QUrl | None = ..., handle_type: PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest.HandleType | None = ..., access_flags: PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest.AccessFlag | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest, /) -> bool: ...
    def accept(self, /) -> None: ...
    def access_flags(self, /) -> PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest.AccessFlag: ...
    def file_path(self, /) -> PySide6.QtCore.QUrl: ...
    def handle_type(self, /) -> PySide6.QtWebEngineCore.QWebEngineFileSystemAccessRequest.HandleType: ...
    def origin(self, /) -> PySide6.QtCore.QUrl: ...
    def reject(self, /) -> None: ...


class QWebEngineFindTextResult(Shiboken.Object):

    @typing.overload
    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineFindTextResult, /, *, number_of_matches: int | None = ..., active_match: int | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, number_of_matches: int | None = ..., active_match: int | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def active_match(self, /) -> int: ...
    def number_of_matches(self, /) -> int: ...


class QWebEngineFrame(Shiboken.Object):
    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtWebEngineCore.QWebEngineFrame, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtWebEngineCore.QWebEngineFrame, /) -> bool: ...
    def children(self, /) -> typing.List[PySide6.QtWebEngineCore.QWebEngineFrame]: ...
    def html_name(self, /) -> str: ...
    def is_main_frame(self, /) -> bool: ...
    def is_valid(self, /) -> bool: ...
    def name(self, /) -> str: ...
    @typing.overload
    def print_to_pdf(self, filePath: str, /) -> None: ...
    @typing.overload
    def print_to_pdf(self, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    @typing.overload
    def run_java_script(self, scriptSource: str, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    @typing.overload
    def run_java_script(self, scriptSource: str, worldId: int, /, resultCallback: collections.abc.Callable[..., typing.Any] = ...) -> None: ...
    def size(self, /) -> PySide6.QtCore.QSizeF: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineFullScreenRequest(Shiboken.Object):

    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineFullScreenRequest, /, *, toggle_on: bool | None = ..., origin: PySide6.QtCore.QUrl | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def accept(self, /) -> None: ...
    def origin(self, /) -> PySide6.QtCore.QUrl: ...
    def reject(self, /) -> None: ...
    def toggle_on(self, /) -> bool: ...


class QWebEngineGlobalSettings(Shiboken.Object):

    class DnsMode(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, DnsMode: PySide6.QtWebEngineCore.QWebEngineGlobalSettings.DnsMode, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...

    class SecureDnsMode(enum.Enum):

        SystemOnly                = ...  # 0x0
        SecureWithFallback        = ...  # 0x1
        SecureOnly                = ...  # 0x2


    @staticmethod
    def set_dns_mode(dnsMode: PySide6.QtWebEngineCore.QWebEngineGlobalSettings.DnsMode, /) -> bool: ...


class QWebEngineHistory(PySide6.QtCore.QObject):
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def back(self, /) -> None: ...
    def back_item(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryItem: ...
    def back_items(self, maxItems: int, /) -> typing.List[PySide6.QtWebEngineCore.QWebEngineHistoryItem]: ...
    def back_items_model(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryModel: ...
    def can_go_back(self, /) -> bool: ...
    def can_go_forward(self, /) -> bool: ...
    def clear(self, /) -> None: ...
    def count(self, /) -> int: ...
    def current_item(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryItem: ...
    def current_item_index(self, /) -> int: ...
    def forward(self, /) -> None: ...
    def forward_item(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryItem: ...
    def forward_items(self, maxItems: int, /) -> typing.List[PySide6.QtWebEngineCore.QWebEngineHistoryItem]: ...
    def forward_items_model(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryModel: ...
    def go_to_item(self, item: PySide6.QtWebEngineCore.QWebEngineHistoryItem, /) -> None: ...
    def item_at(self, i: int, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryItem: ...
    def items(self, /) -> typing.List[PySide6.QtWebEngineCore.QWebEngineHistoryItem]: ...
    def items_model(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistoryModel: ...


class QWebEngineHistoryItem(Shiboken.Object):

    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineHistoryItem, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def icon_url(self, /) -> PySide6.QtCore.QUrl: ...
    def is_valid(self, /) -> bool: ...
    def last_visited(self, /) -> PySide6.QtCore.QDateTime: ...
    def original_url(self, /) -> PySide6.QtCore.QUrl: ...
    def title(self, /) -> str: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineHistoryModel(PySide6.QtCore.QAbstractListModel):

    class Roles(enum.Enum):

        UrlRole                   = ...  # 0x100
        TitleRole                 = ...  # 0x101
        OffsetRole                = ...  # 0x102
        IconUrlRole               = ...  # 0x103


    def data(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /, role: int = ...) -> typing.Any: ...
    def reset(self, /) -> None: ...
    def role_names(self, /) -> typing.Dict[int, PySide6.QtCore.QByteArray]: ...
    def row_count(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> int: ...


class QWebEngineHttpRequest(Shiboken.Object):

    class Method(enum.Enum):

        Get                       = ...  # 0x0
        Post                      = ...  # 0x1


    @typing.overload
    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineHttpRequest, /) -> None: ...
    @typing.overload
    def __init__(self, /, url: PySide6.QtCore.QUrl | str = ..., method: PySide6.QtWebEngineCore.QWebEngineHttpRequest.Method = ...) -> None: ...

    def __eq__(self, other: PySide6.QtWebEngineCore.QWebEngineHttpRequest, /) -> bool: ...
    def __ne__(self, other: PySide6.QtWebEngineCore.QWebEngineHttpRequest, /) -> bool: ...
    def has_header(self, headerName: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> bool: ...
    def header(self, headerName: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> PySide6.QtCore.QByteArray: ...
    def headers(self, /) -> typing.List[PySide6.QtCore.QByteArray]: ...
    def method(self, /) -> PySide6.QtWebEngineCore.QWebEngineHttpRequest.Method: ...
    def post_data(self, /) -> PySide6.QtCore.QByteArray: ...
    @staticmethod
    def post_request(url: PySide6.QtCore.QUrl | str, postData: typing.Dict[str, str], /) -> PySide6.QtWebEngineCore.QWebEngineHttpRequest: ...
    def set_header(self, headerName: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, value: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def set_method(self, method: PySide6.QtWebEngineCore.QWebEngineHttpRequest.Method, /) -> None: ...
    def set_post_data(self, postData: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def set_url(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def swap(self, other: PySide6.QtWebEngineCore.QWebEngineHttpRequest, /) -> None: ...
    def unset_header(self, headerName: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineLoadingInfo(Shiboken.Object):

    class ErrorDomain(enum.Enum):

        NoErrorDomain             = ...  # 0x0
        InternalErrorDomain       = ...  # 0x1
        ConnectionErrorDomain     = ...  # 0x2
        CertificateErrorDomain    = ...  # 0x3
        HttpErrorDomain           = ...  # 0x4
        FtpErrorDomain            = ...  # 0x5
        DnsErrorDomain            = ...  # 0x6
        HttpStatusCodeDomain      = ...  # 0x7

    class LoadStatus(enum.Enum):

        LoadStartedStatus         = ...  # 0x0
        LoadStoppedStatus         = ...  # 0x1
        LoadSucceededStatus       = ...  # 0x2
        LoadFailedStatus          = ...  # 0x3


    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineLoadingInfo, /, *, url: PySide6.QtCore.QUrl | None = ..., is_error_page: bool | None = ..., status: PySide6.QtWebEngineCore.QWebEngineLoadingInfo.LoadStatus | None = ..., error_string: str | None = ..., error_domain: PySide6.QtWebEngineCore.QWebEngineLoadingInfo.ErrorDomain | None = ..., error_code: int | None = ..., response_headers: typing.Optional[typing.Dict[PySide6.QtCore.QByteArray, PySide6.QtCore.QByteArray]] = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def error_code(self, /) -> int: ...
    def error_domain(self, /) -> PySide6.QtWebEngineCore.QWebEngineLoadingInfo.ErrorDomain: ...
    def error_string(self, /) -> str: ...
    def is_error_page(self, /) -> bool: ...
    def response_headers(self, /) -> typing.Dict[PySide6.QtCore.QByteArray, PySide6.QtCore.QByteArray]: ...
    def status(self, /) -> PySide6.QtWebEngineCore.QWebEngineLoadingInfo.LoadStatus: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineNavigationRequest(PySide6.QtCore.QObject):

    actionChanged            : typing.ClassVar[Signal] = ... # actionChanged()

    class NavigationRequestAction(enum.Enum):

        AcceptRequest             = ...  # 0x0
        IgnoreRequest             = ...  # 0xff

    class NavigationType(enum.Enum):

        LinkClickedNavigation     = ...  # 0x0
        TypedNavigation           = ...  # 0x1
        FormSubmittedNavigation   = ...  # 0x2
        BackForwardNavigation     = ...  # 0x3
        ReloadNavigation          = ...  # 0x4
        OtherNavigation           = ...  # 0x5
        RedirectNavigation        = ...  # 0x6


    def accept(self, /) -> None: ...
    def has_form_data(self, /) -> bool: ...
    def is_main_frame(self, /) -> bool: ...
    def navigation_type(self, /) -> PySide6.QtWebEngineCore.QWebEngineNavigationRequest.NavigationType: ...
    def reject(self, /) -> None: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineNewWindowRequest(PySide6.QtCore.QObject):

    class DestinationType(enum.Enum):

        InNewWindow               = ...  # 0x0
        InNewTab                  = ...  # 0x1
        InNewDialog               = ...  # 0x2
        InNewBackgroundTab        = ...  # 0x3


    def destination(self, /) -> PySide6.QtWebEngineCore.QWebEngineNewWindowRequest.DestinationType: ...
    def is_user_initiated(self, /) -> bool: ...
    def open_in(self, arg__1: PySide6.QtWebEngineCore.QWebEnginePage, /) -> None: ...
    def requested_geometry(self, /) -> PySide6.QtCore.QRect: ...
    def requested_url(self, /) -> PySide6.QtCore.QUrl: ...


class QWebEngineNotification(PySide6.QtCore.QObject):

    closed                   : typing.ClassVar[Signal] = ... # closed()
    def click(self, /) -> None: ...
    def close(self, /) -> None: ...
    def direction(self, /) -> PySide6.QtCore.Qt.LayoutDirection: ...
    def icon(self, /) -> PySide6.QtGui.QImage: ...
    def language(self, /) -> str: ...
    def matches(self, other: PySide6.QtWebEngineCore.QWebEngineNotification, /) -> bool: ...
    def message(self, /) -> str: ...
    def origin(self, /) -> PySide6.QtCore.QUrl: ...
    def show(self, /) -> None: ...
    def tag(self, /) -> str: ...
    def title(self, /) -> str: ...


class QWebEnginePage(PySide6.QtCore.QObject):

    _q_aboutToDelete         : typing.ClassVar[Signal] = ... # _q_aboutToDelete()
    audioMutedChanged        : typing.ClassVar[Signal] = ... # audioMutedChanged(bool)
    authenticationRequired   : typing.ClassVar[Signal] = ... # authenticationRequired(QUrl,QAuthenticator*)
    certificateError         : typing.ClassVar[Signal] = ... # certificateError(QWebEngineCertificateError)
    contentsSizeChanged      : typing.ClassVar[Signal] = ... # contentsSizeChanged(QSizeF)
    desktopMediaRequested    : typing.ClassVar[Signal] = ... # desktopMediaRequested(QWebEngineDesktopMediaRequest)
    featurePermissionRequestCanceled: typing.ClassVar[Signal] = ... # featurePermissionRequestCanceled(QUrl,QWebEnginePage::Feature)
    featurePermissionRequested: typing.ClassVar[Signal] = ... # featurePermissionRequested(QUrl,QWebEnginePage::Feature)
    fileSystemAccessRequested: typing.ClassVar[Signal] = ... # fileSystemAccessRequested(QWebEngineFileSystemAccessRequest)
    findTextFinished         : typing.ClassVar[Signal] = ... # findTextFinished(QWebEngineFindTextResult)
    fullScreenRequested      : typing.ClassVar[Signal] = ... # fullScreenRequested(QWebEngineFullScreenRequest)
    geometryChangeRequested  : typing.ClassVar[Signal] = ... # geometryChangeRequested(QRect)
    iconChanged              : typing.ClassVar[Signal] = ... # iconChanged(QIcon)
    iconUrlChanged           : typing.ClassVar[Signal] = ... # iconUrlChanged(QUrl)
    lifecycleStateChanged    : typing.ClassVar[Signal] = ... # lifecycleStateChanged(LifecycleState)
    linkHovered              : typing.ClassVar[Signal] = ... # linkHovered(QString)
    loadFinished             : typing.ClassVar[Signal] = ... # loadFinished(bool)
    loadProgress             : typing.ClassVar[Signal] = ... # loadProgress(int)
    loadStarted              : typing.ClassVar[Signal] = ... # loadStarted()
    loadingChanged           : typing.ClassVar[Signal] = ... # loadingChanged(QWebEngineLoadingInfo)
    navigationRequested      : typing.ClassVar[Signal] = ... # navigationRequested(QWebEngineNavigationRequest&)
    newWindowRequested       : typing.ClassVar[Signal] = ... # newWindowRequested(QWebEngineNewWindowRequest&)
    pdfPrintingFinished      : typing.ClassVar[Signal] = ... # pdfPrintingFinished(QString,bool)
    permissionRequested      : typing.ClassVar[Signal] = ... # permissionRequested(QWebEnginePermission)
    printRequested           : typing.ClassVar[Signal] = ... # printRequested()
    printRequestedByFrame    : typing.ClassVar[Signal] = ... # printRequestedByFrame(QWebEngineFrame)
    proxyAuthenticationRequired: typing.ClassVar[Signal] = ... # proxyAuthenticationRequired(QUrl,QAuthenticator*,QString)
    quotaRequested           : typing.ClassVar[Signal] = ... # quotaRequested(QWebEngineQuotaRequest)
    recentlyAudibleChanged   : typing.ClassVar[Signal] = ... # recentlyAudibleChanged(bool)
    recommendedStateChanged  : typing.ClassVar[Signal] = ... # recommendedStateChanged(LifecycleState)
    registerProtocolHandlerRequested: typing.ClassVar[Signal] = ... # registerProtocolHandlerRequested(QWebEngineRegisterProtocolHandlerRequest)
    renderProcessPidChanged  : typing.ClassVar[Signal] = ... # renderProcessPidChanged(qlonglong)
    renderProcessTerminated  : typing.ClassVar[Signal] = ... # renderProcessTerminated(RenderProcessTerminationStatus,int)
    scrollPositionChanged    : typing.ClassVar[Signal] = ... # scrollPositionChanged(QPointF)
    selectClientCertificate  : typing.ClassVar[Signal] = ... # selectClientCertificate(QWebEngineClientCertificateSelection)
    selectionChanged         : typing.ClassVar[Signal] = ... # selectionChanged()
    titleChanged             : typing.ClassVar[Signal] = ... # titleChanged(QString)
    urlChanged               : typing.ClassVar[Signal] = ... # urlChanged(QUrl)
    visibleChanged           : typing.ClassVar[Signal] = ... # visibleChanged(bool)
    webAuthUxRequested       : typing.ClassVar[Signal] = ... # webAuthUxRequested(QWebEngineWebAuthUxRequest*)
    windowCloseRequested     : typing.ClassVar[Signal] = ... # windowCloseRequested()
    zoomFactorChanged        : typing.ClassVar[Signal] = ... # zoomFactorChanged(double)

    class Feature(enum.Enum):

        Notifications             = ...  # 0x0
        Geolocation               = ...  # 0x1
        MediaAudioCapture         = ...  # 0x2
        MediaVideoCapture         = ...  # 0x3
        MediaAudioVideoCapture    = ...  # 0x4
        MouseLock                 = ...  # 0x5
        DesktopVideoCapture       = ...  # 0x6
        DesktopAudioVideoCapture  = ...  # 0x7
        ClipboardReadWrite        = ...  # 0x8
        LocalFontsAccess          = ...  # 0x9

    class FileSelectionMode(enum.Enum):

        FileSelectOpen            = ...  # 0x0
        FileSelectOpenMultiple    = ...  # 0x1
        FileSelectUploadFolder    = ...  # 0x2
        FileSelectSave            = ...  # 0x3

    class FindFlag(enum.Flag):

        FindBackward              = ...  # 0x1
        FindCaseSensitively       = ...  # 0x2

    class JavaScriptConsoleMessageLevel(enum.Enum):

        InfoMessageLevel          = ...  # 0x0
        WarningMessageLevel       = ...  # 0x1
        ErrorMessageLevel         = ...  # 0x2

    class LifecycleState(enum.Enum):

        Active                    = ...  # 0x0
        Frozen                    = ...  # 0x1
        Discarded                 = ...  # 0x2

    class NavigationType(enum.Enum):

        NavigationTypeLinkClicked = ...  # 0x0
        NavigationTypeTyped       = ...  # 0x1
        NavigationTypeFormSubmitted = ...  # 0x2
        NavigationTypeBackForward = ...  # 0x3
        NavigationTypeReload      = ...  # 0x4
        NavigationTypeOther       = ...  # 0x5
        NavigationTypeRedirect    = ...  # 0x6

    class PermissionPolicy(enum.Enum):

        PermissionUnknown         = ...  # 0x0
        PermissionGrantedByUser   = ...  # 0x1
        PermissionDeniedByUser    = ...  # 0x2

    class RenderProcessTerminationStatus(enum.Enum):

        NormalTerminationStatus   = ...  # 0x0
        AbnormalTerminationStatus = ...  # 0x1
        CrashedTerminationStatus  = ...  # 0x2
        KilledTerminationStatus   = ...  # 0x3

    class WebAction(enum.Enum):

        NoWebAction               = ...  # -1
        Back                      = ...  # 0x0
        Forward                   = ...  # 0x1
        Stop                      = ...  # 0x2
        Reload                    = ...  # 0x3
        Cut                       = ...  # 0x4
        Copy                      = ...  # 0x5
        Paste                     = ...  # 0x6
        Undo                      = ...  # 0x7
        Redo                      = ...  # 0x8
        SelectAll                 = ...  # 0x9
        ReloadAndBypassCache      = ...  # 0xa
        PasteAndMatchStyle        = ...  # 0xb
        OpenLinkInThisWindow      = ...  # 0xc
        OpenLinkInNewWindow       = ...  # 0xd
        OpenLinkInNewTab          = ...  # 0xe
        CopyLinkToClipboard       = ...  # 0xf
        DownloadLinkToDisk        = ...  # 0x10
        CopyImageToClipboard      = ...  # 0x11
        CopyImageUrlToClipboard   = ...  # 0x12
        DownloadImageToDisk       = ...  # 0x13
        CopyMediaUrlToClipboard   = ...  # 0x14
        ToggleMediaControls       = ...  # 0x15
        ToggleMediaLoop           = ...  # 0x16
        ToggleMediaPlayPause      = ...  # 0x17
        ToggleMediaMute           = ...  # 0x18
        DownloadMediaToDisk       = ...  # 0x19
        InspectElement            = ...  # 0x1a
        ExitFullScreen            = ...  # 0x1b
        RequestClose              = ...  # 0x1c
        Unselect                  = ...  # 0x1d
        SavePage                  = ...  # 0x1e
        OpenLinkInNewBackgroundTab = ...  # 0x1f
        ViewSource                = ...  # 0x20
        ToggleBold                = ...  # 0x21
        ToggleItalic              = ...  # 0x22
        ToggleUnderline           = ...  # 0x23
        ToggleStrikethrough       = ...  # 0x24
        AlignLeft                 = ...  # 0x25
        AlignCenter               = ...  # 0x26
        AlignRight                = ...  # 0x27
        AlignJustified            = ...  # 0x28
        Indent                    = ...  # 0x29
        Outdent                   = ...  # 0x2a
        InsertOrderedList         = ...  # 0x2b
        InsertUnorderedList       = ...  # 0x2c
        ChangeTextDirectionLTR    = ...  # 0x2d
        ChangeTextDirectionRTL    = ...  # 0x2e
        WebActionCount            = ...  # 0x2f

    class WebWindowType(enum.Enum):

        WebBrowserWindow          = ...  # 0x0
        WebBrowserTab             = ...  # 0x1
        WebDialog                 = ...  # 0x2
        WebBrowserBackgroundTab   = ...  # 0x3


    @typing.overload
    def __init__(self, profile: PySide6.QtWebEngineCore.QWebEngineProfile, /, parent: PySide6.QtCore.QObject | None = ..., *, selected_text: str | None = ..., has_selection: bool | None = ..., requested_url: PySide6.QtCore.QUrl | None = ..., zoom_factor: float | None = ..., title: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., icon_url: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtGui.QIcon | None = ..., background_color: PySide6.QtGui.QColor | None = ..., contents_size: PySide6.QtCore.QSizeF | None = ..., scroll_position: PySide6.QtCore.QPointF | None = ..., audio_muted: bool | None = ..., recently_audible: bool | None = ..., visible: bool | None = ..., lifecycle_state: PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState | None = ..., recommended_state: PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState | None = ..., render_process_pid: int | None = ..., loading: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, selected_text: str | None = ..., has_selection: bool | None = ..., requested_url: PySide6.QtCore.QUrl | None = ..., zoom_factor: float | None = ..., title: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., icon_url: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtGui.QIcon | None = ..., background_color: PySide6.QtGui.QColor | None = ..., contents_size: PySide6.QtCore.QSizeF | None = ..., scroll_position: PySide6.QtCore.QPointF | None = ..., audio_muted: bool | None = ..., recently_audible: bool | None = ..., visible: bool | None = ..., lifecycle_state: PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState | None = ..., recommended_state: PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState | None = ..., render_process_pid: int | None = ..., loading: bool | None = ...) -> None: ...

    def accept_as_new_window(self, request: PySide6.QtWebEngineCore.QWebEngineNewWindowRequest, /) -> None: ...
    def accept_navigation_request(self, url: PySide6.QtCore.QUrl | str, type: PySide6.QtWebEngineCore.QWebEnginePage.NavigationType, isMainFrame: bool, /) -> bool: ...
    def action(self, action: PySide6.QtWebEngineCore.QWebEnginePage.WebAction, /) -> PySide6.QtGui.QAction: ...
    def background_color(self, /) -> PySide6.QtGui.QColor: ...
    def choose_files(self, mode: PySide6.QtWebEngineCore.QWebEnginePage.FileSelectionMode, oldFiles: collections.abc.Sequence[str], acceptedMimeTypes: collections.abc.Sequence[str], /) -> typing.List[str]: ...
    def contents_size(self, /) -> PySide6.QtCore.QSizeF: ...
    def create_window(self, type: PySide6.QtWebEngineCore.QWebEnginePage.WebWindowType, /) -> PySide6.QtWebEngineCore.QWebEnginePage: ...
    def dev_tools_id(self, /) -> str: ...
    def dev_tools_page(self, /) -> PySide6.QtWebEngineCore.QWebEnginePage: ...
    def download(self, url: PySide6.QtCore.QUrl | str, /, filename: str = ...) -> None: ...
    def event(self, arg__1: PySide6.QtCore.QEvent, /) -> bool: ...
    def find_frame_by_name(self, name: str, /) -> PySide6.QtWebEngineCore.QWebEngineFrame: ...
    @typing.overload
    def find_text(self, subString: str, /, options: PySide6.QtWebEngineCore.QWebEnginePage.FindFlag = ...) -> None: ...
    @typing.overload
    def find_text(self, subString: str, options: PySide6.QtWebEngineCore.QWebEnginePage.FindFlag, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    def has_selection(self, /) -> bool: ...
    def history(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistory: ...
    def icon(self, /) -> PySide6.QtGui.QIcon: ...
    def icon_url(self, /) -> PySide6.QtCore.QUrl: ...
    def inspected_page(self, /) -> PySide6.QtWebEngineCore.QWebEnginePage: ...
    def is_audio_muted(self, /) -> bool: ...
    def is_loading(self, /) -> bool: ...
    def is_visible(self, /) -> bool: ...
    def java_script_alert(self, securityOrigin: PySide6.QtCore.QUrl | str, msg: str, /) -> None: ...
    def java_script_confirm(self, securityOrigin: PySide6.QtCore.QUrl | str, msg: str, /) -> bool: ...
    def java_script_console_message(self, level: PySide6.QtWebEngineCore.QWebEnginePage.JavaScriptConsoleMessageLevel, message: str, lineNumber: int, sourceID: str, /) -> None: ...
    def java_script_prompt(self, securityOrigin: PySide6.QtCore.QUrl | str, msg: str, defaultValue: str, /) -> typing.Tuple[bool, str]: ...
    def lifecycle_state(self, /) -> PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState: ...
    @typing.overload
    def load(self, request: PySide6.QtWebEngineCore.QWebEngineHttpRequest, /) -> None: ...
    @typing.overload
    def load(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def main_frame(self, /) -> PySide6.QtWebEngineCore.QWebEngineFrame: ...
    @typing.overload
    def print_to_pdf(self, filePath: str, /, layout: PySide6.QtGui.QPageLayout = ..., ranges: PySide6.QtGui.QPageRanges = ...) -> None: ...
    @typing.overload
    def print_to_pdf(self, resultCallback: collections.abc.Callable[..., typing.Any], /, pageLayout: PySide6.QtGui.QPageLayout = ..., ranges: PySide6.QtGui.QPageRanges = ...) -> None: ...
    def profile(self, /) -> PySide6.QtWebEngineCore.QWebEngineProfile: ...
    def recently_audible(self, /) -> bool: ...
    def recommended_state(self, /) -> PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState: ...
    def render_process_pid(self, /) -> int: ...
    def replace_misspelled_word(self, replacement: str, /) -> None: ...
    def requested_url(self, /) -> PySide6.QtCore.QUrl: ...
    @typing.overload
    def run_java_script(self, scriptSource: str, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    @typing.overload
    def run_java_script(self, scriptSource: str, /, worldId: int | None = ..., resultCallback: collections.abc.Callable[..., typing.Any] = ...) -> None: ...
    def save(self, filePath: str, /, format: PySide6.QtWebEngineCore.QWebEngineDownloadRequest.SavePageFormat = ...) -> None: ...
    def scripts(self, /) -> PySide6.QtWebEngineCore.QWebEngineScriptCollection: ...
    def scroll_position(self, /) -> PySide6.QtCore.QPointF: ...
    def selected_text(self, /) -> str: ...
    def set_audio_muted(self, muted: bool, /) -> None: ...
    def set_background_color(self, color: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
    def set_content(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /, mimeType: str = ..., baseUrl: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def set_dev_tools_page(self, page: PySide6.QtWebEngineCore.QWebEnginePage, /) -> None: ...
    def set_feature_permission(self, securityOrigin: PySide6.QtCore.QUrl | str, feature: PySide6.QtWebEngineCore.QWebEnginePage.Feature, policy: PySide6.QtWebEngineCore.QWebEnginePage.PermissionPolicy, /) -> None: ...
    def set_html(self, html: str, /, baseUrl: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def set_inspected_page(self, page: PySide6.QtWebEngineCore.QWebEnginePage, /) -> None: ...
    def set_lifecycle_state(self, state: PySide6.QtWebEngineCore.QWebEnginePage.LifecycleState, /) -> None: ...
    def set_url(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_url_request_interceptor(self, interceptor: PySide6.QtWebEngineCore.QWebEngineUrlRequestInterceptor, /) -> None: ...
    def set_visible(self, visible: bool, /) -> None: ...
    def set_web_channel(self, arg__1: PySide6.QtWebChannel.QWebChannel, /, worldId: int | None = ...) -> None: ...
    def set_zoom_factor(self, factor: float, /) -> None: ...
    def settings(self, /) -> PySide6.QtWebEngineCore.QWebEngineSettings: ...
    def title(self, /) -> str: ...
    def to_html(self, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    def to_plain_text(self, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    def trigger_action(self, action: PySide6.QtWebEngineCore.QWebEnginePage.WebAction, /, checked: bool = ...) -> None: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...
    def web_channel(self, /) -> PySide6.QtWebChannel.QWebChannel: ...
    def zoom_factor(self, /) -> float: ...


class QWebEnginePermission(Shiboken.Object):

    class PermissionType(enum.Enum):

        Unsupported               = ...  # 0x0
        MediaAudioCapture         = ...  # 0x1
        MediaVideoCapture         = ...  # 0x2
        MediaAudioVideoCapture    = ...  # 0x3
        DesktopVideoCapture       = ...  # 0x4
        DesktopAudioVideoCapture  = ...  # 0x5
        MouseLock                 = ...  # 0x6
        Notifications             = ...  # 0x7
        Geolocation               = ...  # 0x8
        ClipboardReadWrite        = ...  # 0x9
        LocalFontsAccess          = ...  # 0xa

    class State(enum.Enum):

        Invalid                   = ...  # 0x0
        Ask                       = ...  # 0x1
        Granted                   = ...  # 0x2
        Denied                    = ...  # 0x3


    @typing.overload
    def __init__(self, other: PySide6.QtWebEngineCore.QWebEnginePermission, /, *, origin: PySide6.QtCore.QUrl | None = ..., permission_type: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType | None = ..., state: PySide6.QtWebEngineCore.QWebEnginePermission.State | None = ..., is_valid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, origin: PySide6.QtCore.QUrl | None = ..., permission_type: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType | None = ..., state: PySide6.QtWebEngineCore.QWebEnginePermission.State | None = ..., is_valid: bool | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, rhs: PySide6.QtWebEngineCore.QWebEnginePermission, /) -> bool: ...
    def __ne__(self, rhs: PySide6.QtWebEngineCore.QWebEnginePermission, /) -> bool: ...
    def deny(self, /) -> None: ...
    def grant(self, /) -> None: ...
    @staticmethod
    def is_persistent(permissionType: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType, /) -> bool: ...
    def is_valid(self, /) -> bool: ...
    def origin(self, /) -> PySide6.QtCore.QUrl: ...
    def permission_type(self, /) -> PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType: ...
    def reset(self, /) -> None: ...
    def state(self, /) -> PySide6.QtWebEngineCore.QWebEnginePermission.State: ...
    def swap(self, other: PySide6.QtWebEngineCore.QWebEnginePermission, /) -> None: ...


class QWebEngineProfile(PySide6.QtCore.QObject):

    clearHttpCacheCompleted  : typing.ClassVar[Signal] = ... # clearHttpCacheCompleted()
    downloadRequested        : typing.ClassVar[Signal] = ... # downloadRequested(QWebEngineDownloadRequest*)

    class HttpCacheType(enum.Enum):

        MemoryHttpCache           = ...  # 0x0
        DiskHttpCache             = ...  # 0x1
        NoCache                   = ...  # 0x2

    class PersistentCookiesPolicy(enum.Enum):

        NoPersistentCookies       = ...  # 0x0
        AllowPersistentCookies    = ...  # 0x1
        ForcePersistentCookies    = ...  # 0x2

    class PersistentPermissionsPolicy(enum.Enum):

        AskEveryTime              = ...  # 0x0
        StoreInMemory             = ...  # 0x1
        StoreOnDisk               = ...  # 0x2


    @typing.overload
    def __init__(self, name: str, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def cache_path(self, /) -> str: ...
    def clear_all_visited_links(self, /) -> None: ...
    def clear_http_cache(self, /) -> None: ...
    def clear_visited_links(self, urls: collections.abc.Sequence[PySide6.QtCore.QUrl], /) -> None: ...
    def client_certificate_store(self, /) -> PySide6.QtWebEngineCore.QWebEngineClientCertificateStore: ...
    def client_hints(self, /) -> PySide6.QtWebEngineCore.QWebEngineClientHints: ...
    def cookie_store(self, /) -> PySide6.QtWebEngineCore.QWebEngineCookieStore: ...
    @staticmethod
    def default_profile() -> PySide6.QtWebEngineCore.QWebEngineProfile: ...
    def download_path(self, /) -> str: ...
    def http_accept_language(self, /) -> str: ...
    def http_cache_maximum_size(self, /) -> int: ...
    def http_cache_type(self, /) -> PySide6.QtWebEngineCore.QWebEngineProfile.HttpCacheType: ...
    def http_user_agent(self, /) -> str: ...
    def install_url_scheme_handler(self, scheme: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, arg__2: PySide6.QtWebEngineCore.QWebEngineUrlSchemeHandler, /) -> None: ...
    def is_off_the_record(self, /) -> bool: ...
    def is_push_service_enabled(self, /) -> bool: ...
    def is_spell_check_enabled(self, /) -> bool: ...
    def list_all_permissions(self, /) -> typing.List[PySide6.QtWebEngineCore.QWebEnginePermission]: ...
    def list_permissions_for_origin(self, securityOrigin: PySide6.QtCore.QUrl | str, /) -> typing.List[PySide6.QtWebEngineCore.QWebEnginePermission]: ...
    def list_permissions_for_permission_type(self, permissionType: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType, /) -> typing.List[PySide6.QtWebEngineCore.QWebEnginePermission]: ...
    def persistent_cookies_policy(self, /) -> PySide6.QtWebEngineCore.QWebEngineProfile.PersistentCookiesPolicy: ...
    def persistent_permissions_policy(self, /) -> PySide6.QtWebEngineCore.QWebEngineProfile.PersistentPermissionsPolicy: ...
    def persistent_storage_path(self, /) -> str: ...
    def query_permission(self, securityOrigin: PySide6.QtCore.QUrl | str, permissionType: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType, /) -> PySide6.QtWebEngineCore.QWebEnginePermission: ...
    def remove_all_url_scheme_handlers(self, /) -> None: ...
    def remove_url_scheme(self, scheme: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def remove_url_scheme_handler(self, arg__1: PySide6.QtWebEngineCore.QWebEngineUrlSchemeHandler, /) -> None: ...
    def scripts(self, /) -> PySide6.QtWebEngineCore.QWebEngineScriptCollection: ...
    def set_cache_path(self, path: str, /) -> None: ...
    def set_download_path(self, path: str, /) -> None: ...
    def set_http_accept_language(self, httpAcceptLanguage: str, /) -> None: ...
    def set_http_cache_maximum_size(self, maxSize: int, /) -> None: ...
    def set_http_cache_type(self, arg__1: PySide6.QtWebEngineCore.QWebEngineProfile.HttpCacheType, /) -> None: ...
    def set_http_user_agent(self, userAgent: str, /) -> None: ...
    def set_notification_presenter(self, notificationPresenter: collections.abc.Callable[..., typing.Any], /) -> None: ...
    def set_persistent_cookies_policy(self, arg__1: PySide6.QtWebEngineCore.QWebEngineProfile.PersistentCookiesPolicy, /) -> None: ...
    def set_persistent_permissions_policy(self, arg__1: PySide6.QtWebEngineCore.QWebEngineProfile.PersistentPermissionsPolicy, /) -> None: ...
    def set_persistent_storage_path(self, path: str, /) -> None: ...
    def set_push_service_enabled(self, enabled: bool, /) -> None: ...
    def set_spell_check_enabled(self, enabled: bool, /) -> None: ...
    def set_spell_check_languages(self, languages: collections.abc.Sequence[str], /) -> None: ...
    def set_url_request_interceptor(self, interceptor: PySide6.QtWebEngineCore.QWebEngineUrlRequestInterceptor, /) -> None: ...
    def settings(self, /) -> PySide6.QtWebEngineCore.QWebEngineSettings: ...
    def spell_check_languages(self, /) -> typing.List[str]: ...
    def storage_name(self, /) -> str: ...
    def url_scheme_handler(self, arg__1: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> PySide6.QtWebEngineCore.QWebEngineUrlSchemeHandler: ...
    def visited_links_contains_url(self, url: PySide6.QtCore.QUrl | str, /) -> bool: ...


class QWebEngineQuotaRequest(Shiboken.Object):

    def __init__(self, /, *, origin: PySide6.QtCore.QUrl | None = ..., requested_size: int | None = ...) -> None: ...

    def __eq__(self, arg__1: PySide6.QtWebEngineCore.QWebEngineQuotaRequest, /) -> bool: ...
    def __ne__(self, arg__1: PySide6.QtWebEngineCore.QWebEngineQuotaRequest, /) -> bool: ...
    def accept(self, /) -> None: ...
    def origin(self, /) -> PySide6.QtCore.QUrl: ...
    def reject(self, /) -> None: ...
    def requested_size(self, /) -> int: ...


class QWebEngineRegisterProtocolHandlerRequest(Shiboken.Object):

    def __init__(self, /, *, origin: PySide6.QtCore.QUrl | None = ..., scheme: str | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, that: PySide6.QtWebEngineCore.QWebEngineRegisterProtocolHandlerRequest, /) -> bool: ...
    def __ne__(self, that: PySide6.QtWebEngineCore.QWebEngineRegisterProtocolHandlerRequest, /) -> bool: ...
    def accept(self, /) -> None: ...
    def origin(self, /) -> PySide6.QtCore.QUrl: ...
    def reject(self, /) -> None: ...
    def scheme(self, /) -> str: ...


class QWebEngineScript(Shiboken.Object):

    class InjectionPoint(enum.Enum):

        Deferred                  = ...  # 0x0
        DocumentReady             = ...  # 0x1
        DocumentCreation          = ...  # 0x2

    class ScriptWorldId(enum.IntEnum):

        MainWorld                 = ...  # 0x0
        ApplicationWorld          = ...  # 0x1
        UserWorld                 = ...  # 0x2


    @typing.overload
    def __init__(self, other: PySide6.QtWebEngineCore.QWebEngineScript, /, *, name: str | None = ..., source_url: PySide6.QtCore.QUrl | None = ..., source_code: str | None = ..., injection_point: PySide6.QtWebEngineCore.QWebEngineScript.InjectionPoint | None = ..., world_id: int | None = ..., runs_on_sub_frames: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, name: str | None = ..., source_url: PySide6.QtCore.QUrl | None = ..., source_code: str | None = ..., injection_point: PySide6.QtWebEngineCore.QWebEngineScript.InjectionPoint | None = ..., world_id: int | None = ..., runs_on_sub_frames: bool | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtWebEngineCore.QWebEngineScript, /) -> bool: ...
    def __ne__(self, other: PySide6.QtWebEngineCore.QWebEngineScript, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def injection_point(self, /) -> PySide6.QtWebEngineCore.QWebEngineScript.InjectionPoint: ...
    def name(self, /) -> str: ...
    def runs_on_sub_frames(self, /) -> bool: ...
    def set_injection_point(self, arg__1: PySide6.QtWebEngineCore.QWebEngineScript.InjectionPoint, /) -> None: ...
    def set_name(self, arg__1: str, /) -> None: ...
    def set_runs_on_sub_frames(self, on: bool, /) -> None: ...
    def set_source_code(self, arg__1: str, /) -> None: ...
    def set_source_url(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_world_id(self, arg__1: int, /) -> None: ...
    def source_code(self, /) -> str: ...
    def source_url(self, /) -> PySide6.QtCore.QUrl: ...
    def swap(self, other: PySide6.QtWebEngineCore.QWebEngineScript, /) -> None: ...
    def world_id(self, /) -> int: ...


class QWebEngineScriptCollection(Shiboken.Object):
    def clear(self, /) -> None: ...
    def contains(self, value: PySide6.QtWebEngineCore.QWebEngineScript, /) -> bool: ...
    def count(self, /) -> int: ...
    def find(self, name: str, /) -> typing.List[PySide6.QtWebEngineCore.QWebEngineScript]: ...
    @typing.overload
    def insert(self, arg__1: PySide6.QtWebEngineCore.QWebEngineScript, /) -> None: ...
    @typing.overload
    def insert(self, list: collections.abc.Sequence[PySide6.QtWebEngineCore.QWebEngineScript], /) -> None: ...
    def is_empty(self, /) -> bool: ...
    def remove(self, arg__1: PySide6.QtWebEngineCore.QWebEngineScript, /) -> bool: ...
    def to_list(self, /) -> typing.List[PySide6.QtWebEngineCore.QWebEngineScript]: ...


class QWebEngineSettings(Shiboken.Object):

    class FontFamily(enum.Enum):

        StandardFont              = ...  # 0x0
        FixedFont                 = ...  # 0x1
        SerifFont                 = ...  # 0x2
        SansSerifFont             = ...  # 0x3
        CursiveFont               = ...  # 0x4
        FantasyFont               = ...  # 0x5
        PictographFont            = ...  # 0x6

    class FontSize(enum.Enum):

        MinimumFontSize           = ...  # 0x0
        MinimumLogicalFontSize    = ...  # 0x1
        DefaultFontSize           = ...  # 0x2
        DefaultFixedFontSize      = ...  # 0x3

    class ImageAnimationPolicy(enum.Enum):

        Inherited                 = ...  # 0x0
        Allow                     = ...  # 0x1
        AnimateOnce               = ...  # 0x2
        Disallow                  = ...  # 0x3

    class UnknownUrlSchemePolicy(enum.Enum):

        InheritedUnknownUrlSchemePolicy = ...  # 0x0
        DisallowUnknownUrlSchemes = ...  # 0x1
        AllowUnknownUrlSchemesFromUserInteraction = ...  # 0x2
        AllowAllUnknownUrlSchemes = ...  # 0x3

    class WebAttribute(enum.Enum):

        AutoLoadImages            = ...  # 0x0
        JavascriptEnabled         = ...  # 0x1
        JavascriptCanOpenWindows  = ...  # 0x2
        JavascriptCanAccessClipboard = ...  # 0x3
        LinksIncludedInFocusChain = ...  # 0x4
        LocalStorageEnabled       = ...  # 0x5
        LocalContentCanAccessRemoteUrls = ...  # 0x6
        XSSAuditingEnabled        = ...  # 0x7
        SpatialNavigationEnabled  = ...  # 0x8
        LocalContentCanAccessFileUrls = ...  # 0x9
        HyperlinkAuditingEnabled  = ...  # 0xa
        ScrollAnimatorEnabled     = ...  # 0xb
        ErrorPageEnabled          = ...  # 0xc
        PluginsEnabled            = ...  # 0xd
        FullScreenSupportEnabled  = ...  # 0xe
        ScreenCaptureEnabled      = ...  # 0xf
        WebGLEnabled              = ...  # 0x10
        Accelerated2dCanvasEnabled = ...  # 0x11
        AutoLoadIconsForPage      = ...  # 0x12
        TouchIconsEnabled         = ...  # 0x13
        FocusOnNavigationEnabled  = ...  # 0x14
        PrintElementBackgrounds   = ...  # 0x15
        AllowRunningInsecureContent = ...  # 0x16
        AllowGeolocationOnInsecureOrigins = ...  # 0x17
        AllowWindowActivationFromJavaScript = ...  # 0x18
        ShowScrollBars            = ...  # 0x19
        PlaybackRequiresUserGesture = ...  # 0x1a
        WebRTCPublicInterfacesOnly = ...  # 0x1b
        JavascriptCanPaste        = ...  # 0x1c
        DnsPrefetchEnabled        = ...  # 0x1d
        PdfViewerEnabled          = ...  # 0x1e
        NavigateOnDropEnabled     = ...  # 0x1f
        ReadingFromCanvasEnabled  = ...  # 0x20
        ForceDarkMode             = ...  # 0x21


    def default_text_encoding(self, /) -> str: ...
    def font_family(self, which: PySide6.QtWebEngineCore.QWebEngineSettings.FontFamily, /) -> str: ...
    def font_size(self, type: PySide6.QtWebEngineCore.QWebEngineSettings.FontSize, /) -> int: ...
    def image_animation_policy(self, /) -> PySide6.QtWebEngineCore.QWebEngineSettings.ImageAnimationPolicy: ...
    def reset_attribute(self, attr: PySide6.QtWebEngineCore.QWebEngineSettings.WebAttribute, /) -> None: ...
    def reset_font_family(self, which: PySide6.QtWebEngineCore.QWebEngineSettings.FontFamily, /) -> None: ...
    def reset_font_size(self, type: PySide6.QtWebEngineCore.QWebEngineSettings.FontSize, /) -> None: ...
    def reset_image_animation_policy(self, /) -> None: ...
    def reset_unknown_url_scheme_policy(self, /) -> None: ...
    def set_attribute(self, attr: PySide6.QtWebEngineCore.QWebEngineSettings.WebAttribute, on: bool, /) -> None: ...
    def set_default_text_encoding(self, encoding: str, /) -> None: ...
    def set_font_family(self, which: PySide6.QtWebEngineCore.QWebEngineSettings.FontFamily, family: str, /) -> None: ...
    def set_font_size(self, type: PySide6.QtWebEngineCore.QWebEngineSettings.FontSize, size: int, /) -> None: ...
    def set_image_animation_policy(self, policy: PySide6.QtWebEngineCore.QWebEngineSettings.ImageAnimationPolicy, /) -> None: ...
    def set_unknown_url_scheme_policy(self, policy: PySide6.QtWebEngineCore.QWebEngineSettings.UnknownUrlSchemePolicy, /) -> None: ...
    def test_attribute(self, attr: PySide6.QtWebEngineCore.QWebEngineSettings.WebAttribute, /) -> bool: ...
    def unknown_url_scheme_policy(self, /) -> PySide6.QtWebEngineCore.QWebEngineSettings.UnknownUrlSchemePolicy: ...


class QWebEngineUrlRequestInfo(Shiboken.Object):

    class NavigationType(enum.Enum):

        NavigationTypeLink        = ...  # 0x0
        NavigationTypeTyped       = ...  # 0x1
        NavigationTypeFormSubmitted = ...  # 0x2
        NavigationTypeBackForward = ...  # 0x3
        NavigationTypeReload      = ...  # 0x4
        NavigationTypeOther       = ...  # 0x5
        NavigationTypeRedirect    = ...  # 0x6

    class ResourceType(enum.Enum):

        ResourceTypeMainFrame     = ...  # 0x0
        ResourceTypeSubFrame      = ...  # 0x1
        ResourceTypeStylesheet    = ...  # 0x2
        ResourceTypeScript        = ...  # 0x3
        ResourceTypeImage         = ...  # 0x4
        ResourceTypeFontResource  = ...  # 0x5
        ResourceTypeSubResource   = ...  # 0x6
        ResourceTypeObject        = ...  # 0x7
        ResourceTypeMedia         = ...  # 0x8
        ResourceTypeWorker        = ...  # 0x9
        ResourceTypeSharedWorker  = ...  # 0xa
        ResourceTypePrefetch      = ...  # 0xb
        ResourceTypeFavicon       = ...  # 0xc
        ResourceTypeXhr           = ...  # 0xd
        ResourceTypePing          = ...  # 0xe
        ResourceTypeServiceWorker = ...  # 0xf
        ResourceTypeCspReport     = ...  # 0x10
        ResourceTypePluginResource = ...  # 0x11
        ResourceTypeNavigationPreloadMainFrame = ...  # 0x13
        ResourceTypeNavigationPreloadSubFrame = ...  # 0x14
        ResourceTypeJson          = ...  # 0x15
        ResourceTypeLast          = ...  # 0x15
        ResourceTypeWebSocket     = ...  # 0xfe
        ResourceTypeUnknown       = ...  # 0xff


    def block(self, shouldBlock: bool, /) -> None: ...
    def changed(self, /) -> bool: ...
    def first_party_url(self, /) -> PySide6.QtCore.QUrl: ...
    def http_headers(self, /) -> typing.Dict[PySide6.QtCore.QByteArray, PySide6.QtCore.QByteArray]: ...
    def initiator(self, /) -> PySide6.QtCore.QUrl: ...
    def navigation_type(self, /) -> PySide6.QtWebEngineCore.QWebEngineUrlRequestInfo.NavigationType: ...
    def redirect(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def request_body(self, /) -> PySide6.QtCore.QIODevice: ...
    def request_method(self, /) -> PySide6.QtCore.QByteArray: ...
    def request_url(self, /) -> PySide6.QtCore.QUrl: ...
    def resource_type(self, /) -> PySide6.QtWebEngineCore.QWebEngineUrlRequestInfo.ResourceType: ...
    def set_http_header(self, name: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, value: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...


class QWebEngineUrlRequestInterceptor(PySide6.QtCore.QObject):

    def __init__(self, /, p: PySide6.QtCore.QObject | None = ...) -> None: ...

    def intercept_request(self, info: PySide6.QtWebEngineCore.QWebEngineUrlRequestInfo, /) -> None: ...


class QWebEngineUrlRequestJob(PySide6.QtCore.QObject):

    class Error(enum.Enum):

        NoError                   = ...  # 0x0
        UrlNotFound               = ...  # 0x1
        UrlInvalid                = ...  # 0x2
        RequestAborted            = ...  # 0x3
        RequestDenied             = ...  # 0x4
        RequestFailed             = ...  # 0x5


    def fail(self, error: PySide6.QtWebEngineCore.QWebEngineUrlRequestJob.Error, /) -> None: ...
    def initiator(self, /) -> PySide6.QtCore.QUrl: ...
    def redirect(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def reply(self, contentType: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def request_body(self, /) -> PySide6.QtCore.QIODevice: ...
    def request_headers(self, /) -> typing.Dict[PySide6.QtCore.QByteArray, PySide6.QtCore.QByteArray]: ...
    def request_method(self, /) -> PySide6.QtCore.QByteArray: ...
    def request_url(self, /) -> PySide6.QtCore.QUrl: ...
    def set_additional_response_headers(self, additionalResponseHeaders: typing.Dict[PySide6.QtCore.QByteArray, PySide6.QtCore.QByteArray], /) -> None: ...


class QWebEngineUrlScheme(Shiboken.Object):

    class Flag(enum.Flag):

        SecureScheme              = ...  # 0x1
        LocalScheme               = ...  # 0x2
        LocalAccessAllowed        = ...  # 0x4
        NoAccessAllowed           = ...  # 0x8
        ServiceWorkersAllowed     = ...  # 0x10
        ViewSourceAllowed         = ...  # 0x20
        ContentSecurityPolicyIgnored = ...  # 0x40
        CorsEnabled               = ...  # 0x80
        FetchApiAllowed           = ...  # 0x100

    class SpecialPort(enum.Enum):

        PortUnspecified           = ...  # -1

    class Syntax(enum.Enum):

        HostPortAndUserInformation = ...  # 0x0
        HostAndPort               = ...  # 0x1
        Host                      = ...  # 0x2
        Path                      = ...  # 0x3


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, that: PySide6.QtWebEngineCore.QWebEngineUrlScheme, /) -> None: ...
    @typing.overload
    def __init__(self, name: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, that: PySide6.QtWebEngineCore.QWebEngineUrlScheme, /) -> bool: ...
    def __ne__(self, that: PySide6.QtWebEngineCore.QWebEngineUrlScheme, /) -> bool: ...
    def default_port(self, /) -> int: ...
    def flags(self, /) -> PySide6.QtWebEngineCore.QWebEngineUrlScheme.Flag: ...
    def name(self, /) -> PySide6.QtCore.QByteArray: ...
    @staticmethod
    def register_scheme(scheme: PySide6.QtWebEngineCore.QWebEngineUrlScheme, /) -> None: ...
    @staticmethod
    def scheme_by_name(name: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> PySide6.QtWebEngineCore.QWebEngineUrlScheme: ...
    def set_default_port(self, newValue: int, /) -> None: ...
    def set_flags(self, newValue: PySide6.QtWebEngineCore.QWebEngineUrlScheme.Flag, /) -> None: ...
    def set_name(self, newValue: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def set_syntax(self, newValue: PySide6.QtWebEngineCore.QWebEngineUrlScheme.Syntax, /) -> None: ...
    def syntax(self, /) -> PySide6.QtWebEngineCore.QWebEngineUrlScheme.Syntax: ...


class QWebEngineUrlSchemeHandler(PySide6.QtCore.QObject):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def request_started(self, arg__1: PySide6.QtWebEngineCore.QWebEngineUrlRequestJob, /) -> None: ...


class QWebEngineWebAuthPinRequest(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, QWebEngineWebAuthPinRequest: PySide6.QtWebEngineCore.QWebEngineWebAuthPinRequest, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...


class QWebEngineWebAuthUxRequest(PySide6.QtCore.QObject):

    stateChanged             : typing.ClassVar[Signal] = ... # stateChanged(QWebEngineWebAuthUxRequest::WebAuthUxState)

    class PinEntryError(enum.Enum):

        NoError                   = ...  # 0x0
        InternalUvLocked          = ...  # 0x1
        WrongPin                  = ...  # 0x2
        TooShort                  = ...  # 0x3
        InvalidCharacters         = ...  # 0x4
        SameAsCurrentPin          = ...  # 0x5

    class PinEntryReason(enum.Enum):

        Set                       = ...  # 0x0
        Change                    = ...  # 0x1
        Challenge                 = ...  # 0x2

    class RequestFailureReason(enum.Enum):

        Timeout                   = ...  # 0x0
        KeyNotRegistered          = ...  # 0x1
        KeyAlreadyRegistered      = ...  # 0x2
        SoftPinBlock              = ...  # 0x3
        HardPinBlock              = ...  # 0x4
        AuthenticatorRemovedDuringPinEntry = ...  # 0x5
        AuthenticatorMissingResidentKeys = ...  # 0x6
        AuthenticatorMissingUserVerification = ...  # 0x7
        AuthenticatorMissingLargeBlob = ...  # 0x8
        NoCommonAlgorithms        = ...  # 0x9
        StorageFull               = ...  # 0xa
        UserConsentDenied         = ...  # 0xb
        WinUserCancelled          = ...  # 0xc

    class WebAuthUxState(enum.Enum):

        NotStarted                = ...  # 0x0
        SelectAccount             = ...  # 0x1
        CollectPin                = ...  # 0x2
        FinishTokenCollection     = ...  # 0x3
        RequestFailed             = ...  # 0x4
        Cancelled                 = ...  # 0x5
        Completed                 = ...  # 0x6


    def cancel(self, /) -> None: ...
    def pin_request(self, /) -> PySide6.QtWebEngineCore.QWebEngineWebAuthPinRequest: ...
    def relying_party_id(self, /) -> str: ...
    def request_failure_reason(self, /) -> PySide6.QtWebEngineCore.QWebEngineWebAuthUxRequest.RequestFailureReason: ...
    def retry(self, /) -> None: ...
    def set_pin(self, pin: str, /) -> None: ...
    def set_selected_account(self, selectedAccount: str, /) -> None: ...
    def state(self, /) -> PySide6.QtWebEngineCore.QWebEngineWebAuthUxRequest.WebAuthUxState: ...
    def user_names(self, /) -> typing.List[str]: ...


def qWebEngineChromiumSecurityPatchVersion() -> typing.Union[bytes, bytearray, memoryview]: ...
def qWebEngineChromiumVersion() -> typing.Union[bytes, bytearray, memoryview]: ...
def qWebEngineVersion() -> typing.Union[bytes, bytearray, memoryview]: ...


# eof
