# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtSpatialAudio, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtSpatialAudio`

import PySide6.QtSpatialAudio
import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtMultimedia

import enum
import typing
from PySide6.QtCore import Signal


class QAmbientSound(PySide6.QtCore.QObject):

    autoPlayChanged          : typing.ClassVar[Signal] = ... # autoPlayChanged()
    loopsChanged             : typing.ClassVar[Signal] = ... # loopsChanged()
    sourceChanged            : typing.ClassVar[Signal] = ... # sourceChanged()
    volumeChanged            : typing.ClassVar[Signal] = ... # volumeChanged()

    class Loops(enum.IntEnum):

        Infinite                  = ...  # -1
        Once                      = ...  # 0x1


    def __init__(self, engine: PySide6.QtSpatialAudio.QAudioEngine, /, *, source: PySide6.QtCore.QUrl | None = ..., volume: float | None = ..., loops: int | None = ..., auto_play: bool | None = ...) -> None: ...

    def auto_play(self, /) -> bool: ...
    def engine(self, /) -> PySide6.QtSpatialAudio.QAudioEngine: ...
    def loops(self, /) -> int: ...
    def pause(self, /) -> None: ...
    def play(self, /) -> None: ...
    def set_auto_play(self, autoPlay: bool, /) -> None: ...
    def set_loops(self, loops: int, /) -> None: ...
    def set_source(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_volume(self, volume: float, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def stop(self, /) -> None: ...
    def volume(self, /) -> float: ...


class QAudioEngine(PySide6.QtCore.QObject):

    distanceScaleChanged     : typing.ClassVar[Signal] = ... # distanceScaleChanged()
    masterVolumeChanged      : typing.ClassVar[Signal] = ... # masterVolumeChanged()
    outputDeviceChanged      : typing.ClassVar[Signal] = ... # outputDeviceChanged()
    outputModeChanged        : typing.ClassVar[Signal] = ... # outputModeChanged()
    pausedChanged            : typing.ClassVar[Signal] = ... # pausedChanged()

    class OutputMode(enum.Enum):

        Surround                  = ...  # 0x0
        Stereo                    = ...  # 0x1
        Headphone                 = ...  # 0x2


    @typing.overload
    def __init__(self, parent: PySide6.QtCore.QObject, /, *, output_mode: PySide6.QtSpatialAudio.QAudioEngine.OutputMode | None = ..., output_device: PySide6.QtMultimedia.QAudioDevice | None = ..., master_volume: float | None = ..., paused: bool | None = ..., distance_scale: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, output_mode: PySide6.QtSpatialAudio.QAudioEngine.OutputMode | None = ..., output_device: PySide6.QtMultimedia.QAudioDevice | None = ..., master_volume: float | None = ..., paused: bool | None = ..., distance_scale: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, sampleRate: int, /, parent: PySide6.QtCore.QObject | None = ..., *, output_mode: PySide6.QtSpatialAudio.QAudioEngine.OutputMode | None = ..., output_device: PySide6.QtMultimedia.QAudioDevice | None = ..., master_volume: float | None = ..., paused: bool | None = ..., distance_scale: float | None = ...) -> None: ...

    def distance_scale(self, /) -> float: ...
    def master_volume(self, /) -> float: ...
    def output_device(self, /) -> PySide6.QtMultimedia.QAudioDevice: ...
    def output_mode(self, /) -> PySide6.QtSpatialAudio.QAudioEngine.OutputMode: ...
    def pause(self, /) -> None: ...
    def paused(self, /) -> bool: ...
    def resume(self, /) -> None: ...
    def room_effects_enabled(self, /) -> bool: ...
    def sample_rate(self, /) -> int: ...
    def set_distance_scale(self, scale: float, /) -> None: ...
    def set_master_volume(self, volume: float, /) -> None: ...
    def set_output_device(self, device: PySide6.QtMultimedia.QAudioDevice, /) -> None: ...
    def set_output_mode(self, mode: PySide6.QtSpatialAudio.QAudioEngine.OutputMode, /) -> None: ...
    def set_paused(self, paused: bool, /) -> None: ...
    def set_room_effects_enabled(self, enabled: bool, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...


class QAudioListener(PySide6.QtCore.QObject):

    def __init__(self, engine: PySide6.QtSpatialAudio.QAudioEngine, /) -> None: ...

    def engine(self, /) -> PySide6.QtSpatialAudio.QAudioEngine: ...
    def position(self, /) -> PySide6.QtGui.QVector3D: ...
    def rotation(self, /) -> PySide6.QtGui.QQuaternion: ...
    def set_position(self, pos: PySide6.QtGui.QVector3D, /) -> None: ...
    def set_rotation(self, q: PySide6.QtGui.QQuaternion, /) -> None: ...


class QAudioRoom(PySide6.QtCore.QObject):

    dimensionsChanged        : typing.ClassVar[Signal] = ... # dimensionsChanged()
    positionChanged          : typing.ClassVar[Signal] = ... # positionChanged()
    reflectionGainChanged    : typing.ClassVar[Signal] = ... # reflectionGainChanged()
    reverbBrightnessChanged  : typing.ClassVar[Signal] = ... # reverbBrightnessChanged()
    reverbGainChanged        : typing.ClassVar[Signal] = ... # reverbGainChanged()
    reverbTimeChanged        : typing.ClassVar[Signal] = ... # reverbTimeChanged()
    rotationChanged          : typing.ClassVar[Signal] = ... # rotationChanged()
    wallsChanged             : typing.ClassVar[Signal] = ... # wallsChanged()

    class Material(enum.Enum):

        Transparent               = ...  # 0x0
        AcousticCeilingTiles      = ...  # 0x1
        BrickBare                 = ...  # 0x2
        BrickPainted              = ...  # 0x3
        ConcreteBlockCoarse       = ...  # 0x4
        ConcreteBlockPainted      = ...  # 0x5
        CurtainHeavy              = ...  # 0x6
        FiberGlassInsulation      = ...  # 0x7
        GlassThin                 = ...  # 0x8
        GlassThick                = ...  # 0x9
        Grass                     = ...  # 0xa
        LinoleumOnConcrete        = ...  # 0xb
        Marble                    = ...  # 0xc
        Metal                     = ...  # 0xd
        ParquetOnConcrete         = ...  # 0xe
        PlasterRough              = ...  # 0xf
        PlasterSmooth             = ...  # 0x10
        PlywoodPanel              = ...  # 0x11
        PolishedConcreteOrTile    = ...  # 0x12
        Sheetrock                 = ...  # 0x13
        WaterOrIceSurface         = ...  # 0x14
        WoodCeiling               = ...  # 0x15
        WoodPanel                 = ...  # 0x16
        UniformMaterial           = ...  # 0x17

    class Wall(enum.Enum):

        LeftWall                  = ...  # 0x0
        RightWall                 = ...  # 0x1
        Floor                     = ...  # 0x2
        Ceiling                   = ...  # 0x3
        FrontWall                 = ...  # 0x4
        BackWall                  = ...  # 0x5


    def __init__(self, engine: PySide6.QtSpatialAudio.QAudioEngine, /, *, position: PySide6.QtGui.QVector3D | None = ..., dimensions: PySide6.QtGui.QVector3D | None = ..., rotation: PySide6.QtGui.QQuaternion | None = ..., reflection_gain: float | None = ..., reverb_gain: float | None = ..., reverb_time: float | None = ..., reverb_brightness: float | None = ...) -> None: ...

    def dimensions(self, /) -> PySide6.QtGui.QVector3D: ...
    def position(self, /) -> PySide6.QtGui.QVector3D: ...
    def reflection_gain(self, /) -> float: ...
    def reverb_brightness(self, /) -> float: ...
    def reverb_gain(self, /) -> float: ...
    def reverb_time(self, /) -> float: ...
    def rotation(self, /) -> PySide6.QtGui.QQuaternion: ...
    def set_dimensions(self, dim: PySide6.QtGui.QVector3D, /) -> None: ...
    def set_position(self, pos: PySide6.QtGui.QVector3D, /) -> None: ...
    def set_reflection_gain(self, factor: float, /) -> None: ...
    def set_reverb_brightness(self, factor: float, /) -> None: ...
    def set_reverb_gain(self, factor: float, /) -> None: ...
    def set_reverb_time(self, factor: float, /) -> None: ...
    def set_rotation(self, q: PySide6.QtGui.QQuaternion, /) -> None: ...
    def set_wall_material(self, wall: PySide6.QtSpatialAudio.QAudioRoom.Wall, material: PySide6.QtSpatialAudio.QAudioRoom.Material, /) -> None: ...
    def wall_material(self, wall: PySide6.QtSpatialAudio.QAudioRoom.Wall, /) -> PySide6.QtSpatialAudio.QAudioRoom.Material: ...


class QIntList: ...


class QSpatialSound(PySide6.QtCore.QObject):

    autoPlayChanged          : typing.ClassVar[Signal] = ... # autoPlayChanged()
    directivityChanged       : typing.ClassVar[Signal] = ... # directivityChanged()
    directivityOrderChanged  : typing.ClassVar[Signal] = ... # directivityOrderChanged()
    distanceCutoffChanged    : typing.ClassVar[Signal] = ... # distanceCutoffChanged()
    distanceModelChanged     : typing.ClassVar[Signal] = ... # distanceModelChanged()
    loopsChanged             : typing.ClassVar[Signal] = ... # loopsChanged()
    manualAttenuationChanged : typing.ClassVar[Signal] = ... # manualAttenuationChanged()
    nearFieldGainChanged     : typing.ClassVar[Signal] = ... # nearFieldGainChanged()
    occlusionIntensityChanged: typing.ClassVar[Signal] = ... # occlusionIntensityChanged()
    positionChanged          : typing.ClassVar[Signal] = ... # positionChanged()
    rotationChanged          : typing.ClassVar[Signal] = ... # rotationChanged()
    sizeChanged              : typing.ClassVar[Signal] = ... # sizeChanged()
    sourceChanged            : typing.ClassVar[Signal] = ... # sourceChanged()
    volumeChanged            : typing.ClassVar[Signal] = ... # volumeChanged()

    class DistanceModel(enum.Enum):

        Logarithmic               = ...  # 0x0
        Linear                    = ...  # 0x1
        ManualAttenuation         = ...  # 0x2

    class Loops(enum.IntEnum):

        Infinite                  = ...  # -1
        Once                      = ...  # 0x1


    def __init__(self, engine: PySide6.QtSpatialAudio.QAudioEngine, /, *, source: PySide6.QtCore.QUrl | None = ..., position: PySide6.QtGui.QVector3D | None = ..., rotation: PySide6.QtGui.QQuaternion | None = ..., volume: float | None = ..., distance_model: PySide6.QtSpatialAudio.QSpatialSound.DistanceModel | None = ..., size: float | None = ..., distance_cutoff: float | None = ..., manual_attenuation: float | None = ..., occlusion_intensity: float | None = ..., directivity: float | None = ..., directivity_order: float | None = ..., near_field_gain: float | None = ..., loops: int | None = ..., auto_play: bool | None = ...) -> None: ...

    def auto_play(self, /) -> bool: ...
    def directivity(self, /) -> float: ...
    def directivity_order(self, /) -> float: ...
    def distance_cutoff(self, /) -> float: ...
    def distance_model(self, /) -> PySide6.QtSpatialAudio.QSpatialSound.DistanceModel: ...
    def engine(self, /) -> PySide6.QtSpatialAudio.QAudioEngine: ...
    def loops(self, /) -> int: ...
    def manual_attenuation(self, /) -> float: ...
    def near_field_gain(self, /) -> float: ...
    def occlusion_intensity(self, /) -> float: ...
    def pause(self, /) -> None: ...
    def play(self, /) -> None: ...
    def position(self, /) -> PySide6.QtGui.QVector3D: ...
    def rotation(self, /) -> PySide6.QtGui.QQuaternion: ...
    def set_auto_play(self, autoPlay: bool, /) -> None: ...
    def set_directivity(self, alpha: float, /) -> None: ...
    def set_directivity_order(self, alpha: float, /) -> None: ...
    def set_distance_cutoff(self, cutoff: float, /) -> None: ...
    def set_distance_model(self, model: PySide6.QtSpatialAudio.QSpatialSound.DistanceModel, /) -> None: ...
    def set_loops(self, loops: int, /) -> None: ...
    def set_manual_attenuation(self, attenuation: float, /) -> None: ...
    def set_near_field_gain(self, gain: float, /) -> None: ...
    def set_occlusion_intensity(self, occlusion: float, /) -> None: ...
    def set_position(self, pos: PySide6.QtGui.QVector3D, /) -> None: ...
    def set_rotation(self, q: PySide6.QtGui.QQuaternion, /) -> None: ...
    def set_size(self, size: float, /) -> None: ...
    def set_source(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def set_volume(self, volume: float, /) -> None: ...
    def size(self, /) -> float: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def stop(self, /) -> None: ...
    def volume(self, /) -> float: ...


# eof
