# Generated by Django 4.2.14 on 2025-03-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatedpersons', '0002_relatedperson_communication_relatedperson_gender'),
        ('practitioners', '0010_practitionerrole_endpoint'),
        ('organizations', '0003_organization_endpoint'),
        ('base', '0015_rename_signaturewhenreference_signaturewhoreference'),
        ('devices', '0007_alter_device_status_and_more'),
        ('groups', '0004_group_code_group_combination_method_and_more'),
        ('patients', '0007_patientorganizationreference'),
        ('contracts', '0006_remove_contracttermactionsubject_reference_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractTermOfferPartyReference',
            new_name='ContractTermOfferPartyReferenceReference',
        ),
        migrations.RemoveField(
            model_name='contracttermofferanswer',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='contracttermofferanswer',
            name='security_label_number',
        ),
        migrations.RemoveField(
            model_name='contracttermofferanswer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='contracttermofferparty',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='contracttermsecuritylabel',
            name='number',
        ),
        migrations.AddField(
            model_name='contracttermactionrequesterreference',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_term_action_requester_reference_device', to='devices.device'),
        ),
    ]
