
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-10T16:58:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "53a69cc916081c47d42fb208bb0eb77b2258a109",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
