# Generated by Django 4.2.14 on 2025-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_communication'),
        ('practitioners', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitionertelecom',
            name='practitioner',
        ),
        migrations.RenameField(
            model_name='practitioner',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='deceased',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='practitioner',
            name='communication',
            field=models.ManyToManyField(blank=True, related_name='practitioner_communication', to='base.communication'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='deceased_boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='identifier',
            field=models.ManyToManyField(blank=True, related_name='practitioner_identifier', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='practitioner_name', to='base.humanname'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='practitioner_photo', to='base.attachment'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='telecom',
            field=models.ManyToManyField(blank=True, related_name='practitioner_telecom', to='base.contactpoint'),
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='PractitionerTelecom',
        ),
    ]
