# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtWebEngineQuick, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtWebEngineQuick`

import PySide6.QtWebEngineQuick
import PySide6.QtCore
import PySide6.QtWebEngineCore

import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QIntList: ...


class QQuickWebEngineProfile(PySide6.QtCore.QObject):

    cachePathChanged         : typing.ClassVar[Signal] = ... # cachePathChanged()
    clearHttpCacheCompleted  : typing.ClassVar[Signal] = ... # clearHttpCacheCompleted()
    downloadFinished         : typing.ClassVar[Signal] = ... # downloadFinished(QQuickWebEngineDownloadRequest*)
    downloadPathChanged      : typing.ClassVar[Signal] = ... # downloadPathChanged()
    downloadRequested        : typing.ClassVar[Signal] = ... # downloadRequested(QQuickWebEngineDownloadRequest*)
    httpAcceptLanguageChanged: typing.ClassVar[Signal] = ... # httpAcceptLanguageChanged()
    httpCacheMaximumSizeChanged: typing.ClassVar[Signal] = ... # httpCacheMaximumSizeChanged()
    httpCacheTypeChanged     : typing.ClassVar[Signal] = ... # httpCacheTypeChanged()
    httpUserAgentChanged     : typing.ClassVar[Signal] = ... # httpUserAgentChanged()
    offTheRecordChanged      : typing.ClassVar[Signal] = ... # offTheRecordChanged()
    persistentCookiesPolicyChanged: typing.ClassVar[Signal] = ... # persistentCookiesPolicyChanged()
    persistentPermissionsPolicyChanged: typing.ClassVar[Signal] = ... # persistentPermissionsPolicyChanged()
    persistentStoragePathChanged: typing.ClassVar[Signal] = ... # persistentStoragePathChanged()
    presentNotification      : typing.ClassVar[Signal] = ... # presentNotification(QWebEngineNotification*)
    pushServiceEnabledChanged: typing.ClassVar[Signal] = ... # pushServiceEnabledChanged()
    spellCheckEnabledChanged : typing.ClassVar[Signal] = ... # spellCheckEnabledChanged()
    spellCheckLanguagesChanged: typing.ClassVar[Signal] = ... # spellCheckLanguagesChanged()
    storageNameChanged       : typing.ClassVar[Signal] = ... # storageNameChanged()

    class HttpCacheType(enum.Enum):

        MemoryHttpCache           = ...  # 0x0
        DiskHttpCache             = ...  # 0x1
        NoCache                   = ...  # 0x2

    class PersistentCookiesPolicy(enum.Enum):

        NoPersistentCookies       = ...  # 0x0
        AllowPersistentCookies    = ...  # 0x1
        ForcePersistentCookies    = ...  # 0x2

    class PersistentPermissionsPolicy(enum.Enum):

        AskEveryTime              = ...  # 0x0
        StoreInMemory             = ...  # 0x1
        StoreOnDisk               = ...  # 0x2


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, storage_name: str | None = ..., off_the_record: bool | None = ..., persistent_storage_path: str | None = ..., cache_path: str | None = ..., http_user_agent: str | None = ..., http_cache_type: PySide6.QtWebEngineQuick.QQuickWebEngineProfile.HttpCacheType | None = ..., http_accept_language: str | None = ..., persistent_cookies_policy: PySide6.QtWebEngineQuick.QQuickWebEngineProfile.PersistentCookiesPolicy | None = ..., persistent_permissions_policy: PySide6.QtWebEngineQuick.QQuickWebEngineProfile.PersistentPermissionsPolicy | None = ..., http_cache_maximum_size: int | None = ..., spell_check_languages: collections.abc.Sequence[str] | None = ..., spell_check_enabled: bool | None = ..., download_path: str | None = ..., is_push_service_enabled: bool | None = ..., client_hints: PySide6.QtWebEngineCore.QWebEngineClientHints | None = ...) -> None: ...

    def cache_path(self, /) -> str: ...
    def clear_http_cache(self, /) -> None: ...
    def client_certificate_store(self, /) -> PySide6.QtWebEngineCore.QWebEngineClientCertificateStore: ...
    def client_hints(self, /) -> PySide6.QtWebEngineCore.QWebEngineClientHints: ...
    def cookie_store(self, /) -> PySide6.QtWebEngineCore.QWebEngineCookieStore: ...
    @staticmethod
    def default_profile() -> PySide6.QtWebEngineQuick.QQuickWebEngineProfile: ...
    def download_path(self, /) -> str: ...
    def http_accept_language(self, /) -> str: ...
    def http_cache_maximum_size(self, /) -> int: ...
    def http_cache_type(self, /) -> PySide6.QtWebEngineQuick.QQuickWebEngineProfile.HttpCacheType: ...
    def http_user_agent(self, /) -> str: ...
    def install_url_scheme_handler(self, scheme: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, arg__2: PySide6.QtWebEngineCore.QWebEngineUrlSchemeHandler, /) -> None: ...
    def is_off_the_record(self, /) -> bool: ...
    def is_push_service_enabled(self, /) -> bool: ...
    def is_spell_check_enabled(self, /) -> bool: ...
    def list_all_permissions(self, /) -> typing.List[PySide6.QtWebEngineCore.QWebEnginePermission]: ...
    def list_permissions_for_origin(self, securityOrigin: PySide6.QtCore.QUrl | str, /) -> typing.List[PySide6.QtWebEngineCore.QWebEnginePermission]: ...
    def list_permissions_for_permission_type(self, permissionType: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType, /) -> typing.List[PySide6.QtWebEngineCore.QWebEnginePermission]: ...
    def persistent_cookies_policy(self, /) -> PySide6.QtWebEngineQuick.QQuickWebEngineProfile.PersistentCookiesPolicy: ...
    def persistent_permissions_policy(self, /) -> PySide6.QtWebEngineQuick.QQuickWebEngineProfile.PersistentPermissionsPolicy: ...
    def persistent_storage_path(self, /) -> str: ...
    def query_permission(self, securityOrigin: PySide6.QtCore.QUrl | str, permissionType: PySide6.QtWebEngineCore.QWebEnginePermission.PermissionType, /) -> PySide6.QtWebEngineCore.QWebEnginePermission: ...
    def remove_all_url_scheme_handlers(self, /) -> None: ...
    def remove_url_scheme(self, scheme: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def remove_url_scheme_handler(self, arg__1: PySide6.QtWebEngineCore.QWebEngineUrlSchemeHandler, /) -> None: ...
    def set_cache_path(self, path: str, /) -> None: ...
    def set_download_path(self, path: str, /) -> None: ...
    def set_http_accept_language(self, httpAcceptLanguage: str, /) -> None: ...
    def set_http_cache_maximum_size(self, maxSize: int, /) -> None: ...
    def set_http_cache_type(self, arg__1: PySide6.QtWebEngineQuick.QQuickWebEngineProfile.HttpCacheType, /) -> None: ...
    def set_http_user_agent(self, userAgent: str, /) -> None: ...
    def set_off_the_record(self, offTheRecord: bool, /) -> None: ...
    def set_persistent_cookies_policy(self, arg__1: PySide6.QtWebEngineQuick.QQuickWebEngineProfile.PersistentCookiesPolicy, /) -> None: ...
    def set_persistent_permissions_policy(self, arg__1: PySide6.QtWebEngineQuick.QQuickWebEngineProfile.PersistentPermissionsPolicy, /) -> None: ...
    def set_persistent_storage_path(self, path: str, /) -> None: ...
    def set_push_service_enabled(self, enable: bool, /) -> None: ...
    def set_spell_check_enabled(self, enabled: bool, /) -> None: ...
    def set_spell_check_languages(self, languages: collections.abc.Sequence[str], /) -> None: ...
    def set_storage_name(self, name: str, /) -> None: ...
    def set_url_request_interceptor(self, interceptor: PySide6.QtWebEngineCore.QWebEngineUrlRequestInterceptor, /) -> None: ...
    def spell_check_languages(self, /) -> typing.List[str]: ...
    def storage_name(self, /) -> str: ...
    def url_scheme_handler(self, arg__1: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> PySide6.QtWebEngineCore.QWebEngineUrlSchemeHandler: ...


class QtWebEngineQuick(Shiboken.Object):
    @staticmethod
    def initialize() -> None: ...


# eof
