
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-13T23:43:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf9d0fd4a2431a8afbc2d87ee75b7c615cd2e2e2",
 "version": "0.0.1.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
