# Define possible aliases for all embeddings
MANIFOLD_ALIASES = {
    "Random projection": "Random projection embedding",
    "SparseRandomProjection": "Random projection embedding",
    "Truncated SVD": "Truncated SVD embedding",
    "SVD": "Truncated SVD embedding",
    "Isomap": "Isomap embedding",
    "LLE": "Standard LLE embedding",
    "Standard LLE": "Standard LLE embedding",
    "Modified LLE": "Modified LLE embedding",
    "Hessian LLE": "Hessian LLE embedding",
    "LTSA": "LTSA LLE embedding",
    "LTSA LLE": "LTSA LLE embedding",
    "MDS": "MDS embedding",
    "Random Trees": "Random Trees embedding",
    "RandomTreesEmbedding": "Random Trees embedding",
    "Spectral": "Spectral embedding",
    "SpectralEmbedding": "Spectral embedding",
    "TSNE": "t-SNE embedding",
    "tSNE": "t-SNE embedding",
    "t-SNE": "t-SNE embedding",
    "NCA": "NCA embedding",
    "NeighborhoodComponentsAnalysis": "NCA embedding",
}
