# Generated by Django 4.2.14 on 2025-01-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_communication'),
        ('healthcareservices', '0003_alter_healthcareservicereference_healthcare_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareservicecodeablereference',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='healthcareservice_codeableconcept', to='base.codeableconcept'),
        ),
    ]
