# Generated by Django 4.2.14 on 2025-01-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareservices', '0005_remove_healthcareservicecodeablereference_healthcare_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareservice',
            name='endpoint',
        ),
    ]
