# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSpinBox, QTextBrowser, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1903, 860)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(53, 53, 53, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(79, 79, 79, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(66, 66, 66, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(26, 26, 26, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(35, 35, 35, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        brush6 = QBrush(QColor(54, 54, 54, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        brush8 = QBrush(QColor(0, 223, 47, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush9 = QBrush(QColor(255, 255, 220, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush10 = QBrush(QColor(255, 255, 255, 128))
        brush10.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        brush11 = QBrush(QColor(78, 78, 78, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        brush12 = QBrush(QColor(145, 145, 145, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush12)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        MainWindow.setPalette(palette)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        self.actionRobot_Configuration = QAction(MainWindow)
        self.actionRobot_Configuration.setObjectName(u"actionRobot_Configuration")
        self.actionTask_Configuration = QAction(MainWindow)
        self.actionTask_Configuration.setObjectName(u"actionTask_Configuration")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        font = QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)

        self.horizontalLayout_6.addWidget(self.label_3)


        self.verticalLayout_4.addLayout(self.horizontalLayout_6)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.openGLWidget_camera_1 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_camera_1.setObjectName(u"openGLWidget_camera_1")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.openGLWidget_camera_1.sizePolicy().hasHeightForWidth())
        self.openGLWidget_camera_1.setSizePolicy(sizePolicy2)
        self.openGLWidget_camera_1.setMinimumSize(QSize(300, 300))

        self.gridLayout.addWidget(self.openGLWidget_camera_1, 0, 1, 1, 1)

        self.openGLWidget_camera_0 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_camera_0.setObjectName(u"openGLWidget_camera_0")
        sizePolicy2.setHeightForWidth(self.openGLWidget_camera_0.sizePolicy().hasHeightForWidth())
        self.openGLWidget_camera_0.setSizePolicy(sizePolicy2)
        self.openGLWidget_camera_0.setMinimumSize(QSize(300, 300))

        self.gridLayout.addWidget(self.openGLWidget_camera_0, 0, 0, 1, 1)

        self.openGLWidget_camera_2 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_camera_2.setObjectName(u"openGLWidget_camera_2")
        sizePolicy2.setHeightForWidth(self.openGLWidget_camera_2.sizePolicy().hasHeightForWidth())
        self.openGLWidget_camera_2.setSizePolicy(sizePolicy2)
        self.openGLWidget_camera_2.setMinimumSize(QSize(300, 300))

        self.gridLayout.addWidget(self.openGLWidget_camera_2, 1, 0, 1, 1)

        self.openGLWidget_camera_3 = QOpenGLWidget(self.centralwidget)
        self.openGLWidget_camera_3.setObjectName(u"openGLWidget_camera_3")
        sizePolicy2.setHeightForWidth(self.openGLWidget_camera_3.sizePolicy().hasHeightForWidth())
        self.openGLWidget_camera_3.setSizePolicy(sizePolicy2)
        self.openGLWidget_camera_3.setMinimumSize(QSize(300, 300))

        self.gridLayout.addWidget(self.openGLWidget_camera_3, 1, 1, 1, 1)


        self.verticalLayout_4.addLayout(self.gridLayout)


        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush13 = QBrush(QColor(127, 127, 127, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush13)
        brush14 = QBrush(QColor(191, 191, 191, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush14)
        brush15 = QBrush(QColor(159, 159, 159, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        brush16 = QBrush(QColor(63, 63, 63, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(84, 84, 84, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush16)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush16)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.line.setPalette(palette1)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout.addWidget(self.line)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy3)
        self.label.setMinimumSize(QSize(0, 70))
        self.label.setMaximumSize(QSize(435, 16777215))
        self.label.setFont(font)

        self.verticalLayout_2.addWidget(self.label)

        self.comboBox_task_selection = QComboBox(self.centralwidget)
        self.comboBox_task_selection.addItem("")
        self.comboBox_task_selection.addItem("")
        self.comboBox_task_selection.addItem("")
        self.comboBox_task_selection.setObjectName(u"comboBox_task_selection")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.comboBox_task_selection.sizePolicy().hasHeightForWidth())
        self.comboBox_task_selection.setSizePolicy(sizePolicy4)
        self.comboBox_task_selection.setMinimumSize(QSize(0, 100))
        self.comboBox_task_selection.setMaximumSize(QSize(450, 16777215))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        brush18 = QBrush(QColor(228, 228, 228, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush18)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush)
        brush19 = QBrush(QColor(241, 241, 241, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush19)
        brush20 = QBrush(QColor(114, 114, 114, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush20)
        brush21 = QBrush(QColor(152, 152, 152, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush21)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush18)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush19)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush22 = QBrush(QColor(0, 0, 0, 128))
        brush22.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush22)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush18)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush19)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush20)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush21)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush18)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush19)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush19)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush20)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush21)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush22)
#endif
        self.comboBox_task_selection.setPalette(palette2)
        font1 = QFont()
        font1.setPointSize(18)
        font1.setBold(True)
        self.comboBox_task_selection.setFont(font1)

        self.verticalLayout_2.addWidget(self.comboBox_task_selection)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(0, 70))
        self.label_2.setMaximumSize(QSize(234, 16777215))
        font2 = QFont()
        font2.setPointSize(20)
        self.label_2.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.pushButton_episode_count_minus = QPushButton(self.centralwidget)
        self.pushButton_episode_count_minus.setObjectName(u"pushButton_episode_count_minus")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.pushButton_episode_count_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_episode_count_minus.setSizePolicy(sizePolicy5)
        self.pushButton_episode_count_minus.setMinimumSize(QSize(50, 100))
        self.pushButton_episode_count_minus.setMaximumSize(QSize(50, 100))
        self.pushButton_episode_count_minus.setFont(font)

        self.horizontalLayout_4.addWidget(self.pushButton_episode_count_minus)

        self.spinBox_episode_count = QSpinBox(self.centralwidget)
        self.spinBox_episode_count.setObjectName(u"spinBox_episode_count")
        self.spinBox_episode_count.setMinimumSize(QSize(0, 100))
        self.spinBox_episode_count.setMaximumSize(QSize(130, 16777215))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush18)
        brush23 = QBrush(QColor(54, 54, 54, 128))
        brush23.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush23)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush18)
        brush24 = QBrush(QColor(54, 54, 54, 128))
        brush24.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush24)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        brush25 = QBrush(QColor(54, 54, 54, 128))
        brush25.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush25)
#endif
        self.spinBox_episode_count.setPalette(palette3)
        font3 = QFont()
        font3.setPointSize(24)
        font3.setBold(True)
        self.spinBox_episode_count.setFont(font3)
        self.spinBox_episode_count.setFrame(True)
        self.spinBox_episode_count.setAlignment(Qt.AlignCenter)
        self.spinBox_episode_count.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spinBox_episode_count.setValue(30)

        self.horizontalLayout_4.addWidget(self.spinBox_episode_count)

        self.pushButton_episode_count_plus = QPushButton(self.centralwidget)
        self.pushButton_episode_count_plus.setObjectName(u"pushButton_episode_count_plus")
        sizePolicy5.setHeightForWidth(self.pushButton_episode_count_plus.sizePolicy().hasHeightForWidth())
        self.pushButton_episode_count_plus.setSizePolicy(sizePolicy5)
        self.pushButton_episode_count_plus.setMinimumSize(QSize(50, 100))
        self.pushButton_episode_count_plus.setMaximumSize(QSize(50, 100))

        self.horizontalLayout_4.addWidget(self.pushButton_episode_count_plus)


        self.verticalLayout_3.addLayout(self.horizontalLayout_4)


        self.horizontalLayout_2.addLayout(self.verticalLayout_3)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.textBrowser_log = QTextBrowser(self.centralwidget)
        self.textBrowser_log.setObjectName(u"textBrowser_log")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Expanding)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.textBrowser_log.sizePolicy().hasHeightForWidth())
        self.textBrowser_log.setSizePolicy(sizePolicy6)
        self.textBrowser_log.setMinimumSize(QSize(670, 0))
        self.textBrowser_log.setMaximumSize(QSize(690, 16777215))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Base, brush18)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush18)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        self.textBrowser_log.setPalette(palette4)

        self.verticalLayout.addWidget(self.textBrowser_log)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pushButton_start_recording = QPushButton(self.centralwidget)
        self.pushButton_start_recording.setObjectName(u"pushButton_start_recording")
        self.pushButton_start_recording.setEnabled(False)
        sizePolicy4.setHeightForWidth(self.pushButton_start_recording.sizePolicy().hasHeightForWidth())
        self.pushButton_start_recording.setSizePolicy(sizePolicy4)
        self.pushButton_start_recording.setMinimumSize(QSize(150, 150))
        self.pushButton_start_recording.setMaximumSize(QSize(180, 16777215))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        self.pushButton_start_recording.setPalette(palette5)
        self.pushButton_start_recording.setFont(font1)

        self.horizontalLayout_3.addWidget(self.pushButton_start_recording)

        self.pushButton_stop_recording = QPushButton(self.centralwidget)
        self.pushButton_stop_recording.setObjectName(u"pushButton_stop_recording")
        self.pushButton_stop_recording.setEnabled(False)
        sizePolicy4.setHeightForWidth(self.pushButton_stop_recording.sizePolicy().hasHeightForWidth())
        self.pushButton_stop_recording.setSizePolicy(sizePolicy4)
        self.pushButton_stop_recording.setMinimumSize(QSize(150, 150))
        self.pushButton_stop_recording.setMaximumSize(QSize(180, 16777215))
        palette6 = QPalette()
        brush26 = QBrush(QColor(239, 41, 41, 255))
        brush26.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        self.pushButton_stop_recording.setPalette(palette6)
        self.pushButton_stop_recording.setFont(font1)

        self.horizontalLayout_3.addWidget(self.pushButton_stop_recording)

        self.pushButton_rerecord = QPushButton(self.centralwidget)
        self.pushButton_rerecord.setObjectName(u"pushButton_rerecord")
        self.pushButton_rerecord.setEnabled(False)
        sizePolicy4.setHeightForWidth(self.pushButton_rerecord.sizePolicy().hasHeightForWidth())
        self.pushButton_rerecord.setSizePolicy(sizePolicy4)
        self.pushButton_rerecord.setMinimumSize(QSize(150, 150))
        self.pushButton_rerecord.setMaximumSize(QSize(180, 16777215))
        palette7 = QPalette()
        brush27 = QBrush(QColor(255, 211, 0, 255))
        brush27.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush27)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        self.pushButton_rerecord.setPalette(palette7)
        self.pushButton_rerecord.setFont(font1)

        self.horizontalLayout_3.addWidget(self.pushButton_rerecord)

        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout_3.addWidget(self.line_2)

        self.pushButton_dryrun = QPushButton(self.centralwidget)
        self.pushButton_dryrun.setObjectName(u"pushButton_dryrun")
        self.pushButton_dryrun.setEnabled(False)
        sizePolicy4.setHeightForWidth(self.pushButton_dryrun.sizePolicy().hasHeightForWidth())
        self.pushButton_dryrun.setSizePolicy(sizePolicy4)
        self.pushButton_dryrun.setMinimumSize(QSize(150, 150))
        self.pushButton_dryrun.setMaximumSize(QSize(244, 16777215))
        self.pushButton_dryrun.setFont(font1)

        self.horizontalLayout_3.addWidget(self.pushButton_dryrun)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_recording_progress = QLabel(self.centralwidget)
        self.label_recording_progress.setObjectName(u"label_recording_progress")
        sizePolicy3.setHeightForWidth(self.label_recording_progress.sizePolicy().hasHeightForWidth())
        self.label_recording_progress.setSizePolicy(sizePolicy3)
        self.label_recording_progress.setMinimumSize(QSize(0, 70))
        self.label_recording_progress.setMaximumSize(QSize(670, 16777215))
        self.label_recording_progress.setFont(font)

        self.horizontalLayout_5.addWidget(self.label_recording_progress)

        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        font4 = QFont()
        font4.setPointSize(14)
        self.label_5.setFont(font4)

        self.horizontalLayout_5.addWidget(self.label_5, 0, Qt.AlignRight)

        self.label_total_time = QLabel(self.centralwidget)
        self.label_total_time.setObjectName(u"label_total_time")
        self.label_total_time.setFont(font4)

        self.horizontalLayout_5.addWidget(self.label_total_time, 0, Qt.AlignHCenter)


        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.progressBar_recording_progress = QProgressBar(self.centralwidget)
        self.progressBar_recording_progress.setObjectName(u"progressBar_recording_progress")
        sizePolicy4.setHeightForWidth(self.progressBar_recording_progress.sizePolicy().hasHeightForWidth())
        self.progressBar_recording_progress.setSizePolicy(sizePolicy4)
        self.progressBar_recording_progress.setMinimumSize(QSize(0, 100))
        self.progressBar_recording_progress.setMaximumSize(QSize(690, 16777215))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        self.progressBar_recording_progress.setPalette(palette8)
        self.progressBar_recording_progress.setValue(0)
        self.progressBar_recording_progress.setTextVisible(False)

        self.verticalLayout.addWidget(self.progressBar_recording_progress)


        self.horizontalLayout.addLayout(self.verticalLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1903, 22))
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuQuit = QMenu(self.menuBar)
        self.menuQuit.setObjectName(u"menuQuit")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuQuit.menuAction())
        self.menuEdit.addAction(self.actionRobot_Configuration)
        self.menuEdit.addAction(self.actionTask_Configuration)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionRobot_Configuration.setText(QCoreApplication.translate("MainWindow", u"Robot Configuration", None))
        self.actionTask_Configuration.setText(QCoreApplication.translate("MainWindow", u"Task Configuration", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"CAMERA VIEW", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TASK SELECTION", None))
        self.comboBox_task_selection.setItemText(0, QCoreApplication.translate("MainWindow", u"Trossen AI Stationary Dummy", None))
        self.comboBox_task_selection.setItemText(1, QCoreApplication.translate("MainWindow", u"Trossen AI Mobile Dummy", None))
        self.comboBox_task_selection.setItemText(2, QCoreApplication.translate("MainWindow", u"Trossen AI Solo Dummy", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"EPISODE COUNT", None))
        self.pushButton_episode_count_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_episode_count_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_start_recording.setText(QCoreApplication.translate("MainWindow", u"START\n"
"RECORDING\n"
"SESSION", None))
        self.pushButton_stop_recording.setText(QCoreApplication.translate("MainWindow", u"END\n"
"RECORDING\n"
"SESSION", None))
        self.pushButton_rerecord.setText(QCoreApplication.translate("MainWindow", u"RE-RECORD\n"
"LAST\n"
"EPISODE", None))
        self.pushButton_dryrun.setText(QCoreApplication.translate("MainWindow", u"DRY\n"
"RUN", None))
        self.label_recording_progress.setText(QCoreApplication.translate("MainWindow", u"EPISODE PROGRESS", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Total Time:", None))
        self.label_total_time.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuQuit.setTitle(QCoreApplication.translate("MainWindow", u"Quit", None))
    # retranslateUi

