# coding: utf-8

"""
    Document Intelligence API

    Data APIs to retrieve document intelligence data

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProcessingStatus(str, Enum):
    """
    ProcessingStatus
    """

    """
    allowed enum values
    """
    NEW = 'New'
    QUEUED = 'Queued'
    EXTRACTION_IN_PROCESS = 'Extraction In Process'
    EXTRACTION_COMPLETED = 'Extraction Completed'
    EXTRACTION_FAILED = 'Extraction Failed'
    VALIDATION_IN_PROCESS = 'Validation In Process'
    VALIDATION_COMPLETED = 'Validation Completed'
    VALIDATION_FAILED = 'Validation Failed'
    NEEDS_TRAINING = 'Needs Training'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProcessingStatus from a JSON string"""
        return cls(json.loads(json_str))


