from manta.color_theme.color_theme_ABC import ColorThemeABC


class TokyoNightABC(ColorThemeABC):
    """
    The TokyoNightABC defines the color scheme of the Tokyo Night color theme. It defines additional color colors to
    the ones defined in the Tokyo Night. The actual color values are defined in the child classes of TokyoNightABC
    (such as TokyoNightStorm).

    The color names were generated by Github Copilot.
    """
    night: str
    storm: str
    moon: str
    dragon: str
    spring: str
    wave: str
    sakura: str
    autumn: str
    winter: str
    summer: str
    text: str
    subtext1: str
    subtext0: str
    overlay2: str
    overlay1: str
    overlay0: str
    surface2: str
    surface1: str
    surface0: str
    base: str
    mantle: str
    crust: str