"""Helper functions for textplumber."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/95_core.ipynb.

# %% auto 0
__all__ = ['pass_tokens', 'get_stop_words']

# %% ../nbs/95_core.ipynb 3
def pass_tokens(tokens):
	""" Pass through function to pass pre-tokenized input to CountVectorizer or TfidfVectorizer. """
	return tokens

# %% ../nbs/95_core.ipynb 4
def get_stop_words():
    """ Get stop words from NLTK. """
    import nltk
    from nltk.corpus import stopwords
    nltk.download('stopwords')
    stop_words = stopwords.words('english')
    return stop_words
