__name__              =  "PySupercell"
__version__           =  "0.0.33"
__author__            =  "Shunhong Zhang"
__author_email__      =  "zhangshunhong.pku@gmail.com"
__url__               =  "https://pypi.org/project/PySupercell"
__license__           =  "MIT License"
__platforms__         =  "['Linux']"
