# Generated by Django 4.2.14 on 2025-01-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0004_ratio'),
        ('careteams', '0001_initial'),
        ('patients', '0004_patientgroupreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeOfCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('waitlist', 'Waitlist'), ('active', 'Active'), ('onhold', 'On Hold'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error')], max_length=255, null=True)),
                ('account', models.ManyToManyField(blank=True, related_name='episode_of_care_account', to='accounts.accountreference')),
                ('care_team', models.ManyToManyField(blank=True, related_name='episode_of_care_care_team', to='careteams.careteamreference')),
                ('diagnosis', models.ManyToManyField(blank=True, related_name='episode_of_care_diagnosis', to='base.codeableconcept')),
                ('identifier', models.ManyToManyField(blank=True, related_name='episode_of_care_identifier', to='base.identifier')),
                ('managing_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_of_care_managing_organization', to='base.organizationreference')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_of_care_period', to='base.period')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_of_care_patient', to='patients.patientgroupreference')),
                ('type', models.ManyToManyField(blank=True, related_name='episode_of_care_type', to='base.codeableconcept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpisodeOfCareReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('display', models.CharField(max_length=255, null=True)),
                ('episode_of_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_of_care_reference_episode_of_care', to='episodeofcare.episodeofcare')),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_of_care_reference_identifier', to='base.identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
