# Generated by Django 4.2.14 on 2025-02-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0008_alter_observationcodeablereference_concept_and_more"),
        ("immunizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immunizationreaction",
            name="manifestation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="immunization_reaction_detail",
                to="observations.observationcodeablereference",
            ),
        ),
    ]
