# Generated by Django 4.2.14 on 2025-01-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
        ('practitioners', '0009_remove_practitionerrole_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerrole',
            name='endpoint',
            field=models.ManyToManyField(blank=True, related_name='practitioner_role_endpoint', to='endpoints.endpointreference'),
        ),
    ]
