# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtHelp, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtHelp`

import PySide6.QtHelp
import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtWidgets

import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QCompressedHelpInfo(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtHelp.QCompressedHelpInfo, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def component(self, /) -> str: ...
    @staticmethod
    def from_compressed_help_file(documentationFileName: str, /) -> PySide6.QtHelp.QCompressedHelpInfo: ...
    def is_null(self, /) -> bool: ...
    def namespace_name(self, /) -> str: ...
    def swap(self, other: PySide6.QtHelp.QCompressedHelpInfo, /) -> None: ...
    def version(self, /) -> PySide6.QtCore.QVersionNumber: ...


class QHelpContentItem(Shiboken.Object):
    def child(self, row: int, /) -> PySide6.QtHelp.QHelpContentItem: ...
    def child_count(self, /) -> int: ...
    def child_position(self, child: PySide6.QtHelp.QHelpContentItem, /) -> int: ...
    def parent(self, /) -> PySide6.QtHelp.QHelpContentItem: ...
    def row(self, /) -> int: ...
    def title(self, /) -> str: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QHelpContentModel(PySide6.QtCore.QAbstractItemModel):

    contentsCreated          : typing.ClassVar[Signal] = ... # contentsCreated()
    contentsCreationStarted  : typing.ClassVar[Signal] = ... # contentsCreationStarted()
    def column_count(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> int: ...
    def content_item_at(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> PySide6.QtHelp.QHelpContentItem: ...
    def create_contents(self, customFilterName: str, /) -> None: ...
    def create_contents_for_current_filter(self, /) -> None: ...
    def data(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, role: int, /) -> typing.Any: ...
    def index(self, row: int, column: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> PySide6.QtCore.QModelIndex: ...
    def is_creating_contents(self, /) -> bool: ...
    @typing.overload
    def parent(self, /) -> PySide6.QtCore.QObject: ...
    @typing.overload
    def parent(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> PySide6.QtCore.QModelIndex: ...
    def row_count(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> int: ...


class QHelpContentWidget(PySide6.QtWidgets.QTreeView):

    linkActivated            : typing.ClassVar[Signal] = ... # linkActivated(QUrl)
    def index_of(self, link: PySide6.QtCore.QUrl | str, /) -> PySide6.QtCore.QModelIndex: ...


class QHelpEngine(PySide6.QtHelp.QHelpEngineCore):

    def __init__(self, collectionFile: str, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def content_model(self, /) -> PySide6.QtHelp.QHelpContentModel: ...
    def content_widget(self, /) -> PySide6.QtHelp.QHelpContentWidget: ...
    def index_model(self, /) -> PySide6.QtHelp.QHelpIndexModel: ...
    def index_widget(self, /) -> PySide6.QtHelp.QHelpIndexWidget: ...
    def search_engine(self, /) -> PySide6.QtHelp.QHelpSearchEngine: ...


class QHelpEngineCore(PySide6.QtCore.QObject):

    currentFilterChanged     : typing.ClassVar[Signal] = ... # currentFilterChanged(QString)
    readersAboutToBeInvalidated: typing.ClassVar[Signal] = ... # readersAboutToBeInvalidated()
    setupFinished            : typing.ClassVar[Signal] = ... # setupFinished()
    setupStarted             : typing.ClassVar[Signal] = ... # setupStarted()
    warning                  : typing.ClassVar[Signal] = ... # warning(QString)

    def __init__(self, collection_file: str, /, parent: PySide6.QtCore.QObject | None = ..., *, auto_save_filter: bool | None = ..., read_only: bool | None = ..., current_filter: str | None = ...) -> None: ...

    def add_custom_filter(self, filterName: str, attributes: collections.abc.Sequence[str], /) -> bool: ...
    def auto_save_filter(self, /) -> bool: ...
    def collection_file(self, /) -> str: ...
    def copy_collection_file(self, fileName: str, /) -> bool: ...
    def current_filter(self, /) -> str: ...
    def custom_filters(self, /) -> typing.List[str]: ...
    def custom_value(self, key: str, /, defaultValue: typing.Any = ...) -> typing.Any: ...
    def documentation_file_name(self, namespaceName: str, /) -> str: ...
    @typing.overload
    def documents_for_identifier(self, id: str, /) -> typing.List[PySide6.QtHelp.QHelpLink]: ...
    @typing.overload
    def documents_for_identifier(self, id: str, filterName: str, /) -> typing.List[PySide6.QtHelp.QHelpLink]: ...
    @typing.overload
    def documents_for_keyword(self, keyword: str, /) -> typing.List[PySide6.QtHelp.QHelpLink]: ...
    @typing.overload
    def documents_for_keyword(self, keyword: str, filterName: str, /) -> typing.List[PySide6.QtHelp.QHelpLink]: ...
    def error(self, /) -> str: ...
    def file_data(self, url: PySide6.QtCore.QUrl | str, /) -> PySide6.QtCore.QByteArray: ...
    @typing.overload
    def files(self, namespaceName: str, filterName: str, /, extensionFilter: str = ...) -> typing.List[PySide6.QtCore.QUrl]: ...
    @typing.overload
    def files(self, namespaceName: str, filterAttributes: collections.abc.Sequence[str], /, extensionFilter: str = ...) -> typing.List[PySide6.QtCore.QUrl]: ...
    def filter_attribute_sets(self, namespaceName: str, /) -> typing.List[typing.List[str]]: ...
    @typing.overload
    def filter_attributes(self, /) -> typing.List[str]: ...
    @typing.overload
    def filter_attributes(self, filterName: str, /) -> typing.List[str]: ...
    def filter_engine(self, /) -> PySide6.QtHelp.QHelpFilterEngine: ...
    def find_file(self, url: PySide6.QtCore.QUrl | str, /) -> PySide6.QtCore.QUrl: ...
    def is_read_only(self, /) -> bool: ...
    @staticmethod
    def meta_data(documentationFileName: str, name: str, /) -> typing.Any: ...
    @staticmethod
    def namespace_name(documentationFileName: str, /) -> str: ...
    def register_documentation(self, documentationFileName: str, /) -> bool: ...
    def registered_documentations(self, /) -> typing.List[str]: ...
    def remove_custom_filter(self, filterName: str, /) -> bool: ...
    def remove_custom_value(self, key: str, /) -> bool: ...
    def set_auto_save_filter(self, save: bool, /) -> None: ...
    def set_collection_file(self, fileName: str, /) -> None: ...
    def set_current_filter(self, filterName: str, /) -> None: ...
    def set_custom_value(self, key: str, value: typing.Any, /) -> bool: ...
    def set_read_only(self, enable: bool, /) -> None: ...
    def set_uses_filter_engine(self, uses: bool, /) -> None: ...
    def setup_data(self, /) -> bool: ...
    def unregister_documentation(self, namespaceName: str, /) -> bool: ...
    def uses_filter_engine(self, /) -> bool: ...


class QHelpFilterData(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtHelp.QHelpFilterData, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def __eq__(self, other: PySide6.QtHelp.QHelpFilterData, /) -> bool: ...
    def components(self, /) -> typing.List[str]: ...
    def set_components(self, components: collections.abc.Sequence[str], /) -> None: ...
    def set_versions(self, versions: collections.abc.Sequence[PySide6.QtCore.QVersionNumber], /) -> None: ...
    def swap(self, other: PySide6.QtHelp.QHelpFilterData, /) -> None: ...
    def versions(self, /) -> typing.List[PySide6.QtCore.QVersionNumber]: ...


class QHelpFilterEngine(PySide6.QtCore.QObject):

    filterActivated          : typing.ClassVar[Signal] = ... # filterActivated(QString)

    def __init__(self, helpEngine: PySide6.QtHelp.QHelpEngineCore, /) -> None: ...

    def active_filter(self, /) -> str: ...
    def available_components(self, /) -> typing.List[str]: ...
    def available_versions(self, /) -> typing.List[PySide6.QtCore.QVersionNumber]: ...
    def filter_data(self, filterName: str, /) -> PySide6.QtHelp.QHelpFilterData: ...
    def filters(self, /) -> typing.List[str]: ...
    @typing.overload
    def indices(self, /) -> typing.List[str]: ...
    @typing.overload
    def indices(self, filterName: str, /) -> typing.List[str]: ...
    def namespace_to_component(self, /) -> typing.Dict[str, str]: ...
    def namespace_to_version(self, /) -> typing.Dict[str, PySide6.QtCore.QVersionNumber]: ...
    def namespaces_for_filter(self, filterName: str, /) -> typing.List[str]: ...
    def remove_filter(self, filterName: str, /) -> bool: ...
    def set_active_filter(self, filterName: str, /) -> bool: ...
    def set_filter_data(self, filterName: str, filterData: PySide6.QtHelp.QHelpFilterData, /) -> bool: ...


class QHelpFilterSettingsWidget(PySide6.QtWidgets.QWidget):

    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ...) -> None: ...

    def apply_settings(self, filterEngine: PySide6.QtHelp.QHelpFilterEngine, /) -> bool: ...
    def read_settings(self, filterEngine: PySide6.QtHelp.QHelpFilterEngine, /) -> None: ...
    def set_available_components(self, components: collections.abc.Sequence[str], /) -> None: ...
    def set_available_versions(self, versions: collections.abc.Sequence[PySide6.QtCore.QVersionNumber], /) -> None: ...


class QHelpGlobal(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, QHelpGlobal: PySide6.QtHelp.QHelpGlobal, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    @staticmethod
    def document_title(content: str, /) -> str: ...
    @staticmethod
    def uniquify_connection_name(name: str, pointer: int, /) -> str: ...


class QHelpIndexModel(PySide6.QtCore.QStringListModel):

    indexCreated             : typing.ClassVar[Signal] = ... # indexCreated()
    indexCreationStarted     : typing.ClassVar[Signal] = ... # indexCreationStarted()
    def create_index(self, customFilterName: str, /) -> None: ...
    def create_index_for_current_filter(self, /) -> None: ...
    def filter(self, filter: str, /, wildcard: str = ...) -> PySide6.QtCore.QModelIndex: ...
    def help_engine(self, /) -> PySide6.QtHelp.QHelpEngineCore: ...
    def is_creating_index(self, /) -> bool: ...


class QHelpIndexWidget(PySide6.QtWidgets.QListView):

    documentActivated        : typing.ClassVar[Signal] = ... # documentActivated(QHelpLink,QString)
    documentsActivated       : typing.ClassVar[Signal] = ... # documentsActivated(QList<QHelpLink>,QString)
    linkActivated            : typing.ClassVar[Signal] = ... # linkActivated(QUrl,QString)
    linksActivated           : typing.ClassVar[Signal] = ... # linksActivated(QMultiMap<QString,QUrl>,QString)
    def activate_current_item(self, /) -> None: ...
    def filter_indices(self, filter: str, /, wildcard: str = ...) -> None: ...


class QHelpLink(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, QHelpLink: PySide6.QtHelp.QHelpLink, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...


class QHelpSearchEngine(PySide6.QtCore.QObject):

    indexingFinished         : typing.ClassVar[Signal] = ... # indexingFinished()
    indexingStarted          : typing.ClassVar[Signal] = ... # indexingStarted()
    searchingFinished        : typing.ClassVar[Signal] = ... # searchingFinished(int)
    searchingStarted         : typing.ClassVar[Signal] = ... # searchingStarted()

    def __init__(self, helpEngine: PySide6.QtHelp.QHelpEngineCore, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def cancel_indexing(self, /) -> None: ...
    def cancel_searching(self, /) -> None: ...
    def hit_count(self, /) -> int: ...
    def hits(self, start: int, end: int, /) -> typing.List[typing.Tuple[str, str]]: ...
    def hits_count(self, /) -> int: ...
    def query(self, /) -> typing.List[PySide6.QtHelp.QHelpSearchQuery]: ...
    def query_widget(self, /) -> PySide6.QtHelp.QHelpSearchQueryWidget: ...
    def reindex_documentation(self, /) -> None: ...
    def result_widget(self, /) -> PySide6.QtHelp.QHelpSearchResultWidget: ...
    def schedule_index_documentation(self, /) -> None: ...
    @typing.overload
    def search(self, searchInput: str, /) -> None: ...
    @typing.overload
    def search(self, queryList: collections.abc.Sequence[PySide6.QtHelp.QHelpSearchQuery], /) -> None: ...
    def search_input(self, /) -> str: ...
    def search_result_count(self, /) -> int: ...
    def search_results(self, start: int, end: int, /) -> typing.List[PySide6.QtHelp.QHelpSearchResult]: ...


class QHelpSearchEngineCore(PySide6.QtCore.QObject):

    indexingFinished         : typing.ClassVar[Signal] = ... # indexingFinished()
    indexingStarted          : typing.ClassVar[Signal] = ... # indexingStarted()
    searchingFinished        : typing.ClassVar[Signal] = ... # searchingFinished()
    searchingStarted         : typing.ClassVar[Signal] = ... # searchingStarted()

    def __init__(self, helpEngine: PySide6.QtHelp.QHelpEngineCore, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def cancel_indexing(self, /) -> None: ...
    def cancel_searching(self, /) -> None: ...
    def reindex_documentation(self, /) -> None: ...
    def schedule_index_documentation(self, /) -> None: ...
    def search(self, searchInput: str, /) -> None: ...
    def search_input(self, /) -> str: ...
    def search_result_count(self, /) -> int: ...
    def search_results(self, start: int, end: int, /) -> typing.List[PySide6.QtHelp.QHelpSearchResult]: ...


class QHelpSearchQuery(Shiboken.Object):

    class FieldName(enum.Enum):

        DEFAULT                   = ...  # 0x0
        FUZZY                     = ...  # 0x1
        WITHOUT                   = ...  # 0x2
        PHRASE                    = ...  # 0x3
        ALL                       = ...  # 0x4
        ATLEAST                   = ...  # 0x5


    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, field: PySide6.QtHelp.QHelpSearchQuery.FieldName, wordList_: collections.abc.Sequence[str], /) -> None: ...
    @typing.overload
    def __init__(self, QHelpSearchQuery: PySide6.QtHelp.QHelpSearchQuery, /) -> None: ...

    def __copy__(self, /) -> typing.Self: ...


class QHelpSearchQueryWidget(PySide6.QtWidgets.QWidget):

    search                   : typing.ClassVar[Signal] = ... # search()

    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ...) -> None: ...

    def change_event(self, event: PySide6.QtCore.QEvent, /) -> None: ...
    def collapse_extended_search(self, /) -> None: ...
    def expand_extended_search(self, /) -> None: ...
    def focus_in_event(self, focusEvent: PySide6.QtGui.QFocusEvent, /) -> None: ...
    def is_compact_mode(self, /) -> bool: ...
    def query(self, /) -> typing.List[PySide6.QtHelp.QHelpSearchQuery]: ...
    def search_input(self, /) -> str: ...
    def set_compact_mode(self, on: bool, /) -> None: ...
    def set_query(self, queryList: collections.abc.Sequence[PySide6.QtHelp.QHelpSearchQuery], /) -> None: ...
    def set_search_input(self, searchInput: str, /) -> None: ...


class QHelpSearchResult(Shiboken.Object):

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: PySide6.QtHelp.QHelpSearchResult, /) -> None: ...
    @typing.overload
    def __init__(self, url: PySide6.QtCore.QUrl | str, title: str, snippet: str, /) -> None: ...

    def snippet(self, /) -> str: ...
    def title(self, /) -> str: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...


class QHelpSearchResultWidget(PySide6.QtWidgets.QWidget):

    requestShowLink          : typing.ClassVar[Signal] = ... # requestShowLink(QUrl)
    def change_event(self, event: PySide6.QtCore.QEvent, /) -> None: ...
    def link_at(self, point: PySide6.QtCore.QPoint, /) -> PySide6.QtCore.QUrl: ...


class QIntList: ...


# eof
