# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.QtScxml, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.QtScxml`

import PySide6.QtScxml
import PySide6.QtCore

import enum
import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QIntList: ...


class QScxmlCompiler(Shiboken.Object):

    class Loader(Shiboken.Object):

        def __init__(self, /) -> None: ...

        def load(self, name: str, baseDir: str, /) -> typing.Tuple[PySide6.QtCore.QByteArray, typing.List[str]]: ...


    def __init__(self, xmlReader: PySide6.QtCore.QXmlStreamReader, /) -> None: ...

    def compile(self, /) -> PySide6.QtScxml.QScxmlStateMachine: ...
    def errors(self, /) -> typing.List[PySide6.QtScxml.QScxmlError]: ...
    def file_name(self, /) -> str: ...
    def loader(self, /) -> PySide6.QtScxml.QScxmlCompiler.Loader: ...
    def set_file_name(self, fileName: str, /) -> None: ...
    def set_loader(self, newLoader: PySide6.QtScxml.QScxmlCompiler.Loader, /) -> None: ...


class QScxmlCppDataModel(PySide6.QtScxml.QScxmlDataModel):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def evaluate_assignment(self, id: int, /) -> bool: ...
    def evaluate_foreach(self, id: int, body: PySide6.QtScxml.QScxmlDataModel.ForeachLoopBody, /) -> bool: ...
    def evaluate_initialization(self, id: int, /) -> bool: ...
    def has_scxml_property(self, name: str, /) -> bool: ...
    def in_state(self, stateName: str, /) -> bool: ...
    def scxml_event(self, /) -> PySide6.QtScxml.QScxmlEvent: ...
    def scxml_property(self, name: str, /) -> typing.Any: ...
    def set_scxml_event(self, scxmlEvent: PySide6.QtScxml.QScxmlEvent, /) -> None: ...
    def set_scxml_property(self, name: str, value: typing.Any, context: str, /) -> bool: ...
    def setup(self, initialDataValues: typing.Dict[str, typing.Any], /) -> bool: ...


class QScxmlDataModel(PySide6.QtCore.QObject):

    stateMachineChanged      : typing.ClassVar[Signal] = ... # stateMachineChanged(QScxmlStateMachine*)

    class ForeachLoopBody(Shiboken.Object):

        def __init__(self, /) -> None: ...

        def run(self, /) -> bool: ...


    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, state_machine: PySide6.QtScxml.QScxmlStateMachine | None = ...) -> None: ...

    @staticmethod
    def create_scxml_data_model(pluginKey: str, /) -> PySide6.QtScxml.QScxmlDataModel: ...
    def evaluate_assignment(self, id: int, /) -> bool: ...
    def evaluate_foreach(self, id: int, body: PySide6.QtScxml.QScxmlDataModel.ForeachLoopBody, /) -> bool: ...
    def evaluate_initialization(self, id: int, /) -> bool: ...
    def evaluate_to_bool(self, id: int, /) -> bool: ...
    def evaluate_to_string(self, id: int, /) -> str: ...
    def evaluate_to_variant(self, id: int, /) -> typing.Any: ...
    def evaluate_to_void(self, id: int, /) -> bool: ...
    def has_scxml_property(self, name: str, /) -> bool: ...
    def scxml_property(self, name: str, /) -> typing.Any: ...
    def set_scxml_event(self, event: PySide6.QtScxml.QScxmlEvent, /) -> None: ...
    def set_scxml_property(self, name: str, value: typing.Any, context: str, /) -> bool: ...
    def set_state_machine(self, stateMachine: PySide6.QtScxml.QScxmlStateMachine, /) -> None: ...
    def setup(self, initialDataValues: typing.Dict[str, typing.Any], /) -> bool: ...
    def state_machine(self, /) -> PySide6.QtScxml.QScxmlStateMachine: ...


class QScxmlDynamicScxmlServiceFactory(PySide6.QtScxml.QScxmlInvokableServiceFactory):

    def __init__(self, invokeInfo: PySide6.QtScxml.QScxmlExecutableContent.InvokeInfo, names: collections.abc.Sequence[int], parameters: collections.abc.Sequence[PySide6.QtScxml.QScxmlExecutableContent.ParameterInfo], /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def invoke(self, parentStateMachine: PySide6.QtScxml.QScxmlStateMachine, /) -> PySide6.QtScxml.QScxmlInvokableService: ...


class QScxmlError(Shiboken.Object):

    @typing.overload
    def __init__(self, arg__1: PySide6.QtScxml.QScxmlError, /, *, valid: bool | None = ..., file_name: str | None = ..., line: int | None = ..., column: int | None = ..., description: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, file_name: str, line: int, column: int, description: str, /, *, valid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, valid: bool | None = ..., file_name: str | None = ..., line: int | None = ..., column: int | None = ..., description: str | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def column(self, /) -> int: ...
    def description(self, /) -> str: ...
    def file_name(self, /) -> str: ...
    def is_valid(self, /) -> bool: ...
    def line(self, /) -> int: ...
    def to_string(self, /) -> str: ...


class QScxmlEvent(Shiboken.Object):

    class EventType(enum.Enum):

        PlatformEvent             = ...  # 0x0
        InternalEvent             = ...  # 0x1
        ExternalEvent             = ...  # 0x2


    @typing.overload
    def __init__(self, other: PySide6.QtScxml.QScxmlEvent, /, *, name: str | None = ..., event_type: PySide6.QtScxml.QScxmlEvent.EventType | None = ..., scxml_type: str | None = ..., send_id: str | None = ..., origin: str | None = ..., origin_type: str | None = ..., invoke_id: str | None = ..., delay: int | None = ..., data: typing.Any | None = ..., error_event: bool | None = ..., error_message: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, name: str | None = ..., event_type: PySide6.QtScxml.QScxmlEvent.EventType | None = ..., scxml_type: str | None = ..., send_id: str | None = ..., origin: str | None = ..., origin_type: str | None = ..., invoke_id: str | None = ..., delay: int | None = ..., data: typing.Any | None = ..., error_event: bool | None = ..., error_message: str | None = ...) -> None: ...

    def __copy__(self, /) -> typing.Self: ...
    def clear(self, /) -> None: ...
    def data(self, /) -> typing.Any: ...
    def delay(self, /) -> int: ...
    def error_message(self, /) -> str: ...
    def event_type(self, /) -> PySide6.QtScxml.QScxmlEvent.EventType: ...
    def invoke_id(self, /) -> str: ...
    def is_error_event(self, /) -> bool: ...
    def name(self, /) -> str: ...
    def origin(self, /) -> str: ...
    def origin_type(self, /) -> str: ...
    def scxml_type(self, /) -> str: ...
    def send_id(self, /) -> str: ...
    def set_data(self, data: typing.Any, /) -> None: ...
    def set_delay(self, delayInMiliSecs: int, /) -> None: ...
    def set_error_message(self, message: str, /) -> None: ...
    def set_event_type(self, type: PySide6.QtScxml.QScxmlEvent.EventType, /) -> None: ...
    def set_invoke_id(self, invokeId: str, /) -> None: ...
    def set_name(self, name: str, /) -> None: ...
    def set_origin(self, origin: str, /) -> None: ...
    def set_origin_type(self, originType: str, /) -> None: ...
    def set_send_id(self, sendId: str, /) -> None: ...


class QScxmlExecutableContent(Shiboken.Object):

    class AssignmentInfo(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, AssignmentInfo: PySide6.QtScxml.QScxmlExecutableContent.AssignmentInfo, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...

    class EvaluatorInfo(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, EvaluatorInfo: PySide6.QtScxml.QScxmlExecutableContent.EvaluatorInfo, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...

    class ForeachInfo(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, ForeachInfo: PySide6.QtScxml.QScxmlExecutableContent.ForeachInfo, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...

    class InvokeInfo(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, InvokeInfo: PySide6.QtScxml.QScxmlExecutableContent.InvokeInfo, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...

    class ParameterInfo(Shiboken.Object):

        @typing.overload
        def __init__(self, /) -> None: ...
        @typing.overload
        def __init__(self, ParameterInfo: PySide6.QtScxml.QScxmlExecutableContent.ParameterInfo, /) -> None: ...

        def __copy__(self, /) -> typing.Self: ...


class QScxmlInvokableService(PySide6.QtCore.QObject):

    def __init__(self, parent_state_machine: PySide6.QtScxml.QScxmlStateMachine, parent: PySide6.QtScxml.QScxmlInvokableServiceFactory, /, *, id: str | None = ..., name: str | None = ...) -> None: ...

    def id(self, /) -> str: ...
    def name(self, /) -> str: ...
    def parent_state_machine(self, /) -> PySide6.QtScxml.QScxmlStateMachine: ...
    def post_event(self, event: PySide6.QtScxml.QScxmlEvent, /) -> None: ...
    def start(self, /) -> bool: ...


class QScxmlInvokableServiceFactory(PySide6.QtCore.QObject):

    def __init__(self, invoke_info: PySide6.QtScxml.QScxmlExecutableContent.InvokeInfo, names: collections.abc.Sequence[int], parameters: collections.abc.Sequence[PySide6.QtScxml.QScxmlExecutableContent.ParameterInfo], /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def invoke(self, parentStateMachine: PySide6.QtScxml.QScxmlStateMachine, /) -> PySide6.QtScxml.QScxmlInvokableService: ...
    def invoke_info(self, /) -> PySide6.QtScxml.QScxmlExecutableContent.InvokeInfo: ...
    def names(self, /) -> typing.List[int]: ...
    def parameters(self, /) -> typing.List[PySide6.QtScxml.QScxmlExecutableContent.ParameterInfo]: ...


class QScxmlNullDataModel(PySide6.QtScxml.QScxmlDataModel):

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def evaluate_assignment(self, id: int, /) -> bool: ...
    def evaluate_foreach(self, id: int, body: PySide6.QtScxml.QScxmlDataModel.ForeachLoopBody, /) -> bool: ...
    def evaluate_initialization(self, id: int, /) -> bool: ...
    def evaluate_to_bool(self, id: int, /) -> bool: ...
    def evaluate_to_string(self, id: int, /) -> str: ...
    def evaluate_to_variant(self, id: int, /) -> typing.Any: ...
    def evaluate_to_void(self, id: int, /) -> bool: ...
    def has_scxml_property(self, name: str, /) -> bool: ...
    def scxml_property(self, name: str, /) -> typing.Any: ...
    def set_scxml_event(self, event: PySide6.QtScxml.QScxmlEvent, /) -> None: ...
    def set_scxml_property(self, name: str, value: typing.Any, context: str, /) -> bool: ...
    def setup(self, initialDataValues: typing.Dict[str, typing.Any], /) -> bool: ...


class QScxmlStateMachine(PySide6.QtCore.QObject):

    dataModelChanged         : typing.ClassVar[Signal] = ... # dataModelChanged(QScxmlDataModel*)
    finished                 : typing.ClassVar[Signal] = ... # finished()
    initialValuesChanged     : typing.ClassVar[Signal] = ... # initialValuesChanged(QVariantMap)
    initializedChanged       : typing.ClassVar[Signal] = ... # initializedChanged(bool)
    invokedServicesChanged   : typing.ClassVar[Signal] = ... # invokedServicesChanged(QList<QScxmlInvokableService*>)
    loaderChanged            : typing.ClassVar[Signal] = ... # loaderChanged(QScxmlCompiler::Loader*)
    log                      : typing.ClassVar[Signal] = ... # log(QString,QString)
    reachedStableState       : typing.ClassVar[Signal] = ... # reachedStableState()
    runningChanged           : typing.ClassVar[Signal] = ... # runningChanged(bool)
    tableDataChanged         : typing.ClassVar[Signal] = ... # tableDataChanged(QScxmlTableData*)

    def __init__(self, metaObject: PySide6.QtCore.QMetaObject, /, parent: PySide6.QtCore.QObject | None = ..., *, running: bool | None = ..., initialized: bool | None = ..., data_model: PySide6.QtScxml.QScxmlDataModel | None = ..., initial_values: typing.Optional[typing.Dict[str, typing.Any]] = ..., invoked_services: collections.abc.Sequence[PySide6.QtScxml.QScxmlInvokableService] | None = ..., session_id: str | None = ..., name: str | None = ..., invoked: bool | None = ..., parse_errors: collections.abc.Sequence[PySide6.QtScxml.QScxmlError] | None = ..., loader: PySide6.QtScxml.QScxmlCompiler.Loader | None = ..., table_data: PySide6.QtScxml.QScxmlTableData | None = ...) -> None: ...

    def active_state_names(self, /, compress: bool = ...) -> typing.List[str]: ...
    def cancel_delayed_event(self, sendId: str, /) -> None: ...
    def connect_to_event(self, scxmlEventSpec: str, receiver: PySide6.QtCore.QObject, method: bytes | bytearray | memoryview, /, type: PySide6.QtCore.Qt.ConnectionType = ...) -> PySide6.QtCore.QMetaObject.Connection: ...
    def connect_to_state(self, scxmlStateName: str, receiver: PySide6.QtCore.QObject, method: bytes | bytearray | memoryview, /, type: PySide6.QtCore.Qt.ConnectionType = ...) -> PySide6.QtCore.QMetaObject.Connection: ...
    def data_model(self, /) -> PySide6.QtScxml.QScxmlDataModel: ...
    @staticmethod
    def from_data(data: PySide6.QtCore.QIODevice, /, fileName: str = ...) -> PySide6.QtScxml.QScxmlStateMachine: ...
    @staticmethod
    def from_file(fileName: str, /) -> PySide6.QtScxml.QScxmlStateMachine: ...
    def init(self, /) -> bool: ...
    def initial_values(self, /) -> typing.Dict[str, typing.Any]: ...
    def invoked_services(self, /) -> typing.List[PySide6.QtScxml.QScxmlInvokableService]: ...
    @typing.overload
    def is_active(self, scxmlStateName: str, /) -> bool: ...
    @typing.overload
    def is_active(self, stateIndex: int, /) -> bool: ...
    def is_dispatchable_target(self, target: str, /) -> bool: ...
    def is_initialized(self, /) -> bool: ...
    def is_invoked(self, /) -> bool: ...
    def is_running(self, /) -> bool: ...
    def loader(self, /) -> PySide6.QtScxml.QScxmlCompiler.Loader: ...
    def name(self, /) -> str: ...
    def parse_errors(self, /) -> typing.List[PySide6.QtScxml.QScxmlError]: ...
    def session_id(self, /) -> str: ...
    def set_data_model(self, model: PySide6.QtScxml.QScxmlDataModel, /) -> None: ...
    def set_initial_values(self, initialValues: typing.Dict[str, typing.Any], /) -> None: ...
    def set_loader(self, loader: PySide6.QtScxml.QScxmlCompiler.Loader, /) -> None: ...
    def set_running(self, running: bool, /) -> None: ...
    def set_table_data(self, tableData: PySide6.QtScxml.QScxmlTableData, /) -> None: ...
    def start(self, /) -> None: ...
    def state_names(self, /, compress: bool = ...) -> typing.List[str]: ...
    def stop(self, /) -> None: ...
    @typing.overload
    def submit_event(self, event: PySide6.QtScxml.QScxmlEvent, /) -> None: ...
    @typing.overload
    def submit_event(self, eventName: str, /) -> None: ...
    @typing.overload
    def submit_event(self, eventName: str, data: typing.Any, /) -> None: ...
    def table_data(self, /) -> PySide6.QtScxml.QScxmlTableData: ...


class QScxmlStaticScxmlServiceFactory(PySide6.QtScxml.QScxmlInvokableServiceFactory):

    def __init__(self, metaObject: PySide6.QtCore.QMetaObject, invokeInfo: PySide6.QtScxml.QScxmlExecutableContent.InvokeInfo, nameList: collections.abc.Sequence[int], parameters: collections.abc.Sequence[PySide6.QtScxml.QScxmlExecutableContent.ParameterInfo], /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def invoke(self, parentStateMachine: PySide6.QtScxml.QScxmlStateMachine, /) -> PySide6.QtScxml.QScxmlInvokableService: ...


class QScxmlTableData(Shiboken.Object):

    def __init__(self, /) -> None: ...

    def assignment_info(self, assignmentId: int, /) -> PySide6.QtScxml.QScxmlExecutableContent.AssignmentInfo: ...
    def data_names(self, /) -> typing.Tuple[typing.List[int], int]: ...
    def evaluator_info(self, evaluatorId: int, /) -> PySide6.QtScxml.QScxmlExecutableContent.EvaluatorInfo: ...
    def foreach_info(self, foreachId: int, /) -> PySide6.QtScxml.QScxmlExecutableContent.ForeachInfo: ...
    def initial_setup(self, /) -> int: ...
    def instructions(self, /) -> typing.List[int]: ...
    def name(self, /) -> str: ...
    def service_factory(self, id: int, /) -> PySide6.QtScxml.QScxmlInvokableServiceFactory: ...
    def state_machine_table(self, /) -> typing.List[int]: ...
    def string(self, id: int, /) -> str: ...


# eof
