# Generated by Django 4.2.14 on 2025-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_ratio'),
        ('relatedpersons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedperson',
            name='communication',
            field=models.ManyToManyField(blank=True, related_name='relatedpersons_communication', to='base.communication'),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('unknown', 'unknown')], max_length=20, null=True),
        ),
    ]
