SOAP_NAMESPACES = {
    "s": "http://www.w3.org/2003/05/soap-envelope",
    "a": "http://schemas.xmlsoap.org/ws/2004/08/addressing",
    "d": "http://schemas.xmlsoap.org/ws/2005/04/discovery",
    "dn": "http://www.onvif.org/ver10/network/wsdl",
    "tds": "http://www.onvif.org/ver10/device/wsdl",
    "tt": "http://www.onvif.org/ver10/schema",
    "trt": "http://www.onvif.org/ver10/media/wsdl",
    "tev": "http://www.onvif.org/ver10/events/wsdl",
    "timg": "http://www.onvif.org/ver20/imaging/wsdl",
    "tptz": "http://www.onvif.org/ver20/ptz/wsdl",
    "tan": "http://www.onvif.org/ver20/analytics/wsdl",
    "tr2": "http://www.onvif.org/ver20/media/wsdl",
    "wsdl": "http://schemas.xmlsoap.org/wsdl/",
    "wsnt": "http://docs.oasis-open.org/wsn/b-2",
    "xsd": "http://www.w3.org/2001/XMLSchema",
}
