# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.sync import Sync
from ...types.sync_with_source_connection import SyncWithSourceConnection

ListSyncsSyncGetResponse = typing.Union[typing.List[Sync], typing.List[SyncWithSourceConnection]]
