# Generated by Django 4.2.14 on 2025-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimendefinitions', '0002_remove_specimendefinition_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimendefinition',
            name='type_tested',
            field=models.ManyToManyField(blank=True, related_name='specimen_definition_type_tested', to='specimendefinitions.specimendefinitiontypetested'),
        ),
    ]
