# Generated by Django 4.2.14 on 2025-03-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organizationcodeablereference"),
        (
            "supplydelivery",
            "0003_rename_item_codealbe_concept_supplydeliverysupplieditem_item_codeable_concept_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplydelivery",
            name="supplied",
        ),
        migrations.AddField(
            model_name="supplydelivery",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="supply_delivery_supplier",
                to="supplydelivery.supplydeliverysupplierreference",
            ),
        ),
        migrations.AddField(
            model_name="supplydeliveryreceiverreference",
            name="organizations",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="supply_delivery_receiver_references_organization",
                to="organizations.organization",
            ),
        ),
    ]
