# Generated by Django 4.2.14 on 2025-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_communication'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='communication',
            field=models.ManyToManyField(blank=True, related_name='patient_communication', to='base.communication'),
        ),
        migrations.DeleteModel(
            name='PatientCommunication',
        ),
    ]
