
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-10T15:06:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b32e3a026b758ec239f5f91b28dcf340205498b",
 "version": "1.2.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
