# nsd_utils/__init__.py

__version__ = "0.2.0"
PYCHARM_FEATURES = [
    "PyCharmDebugger",
    "PyCharmCodeAnalyzer",
    "PyCharmRunConfiguration",
    "PyCharmTestRunner",
    "PyCharmCoverage",
    "PyCharmRefactor",
    "PyCharmRename",
    "PyCharmSearchReplace",
    "PyCharmCodeFormatting",
    "PyCharmCodeInspection",
    "PyCharmCodeCompletion",
    "PyCharmCodeGeneration",
    "PyCharmVCSIntegration",
    "PyCharmEnvironmentManagement",
    "PyCharmErrorHighlighting",
    "PyCharmBreakpoints",
    "PyCharmWatchVariables",
    "PyCharmStepOver",
    "PyCharmStepInto",
    "PyCharmContinue",
    "PyCharmEvaluateExpression",
    "PyCharmInteractiveConsole",
    "PyCharmRunTests",
    "PyCharmCommitChanges",
    "PyCharmPushChanges",
    "PyCharmPullChanges",
    "PyCharmMergeConflictResolution",
    "PyCharmTerminal",
    "PyCharmPythonConsole",
    "PyCharmStructureView",
    "PyCharmNavigationBar",
    "PyCharmGutterIcons",
    "PyCharmQuickDefinition",
    "PyCharmFileWatchers",
    "PyCharmPreCommitHooks",
    "PyCharmTypeHints"
]
