
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-09T18:20:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a01f1090a5accfb05b7db6dc6469f7c51d4fa67",
 "version": "5.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
