WAIT_TIMEOUT = 5000
CAPTCHA_MAX_TIME = 120
MAX_RECURSION_COUNT = 3
RECURSION_COUNT_SIX = 6

NOPECHA_API_KEY = "NOPECHA_API_KEY"
GOOGLE_RECAPTCHA_PAGE_URL = "le.com/recaptcha/api2/demo"


CAPTCHA_TYPE_RECAPTCHA = 'recaptcha'
CAPTCHA_TYPE_TEXTCAPTCHA = 'textcaptcha'
