
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-10T23:17:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dbdbfee9ce8361b7975c9333179b88c01560137",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
