# Generated by Django 4.2.14 on 2025-02-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_expression_relativetime'),
        ('observations', '0007_observationcodeablereference_delete_bodysite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationcodeablereference',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_codeable_reference_concept', to='base.codeableconcept'),
        ),
        migrations.AlterField(
            model_name='observationcodeablereference',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_codeable_reference_reference', to='observations.observationreference'),
        ),
    ]
