# This file was auto-generated by Fern from our API Definition.

from .inbox_item_fix_base import InboxItemFixBase
import typing_extensions
from .knowledge_base_information import KnowledgeBaseInformation
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class InboxItemFixDeactivateKnowledgeBase(InboxItemFixBase):
    knowledge_base: typing_extensions.Annotated[KnowledgeBaseInformation, FieldMetadata(alias="knowledgeBase")] = (
        pydantic.Field()
    )
    """
    The knowledge base associated with this fix.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
