# Generated by Django 4.2.14 on 2025-01-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='endpoint',
        ),
    ]
