# Generated by Django 4.2.14 on 2025-01-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_communication'),
        ('encounters', '0003_remove_encounter_accounts_and_more'),
        ('locations', '0002_locationorganizationreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounteradmission',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_destination', to='locations.locationorganizationreference'),
        ),
        migrations.AddField(
            model_name='encounteradmission',
            name='discharge_disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encounter_admission_discharge_disposition', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='encounteradmission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_origin', to='locations.locationorganizationreference'),
        ),
        migrations.AddField(
            model_name='encounteradmission',
            name='pre_admission_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encounter_admission_pre_admission_identifier', to='base.identifier'),
        ),
        migrations.AddField(
            model_name='encounteradmission',
            name='re_admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encounter_admission_re_admission', to='base.codeableconcept'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encounter_admission', to='encounters.encounteradmission'),
        ),
        migrations.AddField(
            model_name='encounterparticipant',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_actor', to='encounters.encounterparticipantactor'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='encounter_location', to='encounters.encounterlocation'),
        ),
        migrations.AddField(
            model_name='encounterparticipant',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='encounter_participant_type', to='base.codeableconcept'),
        ),
    ]
