from _typeshed import Incomplete
from enum import Enum

class n_asythread_status(Enum):
    unstart: int
    running: int
    finish: int

class n_asyerror(Exception):
    message: Incomplete
    line_number: Incomplete
    def __init__(self, message) -> None: ...

class n_asyncThreadPool:
    max_workers: Incomplete
    def __init__(self, max_workers: int = ..., group: int = ..., time_interval: float = ...) -> None: ...
    def setGroupExecInterval(self, group: int, time_interval: float): ...
    @property
    def getStatus(self) -> n_asythread_status: ...
    def put(self, func, *args, **kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def start(self) -> list: ...
    def get_results(self): ...
    @classmethod
    def single_submit(cls, func, *args, **kwargs) -> any: ...
    def clear(self) -> None: ...
    def map(self, func, *args) -> list: ...
