# Generated by Django 4.2.14 on 2025-03-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge_20250307_1944'),
        ('claimresponses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimresponseitemadjudication',
            name='reason',
        ),
        migrations.AddField(
            model_name='claimresponseitemadjudication',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_item_adjudication_reason', to='base.codeableconcept'),
        ),
    ]
