# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .entity_type import EntityType
from .entity_definition_entity_schema import EntityDefinitionEntitySchema
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EntityDefinition(UniversalBaseModel):
    """
    Schema for an entity definition.
    """

    name: str
    description: typing.Optional[str] = None
    type: EntityType
    entity_schema: EntityDefinitionEntitySchema
    parent_id: typing.Optional[str] = None
    module_name: str
    class_name: str
    id: str
    organization_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
