# Generated by Django 4.2.14 on 2025-01-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_endpointreference_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('expression', models.TextField(null=True)),
                ('reference', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_path', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('context_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_time_context_code', to='base.codeableconcept')),
                ('context_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_time_context_reference', to='base.reference')),
                ('offset_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_time_offset_duration', to='base.quantity')),
                ('offset_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_time_offset_range', to='base.range')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
