# Generated by Django 4.2.14 on 2025-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_age_duration_simplequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeat',
            name='duration_unit',
            field=models.CharField(choices=[('s', 'second'), ('min', 'minute'), ('h', 'hour'), ('d', 'day'), ('wk', 'week'), ('mo', 'month'), ('yr', 'year')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repeat',
            name='period_unit',
            field=models.CharField(choices=[('s', 'second'), ('min', 'minute'), ('h', 'hour'), ('d', 'day'), ('wk', 'week'), ('mo', 'month'), ('yr', 'year')], max_length=255, null=True),
        ),
    ]
