# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
from __future__ import annotations
"""
This file contains the exact signatures for all functions in module
PySide6.Qt3DExtras, except for defaults which are replaced by "...".

# mypy: disable-error-code="override, overload-overlap"
"""

# Module `PySide6.Qt3DExtras`

import PySide6.Qt3DExtras
import PySide6.QtCore
import PySide6.QtGui
import PySide6.Qt3DCore
import PySide6.Qt3DRender

import typing
import collections
from PySide6.QtCore import Signal
from shiboken6 import Shiboken


class QIntList: ...


class Qt3DExtras(Shiboken.Object):

    class QAbstractCameraController(PySide6.Qt3DCore.Qt3DCore.QEntity):

        accelerationChanged      : typing.ClassVar[Signal] = ... # accelerationChanged(float)
        cameraChanged            : typing.ClassVar[Signal] = ... # cameraChanged()
        decelerationChanged      : typing.ClassVar[Signal] = ... # decelerationChanged(float)
        linearSpeedChanged       : typing.ClassVar[Signal] = ... # linearSpeedChanged()
        lookSpeedChanged         : typing.ClassVar[Signal] = ... # lookSpeedChanged()

        class InputState(Shiboken.Object):

            @typing.overload
            def __init__(self, /) -> None: ...
            @typing.overload
            def __init__(self, InputState: PySide6.Qt3DExtras.Qt3DExtras.QAbstractCameraController.InputState, /) -> None: ...

            def __copy__(self, /) -> typing.Self: ...


        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, camera: PySide6.Qt3DRender.Qt3DRender.QCamera | None = ..., linearSpeed: float | None = ..., lookSpeed: float | None = ..., acceleration: float | None = ..., deceleration: float | None = ...) -> None: ...

        @property
        def acceleration(self, /) -> float: ...
        @acceleration.setter
        def acceleration(self, acceleration: float, /) -> None: ...
        @property
        def camera(self, /) -> PySide6.Qt3DRender.Qt3DRender.QCamera: ...
        @camera.setter
        def camera(self, camera: PySide6.Qt3DRender.Qt3DRender.QCamera, /) -> None: ...
        @property
        def deceleration(self, /) -> float: ...
        @deceleration.setter
        def deceleration(self, deceleration: float, /) -> None: ...
        @property
        def linearSpeed(self, /) -> float: ...
        @linearSpeed.setter
        def linearSpeed(self, linearSpeed: float, /) -> None: ...
        @property
        def lookSpeed(self, /) -> float: ...
        @lookSpeed.setter
        def lookSpeed(self, lookSpeed: float, /) -> None: ...

    class QAbstractSpriteSheet(PySide6.Qt3DCore.Qt3DCore.QNode):

        currentIndexChanged      : typing.ClassVar[Signal] = ... # currentIndexChanged(int)
        textureChanged           : typing.ClassVar[Signal] = ... # textureChanged(Qt3DRender::QAbstractTexture*)
        textureTransformChanged  : typing.ClassVar[Signal] = ... # textureTransformChanged(QMatrix3x3)
        @property
        def currentIndex(self, /) -> int: ...
        @currentIndex.setter
        def currentIndex(self, currentIndex: int, /) -> None: ...
        @property
        def texture(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @texture.setter
        def texture(self, texture: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def textureTransform(self, /) -> PySide6.QtGui.QMatrix3x3: ...

    class QConeGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        bottomRadiusChanged      : typing.ClassVar[Signal] = ... # bottomRadiusChanged(float)
        hasBottomEndcapChanged   : typing.ClassVar[Signal] = ... # hasBottomEndcapChanged(bool)
        hasTopEndcapChanged      : typing.ClassVar[Signal] = ... # hasTopEndcapChanged(bool)
        lengthChanged            : typing.ClassVar[Signal] = ... # lengthChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)
        topRadiusChanged         : typing.ClassVar[Signal] = ... # topRadiusChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, hasTopEndcap: bool | None = ..., hasBottomEndcap: bool | None = ..., rings: int | None = ..., slices: int | None = ..., topRadius: float | None = ..., bottomRadius: float | None = ..., length: float | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., texCoordAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def bottomRadius(self, /) -> float: ...
        @bottomRadius.setter
        def bottomRadius(self, bottomRadius: float, /) -> None: ...
        @property
        def hasBottomEndcap(self, /) -> bool: ...
        @hasBottomEndcap.setter
        def hasBottomEndcap(self, hasBottomEndcap: bool, /) -> None: ...
        @property
        def hasTopEndcap(self, /) -> bool: ...
        @hasTopEndcap.setter
        def hasTopEndcap(self, hasTopEndcap: bool, /) -> None: ...
        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def length(self, /) -> float: ...
        @length.setter
        def length(self, length: float, /) -> None: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...
        @property
        def texCoordAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def topRadius(self, /) -> float: ...
        @topRadius.setter
        def topRadius(self, topRadius: float, /) -> None: ...
        def updateIndices(self, /) -> None: ...
        def updateVertices(self, /) -> None: ...

    class QConeGeometryView(PySide6.Qt3DCore.Qt3DCore.QGeometryView):

        bottomRadiusChanged      : typing.ClassVar[Signal] = ... # bottomRadiusChanged(float)
        hasBottomEndcapChanged   : typing.ClassVar[Signal] = ... # hasBottomEndcapChanged(bool)
        hasTopEndcapChanged      : typing.ClassVar[Signal] = ... # hasTopEndcapChanged(bool)
        lengthChanged            : typing.ClassVar[Signal] = ... # lengthChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)
        topRadiusChanged         : typing.ClassVar[Signal] = ... # topRadiusChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., hasTopEndcap: bool | None = ..., hasBottomEndcap: bool | None = ..., topRadius: float | None = ..., bottomRadius: float | None = ..., length: float | None = ...) -> None: ...

        @property
        def bottomRadius(self, /) -> float: ...
        @bottomRadius.setter
        def bottomRadius(self, bottomRadius: float, /) -> None: ...
        @property
        def hasBottomEndcap(self, /) -> bool: ...
        @hasBottomEndcap.setter
        def hasBottomEndcap(self, hasBottomEndcap: bool, /) -> None: ...
        @property
        def hasTopEndcap(self, /) -> bool: ...
        @hasTopEndcap.setter
        def hasTopEndcap(self, hasTopEndcap: bool, /) -> None: ...
        @property
        def length(self, /) -> float: ...
        @length.setter
        def length(self, length: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DCore.Qt3DCore.QGeometryView.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...
        @property
        def topRadius(self, /) -> float: ...
        @topRadius.setter
        def topRadius(self, topRadius: float, /) -> None: ...

    class QConeMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        bottomRadiusChanged      : typing.ClassVar[Signal] = ... # bottomRadiusChanged(float)
        hasBottomEndcapChanged   : typing.ClassVar[Signal] = ... # hasBottomEndcapChanged(bool)
        hasTopEndcapChanged      : typing.ClassVar[Signal] = ... # hasTopEndcapChanged(bool)
        lengthChanged            : typing.ClassVar[Signal] = ... # lengthChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)
        topRadiusChanged         : typing.ClassVar[Signal] = ... # topRadiusChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., hasTopEndcap: bool | None = ..., hasBottomEndcap: bool | None = ..., topRadius: float | None = ..., bottomRadius: float | None = ..., length: float | None = ...) -> None: ...

        @property
        def bottomRadius(self, /) -> float: ...
        @bottomRadius.setter
        def bottomRadius(self, bottomRadius: float, /) -> None: ...
        @property
        def hasBottomEndcap(self, /) -> bool: ...
        @hasBottomEndcap.setter
        def hasBottomEndcap(self, hasBottomEndcap: bool, /) -> None: ...
        @property
        def hasTopEndcap(self, /) -> bool: ...
        @hasTopEndcap.setter
        def hasTopEndcap(self, hasTopEndcap: bool, /) -> None: ...
        @property
        def length(self, /) -> float: ...
        @length.setter
        def length(self, length: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...
        @property
        def topRadius(self, /) -> float: ...
        @topRadius.setter
        def topRadius(self, topRadius: float, /) -> None: ...

    class QCuboidGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        xExtentChanged           : typing.ClassVar[Signal] = ... # xExtentChanged(float)
        xyMeshResolutionChanged  : typing.ClassVar[Signal] = ... # xyMeshResolutionChanged(QSize)
        xzMeshResolutionChanged  : typing.ClassVar[Signal] = ... # xzMeshResolutionChanged(QSize)
        yExtentChanged           : typing.ClassVar[Signal] = ... # yExtentChanged(float)
        yzMeshResolutionChanged  : typing.ClassVar[Signal] = ... # yzMeshResolutionChanged(QSize)
        zExtentChanged           : typing.ClassVar[Signal] = ... # zExtentChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, xExtent: float | None = ..., yExtent: float | None = ..., zExtent: float | None = ..., xyMeshResolution: PySide6.QtCore.QSize | None = ..., yzMeshResolution: PySide6.QtCore.QSize | None = ..., xzMeshResolution: PySide6.QtCore.QSize | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., texCoordAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., tangentAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def setXYMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        def setXZMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        def setYZMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def tangentAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def texCoordAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def updateIndices(self, /) -> None: ...
        def updateVertices(self, /) -> None: ...
        @property
        def xExtent(self, /) -> float: ...
        @xExtent.setter
        def xExtent(self, xExtent: float, /) -> None: ...
        @property
        def xyMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @xyMeshResolution.setter
        def xyMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def xzMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @xzMeshResolution.setter
        def xzMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def yExtent(self, /) -> float: ...
        @yExtent.setter
        def yExtent(self, yExtent: float, /) -> None: ...
        @property
        def yzMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @yzMeshResolution.setter
        def yzMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def zExtent(self, /) -> float: ...
        @zExtent.setter
        def zExtent(self, zExtent: float, /) -> None: ...

    class QCuboidGeometryView(PySide6.Qt3DCore.Qt3DCore.QGeometryView):

        xExtentChanged           : typing.ClassVar[Signal] = ... # xExtentChanged(float)
        xyMeshResolutionChanged  : typing.ClassVar[Signal] = ... # xyMeshResolutionChanged(QSize)
        xzMeshResolutionChanged  : typing.ClassVar[Signal] = ... # xzMeshResolutionChanged(QSize)
        yExtentChanged           : typing.ClassVar[Signal] = ... # yExtentChanged(float)
        yzMeshResolutionChanged  : typing.ClassVar[Signal] = ... # yzMeshResolutionChanged(QSize)
        zExtentChanged           : typing.ClassVar[Signal] = ... # zExtentChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, xExtent: float | None = ..., yExtent: float | None = ..., zExtent: float | None = ..., yzMeshResolution: PySide6.QtCore.QSize | None = ..., xzMeshResolution: PySide6.QtCore.QSize | None = ..., xyMeshResolution: PySide6.QtCore.QSize | None = ...) -> None: ...

        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DCore.Qt3DCore.QGeometryView.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        def setXYMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        def setXZMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        def setYZMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def xExtent(self, /) -> float: ...
        @xExtent.setter
        def xExtent(self, xExtent: float, /) -> None: ...
        @property
        def xyMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @xyMeshResolution.setter
        def xyMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def xzMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @xzMeshResolution.setter
        def xzMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def yExtent(self, /) -> float: ...
        @yExtent.setter
        def yExtent(self, yExtent: float, /) -> None: ...
        @property
        def yzMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @yzMeshResolution.setter
        def yzMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def zExtent(self, /) -> float: ...
        @zExtent.setter
        def zExtent(self, zExtent: float, /) -> None: ...

    class QCuboidMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        xExtentChanged           : typing.ClassVar[Signal] = ... # xExtentChanged(float)
        xyMeshResolutionChanged  : typing.ClassVar[Signal] = ... # xyMeshResolutionChanged(QSize)
        xzMeshResolutionChanged  : typing.ClassVar[Signal] = ... # xzMeshResolutionChanged(QSize)
        yExtentChanged           : typing.ClassVar[Signal] = ... # yExtentChanged(float)
        yzMeshResolutionChanged  : typing.ClassVar[Signal] = ... # yzMeshResolutionChanged(QSize)
        zExtentChanged           : typing.ClassVar[Signal] = ... # zExtentChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, xExtent: float | None = ..., yExtent: float | None = ..., zExtent: float | None = ..., yzMeshResolution: PySide6.QtCore.QSize | None = ..., xzMeshResolution: PySide6.QtCore.QSize | None = ..., xyMeshResolution: PySide6.QtCore.QSize | None = ...) -> None: ...

        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        def setXYMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        def setXZMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        def setYZMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def xExtent(self, /) -> float: ...
        @xExtent.setter
        def xExtent(self, xExtent: float, /) -> None: ...
        @property
        def xyMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @xyMeshResolution.setter
        def xyMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def xzMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @xzMeshResolution.setter
        def xzMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def yExtent(self, /) -> float: ...
        @yExtent.setter
        def yExtent(self, yExtent: float, /) -> None: ...
        @property
        def yzMeshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @yzMeshResolution.setter
        def yzMeshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def zExtent(self, /) -> float: ...
        @zExtent.setter
        def zExtent(self, zExtent: float, /) -> None: ...

    class QCylinderGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        lengthChanged            : typing.ClassVar[Signal] = ... # lengthChanged(float)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., length: float | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., texCoordAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def length(self, /) -> float: ...
        @length.setter
        def length(self, length: float, /) -> None: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...
        @property
        def texCoordAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def updateIndices(self, /) -> None: ...
        def updateVertices(self, /) -> None: ...

    class QCylinderGeometryView(PySide6.Qt3DCore.Qt3DCore.QGeometryView):

        lengthChanged            : typing.ClassVar[Signal] = ... # lengthChanged(float)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., length: float | None = ...) -> None: ...

        @property
        def length(self, /) -> float: ...
        @length.setter
        def length(self, length: float, /) -> None: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DCore.Qt3DCore.QGeometryView.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...

    class QCylinderMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        lengthChanged            : typing.ClassVar[Signal] = ... # lengthChanged(float)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., length: float | None = ...) -> None: ...

        @property
        def length(self, /) -> float: ...
        @length.setter
        def length(self, length: float, /) -> None: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...

    class QDiffuseMapMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(Qt3DRender::QAbstractTexture*)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QColor)
        textureScaleChanged      : typing.ClassVar[Signal] = ... # textureScaleChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., specular: PySide6.QtGui.QColor | None = ..., shininess: float | None = ..., diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., textureScale: float | None = ...) -> None: ...

        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, color: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.QtGui.QColor: ...
        @specular.setter
        def specular(self, specular: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def textureScale(self, /) -> float: ...
        @textureScale.setter
        def textureScale(self, textureScale: float, /) -> None: ...

    class QDiffuseSpecularMapMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(Qt3DRender::QAbstractTexture*)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(Qt3DRender::QAbstractTexture*)
        textureScaleChanged      : typing.ClassVar[Signal] = ... # textureScaleChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., shininess: float | None = ..., specular: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., textureScale: float | None = ...) -> None: ...

        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @specular.setter
        def specular(self, specular: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def textureScale(self, /) -> float: ...
        @textureScale.setter
        def textureScale(self, textureScale: float, /) -> None: ...

    class QDiffuseSpecularMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        alphaBlendingEnabledChanged: typing.ClassVar[Signal] = ... # alphaBlendingEnabledChanged(bool)
        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(QVariant)
        normalChanged            : typing.ClassVar[Signal] = ... # normalChanged(QVariant)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QVariant)
        textureScaleChanged      : typing.ClassVar[Signal] = ... # textureScaleChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., diffuse: typing.Any | None = ..., specular: typing.Any | None = ..., shininess: float | None = ..., normal: typing.Any | None = ..., textureScale: float | None = ..., alphaBlending: bool | None = ...) -> None: ...

        @property
        def alphaBlending(self, /) -> bool: ...
        @alphaBlending.setter
        def alphaBlending(self, enabled: bool, /) -> None: ...
        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> typing.Any: ...
        @diffuse.setter
        def diffuse(self, diffuse: typing.Any, /) -> None: ...
        @property
        def normal(self, /) -> typing.Any: ...
        @normal.setter
        def normal(self, normal: typing.Any, /) -> None: ...
        def setAlphaBlendingEnabled(self, enabled: bool, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> typing.Any: ...
        @specular.setter
        def specular(self, specular: typing.Any, /) -> None: ...
        @property
        def textureScale(self, /) -> float: ...
        @textureScale.setter
        def textureScale(self, textureScale: float, /) -> None: ...

    class QExtrudedTextGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        depthChanged             : typing.ClassVar[Signal] = ... # depthChanged(float)
        fontChanged              : typing.ClassVar[Signal] = ... # fontChanged(QFont)
        textChanged              : typing.ClassVar[Signal] = ... # textChanged(QString)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, text: str | None = ..., font: PySide6.QtGui.QFont | None = ..., extrusionLength: float | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def extrusionLength(self, /) -> float: ...
        @extrusionLength.setter
        def extrusionLength(self, extrusionLength: float, /) -> None: ...
        @property
        def font(self, /) -> PySide6.QtGui.QFont: ...
        @font.setter
        def font(self, font: PySide6.QtGui.QFont | str | collections.abc.Sequence[str], /) -> None: ...
        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def setDepth(self, extrusionLength: float, /) -> None: ...
        @property
        def text(self, /) -> str: ...
        @text.setter
        def text(self, text: str, /) -> None: ...

    class QExtrudedTextMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        depthChanged             : typing.ClassVar[Signal] = ... # depthChanged(float)
        fontChanged              : typing.ClassVar[Signal] = ... # fontChanged(QFont)
        textChanged              : typing.ClassVar[Signal] = ... # textChanged(QString)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, text: str | None = ..., font: PySide6.QtGui.QFont | None = ..., depth: float | None = ...) -> None: ...

        @property
        def depth(self, /) -> float: ...
        @depth.setter
        def depth(self, depth: float, /) -> None: ...
        @property
        def font(self, /) -> PySide6.QtGui.QFont: ...
        @font.setter
        def font(self, font: PySide6.QtGui.QFont | str | collections.abc.Sequence[str], /) -> None: ...
        @property
        def text(self, /) -> str: ...
        @text.setter
        def text(self, text: str, /) -> None: ...

    class QFirstPersonCameraController(PySide6.Qt3DExtras.Qt3DExtras.QAbstractCameraController):

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ...) -> None: ...


    class QForwardRenderer(PySide6.Qt3DRender.Qt3DRender.QTechniqueFilter):

        buffersToClearChanged    : typing.ClassVar[Signal] = ... # buffersToClearChanged(Qt3DRender::QClearBuffers::BufferType)
        cameraChanged            : typing.ClassVar[Signal] = ... # cameraChanged(Qt3DCore::QEntity*)
        clearColorChanged        : typing.ClassVar[Signal] = ... # clearColorChanged(QColor)
        externalRenderTargetSizeChanged: typing.ClassVar[Signal] = ... # externalRenderTargetSizeChanged(QSize)
        frustumCullingEnabledChanged: typing.ClassVar[Signal] = ... # frustumCullingEnabledChanged(bool)
        gammaChanged             : typing.ClassVar[Signal] = ... # gammaChanged(float)
        showDebugOverlayChanged  : typing.ClassVar[Signal] = ... # showDebugOverlayChanged(bool)
        surfaceChanged           : typing.ClassVar[Signal] = ... # surfaceChanged(QObject*)
        viewportRectChanged      : typing.ClassVar[Signal] = ... # viewportRectChanged(QRectF)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, surface: PySide6.QtCore.QObject | None = ..., window: PySide6.QtCore.QObject | None = ..., viewportRect: PySide6.QtCore.QRectF | None = ..., clearColor: PySide6.QtGui.QColor | None = ..., buffersToClear: PySide6.Qt3DRender.Qt3DRender.QClearBuffers.BufferType | None = ..., camera: PySide6.Qt3DCore.Qt3DCore.QEntity | None = ..., externalRenderTargetSize: PySide6.QtCore.QSize | None = ..., frustumCulling: bool | None = ..., gamma: float | None = ..., showDebugOverlay: bool | None = ...) -> None: ...

        @property
        def buffersToClear(self, /) -> PySide6.Qt3DRender.Qt3DRender.QClearBuffers.BufferType: ...
        @buffersToClear.setter
        def buffersToClear(self, arg__1: PySide6.Qt3DRender.Qt3DRender.QClearBuffers.BufferType, /) -> None: ...
        @property
        def camera(self, /) -> PySide6.Qt3DCore.Qt3DCore.QEntity: ...
        @camera.setter
        def camera(self, camera: PySide6.Qt3DCore.Qt3DCore.QEntity, /) -> None: ...
        @property
        def clearColor(self, /) -> PySide6.QtGui.QColor: ...
        @clearColor.setter
        def clearColor(self, clearColor: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def externalRenderTargetSize(self, /) -> PySide6.QtCore.QSize: ...
        @externalRenderTargetSize.setter
        def externalRenderTargetSize(self, size: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def frustumCulling(self, /) -> bool: ...
        @frustumCulling.setter
        def frustumCulling(self, enabled: bool, /) -> None: ...
        @property
        def gamma(self, /) -> float: ...
        @gamma.setter
        def gamma(self, gamma: float, /) -> None: ...
        def setFrustumCullingEnabled(self, enabled: bool, /) -> None: ...
        @property
        def showDebugOverlay(self, /) -> bool: ...
        @showDebugOverlay.setter
        def showDebugOverlay(self, showDebugOverlay: bool, /) -> None: ...
        @property
        def viewportRect(self, /) -> PySide6.QtCore.QRectF: ...
        @viewportRect.setter
        def viewportRect(self, viewportRect: PySide6.QtCore.QRectF | PySide6.QtCore.QRect, /) -> None: ...
        @property
        def window(self, /) -> PySide6.QtCore.QObject: ...
        @window.setter
        def window(self, surface: PySide6.QtCore.QObject, /) -> None: ...

    class QGoochMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        alphaChanged             : typing.ClassVar[Signal] = ... # alphaChanged(float)
        betaChanged              : typing.ClassVar[Signal] = ... # betaChanged(float)
        coolChanged              : typing.ClassVar[Signal] = ... # coolChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(QColor)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QColor)
        warmChanged              : typing.ClassVar[Signal] = ... # warmChanged(QColor)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, diffuse: PySide6.QtGui.QColor | None = ..., specular: PySide6.QtGui.QColor | None = ..., cool: PySide6.QtGui.QColor | None = ..., warm: PySide6.QtGui.QColor | None = ..., alpha: float | None = ..., beta: float | None = ..., shininess: float | None = ...) -> None: ...

        @property
        def alpha(self, /) -> float: ...
        @alpha.setter
        def alpha(self, alpha: float, /) -> None: ...
        @property
        def beta(self, /) -> float: ...
        @beta.setter
        def beta(self, beta: float, /) -> None: ...
        @property
        def cool(self, /) -> PySide6.QtGui.QColor: ...
        @cool.setter
        def cool(self, cool: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.QtGui.QColor: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.QtGui.QColor: ...
        @specular.setter
        def specular(self, specular: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def warm(self, /) -> PySide6.QtGui.QColor: ...
        @warm.setter
        def warm(self, warm: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...

    class QMetalRoughMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientOcclusionChanged  : typing.ClassVar[Signal] = ... # ambientOcclusionChanged(QVariant)
        baseColorChanged         : typing.ClassVar[Signal] = ... # baseColorChanged(QVariant)
        metalnessChanged         : typing.ClassVar[Signal] = ... # metalnessChanged(QVariant)
        normalChanged            : typing.ClassVar[Signal] = ... # normalChanged(QVariant)
        roughnessChanged         : typing.ClassVar[Signal] = ... # roughnessChanged(QVariant)
        textureScaleChanged      : typing.ClassVar[Signal] = ... # textureScaleChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, baseColor: typing.Any | None = ..., metalness: typing.Any | None = ..., roughness: typing.Any | None = ..., ambientOcclusion: typing.Any | None = ..., normal: typing.Any | None = ..., textureScale: float | None = ...) -> None: ...

        @property
        def ambientOcclusion(self, /) -> typing.Any: ...
        @ambientOcclusion.setter
        def ambientOcclusion(self, ambientOcclusion: typing.Any, /) -> None: ...
        @property
        def baseColor(self, /) -> typing.Any: ...
        @baseColor.setter
        def baseColor(self, baseColor: typing.Any, /) -> None: ...
        @property
        def metalness(self, /) -> typing.Any: ...
        @metalness.setter
        def metalness(self, metalness: typing.Any, /) -> None: ...
        @property
        def normal(self, /) -> typing.Any: ...
        @normal.setter
        def normal(self, normal: typing.Any, /) -> None: ...
        @property
        def roughness(self, /) -> typing.Any: ...
        @roughness.setter
        def roughness(self, roughness: typing.Any, /) -> None: ...
        @property
        def textureScale(self, /) -> float: ...
        @textureScale.setter
        def textureScale(self, textureScale: float, /) -> None: ...

    class QMorphPhongMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(QColor)
        interpolatorChanged      : typing.ClassVar[Signal] = ... # interpolatorChanged(float)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QColor)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., diffuse: PySide6.QtGui.QColor | None = ..., specular: PySide6.QtGui.QColor | None = ..., shininess: float | None = ..., interpolator: float | None = ...) -> None: ...

        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.QtGui.QColor: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def interpolator(self, /) -> float: ...
        @interpolator.setter
        def interpolator(self, interpolator: float, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.QtGui.QColor: ...
        @specular.setter
        def specular(self, specular: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...

    class QNormalDiffuseMapAlphaMaterial(PySide6.Qt3DExtras.Qt3DExtras.QNormalDiffuseMapMaterial):

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ...) -> None: ...


    class QNormalDiffuseMapMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(Qt3DRender::QAbstractTexture*)
        normalChanged            : typing.ClassVar[Signal] = ... # normalChanged(Qt3DRender::QAbstractTexture*)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QColor)
        textureScaleChanged      : typing.ClassVar[Signal] = ... # textureScaleChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., specular: PySide6.QtGui.QColor | None = ..., diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., normal: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., shininess: float | None = ..., textureScale: float | None = ...) -> None: ...

        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def normal(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @normal.setter
        def normal(self, normal: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.QtGui.QColor: ...
        @specular.setter
        def specular(self, specular: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def textureScale(self, /) -> float: ...
        @textureScale.setter
        def textureScale(self, textureScale: float, /) -> None: ...

    class QNormalDiffuseSpecularMapMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(Qt3DRender::QAbstractTexture*)
        normalChanged            : typing.ClassVar[Signal] = ... # normalChanged(Qt3DRender::QAbstractTexture*)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(Qt3DRender::QAbstractTexture*)
        textureScaleChanged      : typing.ClassVar[Signal] = ... # textureScaleChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., normal: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., specular: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., shininess: float | None = ..., textureScale: float | None = ...) -> None: ...

        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def normal(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @normal.setter
        def normal(self, normal: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @specular.setter
        def specular(self, specular: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def textureScale(self, /) -> float: ...
        @textureScale.setter
        def textureScale(self, textureScale: float, /) -> None: ...

    class QOrbitCameraController(PySide6.Qt3DExtras.Qt3DExtras.QAbstractCameraController):

        inversePanChanged        : typing.ClassVar[Signal] = ... # inversePanChanged(bool)
        inverseTiltChanged       : typing.ClassVar[Signal] = ... # inverseTiltChanged(bool)
        inverseXTranslateChanged : typing.ClassVar[Signal] = ... # inverseXTranslateChanged(bool)
        inverseYTranslateChanged : typing.ClassVar[Signal] = ... # inverseYTranslateChanged(bool)
        upVectorChanged          : typing.ClassVar[Signal] = ... # upVectorChanged(QVector3D)
        zoomInLimitChanged       : typing.ClassVar[Signal] = ... # zoomInLimitChanged()
        zoomTranslateViewCenterChanged: typing.ClassVar[Signal] = ... # zoomTranslateViewCenterChanged(bool)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, zoomInLimit: float | None = ..., upVector: PySide6.QtGui.QVector3D | None = ..., inverseXTranslate: bool | None = ..., inverseYTranslate: bool | None = ..., inversePan: bool | None = ..., inverseTilt: bool | None = ..., zoomTranslateViewCenter: bool | None = ...) -> None: ...

        @property
        def inversePan(self, /) -> bool: ...
        @inversePan.setter
        def inversePan(self, isInverse: bool, /) -> None: ...
        @property
        def inverseTilt(self, /) -> bool: ...
        @inverseTilt.setter
        def inverseTilt(self, isInverse: bool, /) -> None: ...
        @property
        def inverseXTranslate(self, /) -> bool: ...
        @inverseXTranslate.setter
        def inverseXTranslate(self, isInverse: bool, /) -> None: ...
        @property
        def inverseYTranslate(self, /) -> bool: ...
        @inverseYTranslate.setter
        def inverseYTranslate(self, isInverse: bool, /) -> None: ...
        @property
        def upVector(self, /) -> PySide6.QtGui.QVector3D: ...
        @upVector.setter
        def upVector(self, upVector: PySide6.QtGui.QVector3D, /) -> None: ...
        @property
        def zoomInLimit(self, /) -> float: ...
        @zoomInLimit.setter
        def zoomInLimit(self, zoomInLimit: float, /) -> None: ...
        @property
        def zoomTranslateViewCenter(self, /) -> bool: ...
        @zoomTranslateViewCenter.setter
        def zoomTranslateViewCenter(self, isTranslate: bool, /) -> None: ...

    class QPerVertexColorMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ...) -> None: ...


    class QPhongAlphaMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        alphaChanged             : typing.ClassVar[Signal] = ... # alphaChanged(float)
        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        blendFunctionArgChanged  : typing.ClassVar[Signal] = ... # blendFunctionArgChanged(Qt3DRender::QBlendEquation::BlendFunction)
        destinationAlphaArgChanged: typing.ClassVar[Signal] = ... # destinationAlphaArgChanged(Qt3DRender::QBlendEquationArguments::Blending)
        destinationRgbArgChanged : typing.ClassVar[Signal] = ... # destinationRgbArgChanged(Qt3DRender::QBlendEquationArguments::Blending)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(QColor)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        sourceAlphaArgChanged    : typing.ClassVar[Signal] = ... # sourceAlphaArgChanged(Qt3DRender::QBlendEquationArguments::Blending)
        sourceRgbArgChanged      : typing.ClassVar[Signal] = ... # sourceRgbArgChanged(Qt3DRender::QBlendEquationArguments::Blending)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QColor)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., diffuse: PySide6.QtGui.QColor | None = ..., specular: PySide6.QtGui.QColor | None = ..., shininess: float | None = ..., alpha: float | None = ..., sourceRgbArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending | None = ..., destinationRgbArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending | None = ..., sourceAlphaArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending | None = ..., destinationAlphaArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending | None = ..., blendFunctionArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquation.BlendFunction | None = ...) -> None: ...

        @property
        def alpha(self, /) -> float: ...
        @alpha.setter
        def alpha(self, alpha: float, /) -> None: ...
        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def blendFunctionArg(self, /) -> PySide6.Qt3DRender.Qt3DRender.QBlendEquation.BlendFunction: ...
        @blendFunctionArg.setter
        def blendFunctionArg(self, blendFunctionArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquation.BlendFunction, /) -> None: ...
        @property
        def destinationAlphaArg(self, /) -> PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending: ...
        @destinationAlphaArg.setter
        def destinationAlphaArg(self, destinationAlphaArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending, /) -> None: ...
        @property
        def destinationRgbArg(self, /) -> PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending: ...
        @destinationRgbArg.setter
        def destinationRgbArg(self, destinationRgbArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.QtGui.QColor: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def sourceAlphaArg(self, /) -> PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending: ...
        @sourceAlphaArg.setter
        def sourceAlphaArg(self, sourceAlphaArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending, /) -> None: ...
        @property
        def sourceRgbArg(self, /) -> PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending: ...
        @sourceRgbArg.setter
        def sourceRgbArg(self, sourceRgbArg: PySide6.Qt3DRender.Qt3DRender.QBlendEquationArguments.Blending, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.QtGui.QColor: ...
        @specular.setter
        def specular(self, specular: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...

    class QPhongMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        ambientChanged           : typing.ClassVar[Signal] = ... # ambientChanged(QColor)
        diffuseChanged           : typing.ClassVar[Signal] = ... # diffuseChanged(QColor)
        shininessChanged         : typing.ClassVar[Signal] = ... # shininessChanged(float)
        specularChanged          : typing.ClassVar[Signal] = ... # specularChanged(QColor)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, ambient: PySide6.QtGui.QColor | None = ..., diffuse: PySide6.QtGui.QColor | None = ..., specular: PySide6.QtGui.QColor | None = ..., shininess: float | None = ...) -> None: ...

        @property
        def ambient(self, /) -> PySide6.QtGui.QColor: ...
        @ambient.setter
        def ambient(self, ambient: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def diffuse(self, /) -> PySide6.QtGui.QColor: ...
        @diffuse.setter
        def diffuse(self, diffuse: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def shininess(self, /) -> float: ...
        @shininess.setter
        def shininess(self, shininess: float, /) -> None: ...
        @property
        def specular(self, /) -> PySide6.QtGui.QColor: ...
        @specular.setter
        def specular(self, specular: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...

    class QPlaneGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        heightChanged            : typing.ClassVar[Signal] = ... # heightChanged(float)
        mirroredChanged          : typing.ClassVar[Signal] = ... # mirroredChanged(bool)
        resolutionChanged        : typing.ClassVar[Signal] = ... # resolutionChanged(QSize)
        widthChanged             : typing.ClassVar[Signal] = ... # widthChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, width: float | None = ..., height: float | None = ..., resolution: PySide6.QtCore.QSize | None = ..., mirrored: bool | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., texCoordAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., tangentAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def height(self, /) -> float: ...
        @height.setter
        def height(self, height: float, /) -> None: ...
        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def mirrored(self, /) -> bool: ...
        @mirrored.setter
        def mirrored(self, mirrored: bool, /) -> None: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def resolution(self, /) -> PySide6.QtCore.QSize: ...
        @resolution.setter
        def resolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def tangentAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def texCoordAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def updateIndices(self, /) -> None: ...
        def updateVertices(self, /) -> None: ...
        @property
        def width(self, /) -> float: ...
        @width.setter
        def width(self, width: float, /) -> None: ...

    class QPlaneGeometryView(PySide6.Qt3DCore.Qt3DCore.QGeometryView):

        heightChanged            : typing.ClassVar[Signal] = ... # heightChanged(float)
        meshResolutionChanged    : typing.ClassVar[Signal] = ... # meshResolutionChanged(QSize)
        mirroredChanged          : typing.ClassVar[Signal] = ... # mirroredChanged(bool)
        widthChanged             : typing.ClassVar[Signal] = ... # widthChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, width: float | None = ..., height: float | None = ..., meshResolution: PySide6.QtCore.QSize | None = ..., mirrored: bool | None = ...) -> None: ...

        @property
        def height(self, /) -> float: ...
        @height.setter
        def height(self, height: float, /) -> None: ...
        @property
        def meshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @meshResolution.setter
        def meshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def mirrored(self, /) -> bool: ...
        @mirrored.setter
        def mirrored(self, mirrored: bool, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DCore.Qt3DCore.QGeometryView.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def width(self, /) -> float: ...
        @width.setter
        def width(self, width: float, /) -> None: ...

    class QPlaneMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        heightChanged            : typing.ClassVar[Signal] = ... # heightChanged(float)
        meshResolutionChanged    : typing.ClassVar[Signal] = ... # meshResolutionChanged(QSize)
        mirroredChanged          : typing.ClassVar[Signal] = ... # mirroredChanged(bool)
        widthChanged             : typing.ClassVar[Signal] = ... # widthChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, width: float | None = ..., height: float | None = ..., meshResolution: PySide6.QtCore.QSize | None = ..., mirrored: bool | None = ...) -> None: ...

        @property
        def height(self, /) -> float: ...
        @height.setter
        def height(self, height: float, /) -> None: ...
        @property
        def meshResolution(self, /) -> PySide6.QtCore.QSize: ...
        @meshResolution.setter
        def meshResolution(self, resolution: PySide6.QtCore.QSize, /) -> None: ...
        @property
        def mirrored(self, /) -> bool: ...
        @mirrored.setter
        def mirrored(self, mirrored: bool, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def width(self, /) -> float: ...
        @width.setter
        def width(self, width: float, /) -> None: ...

    class QSkyboxEntity(PySide6.Qt3DCore.Qt3DCore.QEntity):

        baseNameChanged          : typing.ClassVar[Signal] = ... # baseNameChanged(QString)
        extensionChanged         : typing.ClassVar[Signal] = ... # extensionChanged(QString)
        gammaCorrectEnabledChanged: typing.ClassVar[Signal] = ... # gammaCorrectEnabledChanged(bool)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, baseName: str | None = ..., extension: str | None = ..., gammaCorrect: bool | None = ...) -> None: ...

        @property
        def baseName(self, /) -> str: ...
        @baseName.setter
        def baseName(self, path: str, /) -> None: ...
        @property
        def extension(self, /) -> str: ...
        @extension.setter
        def extension(self, extension: str, /) -> None: ...
        @property
        def gammaCorrect(self, /) -> bool: ...
        @gammaCorrect.setter
        def gammaCorrect(self, enabled: bool, /) -> None: ...
        def setGammaCorrectEnabled(self, enabled: bool, /) -> None: ...

    class QSphereGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        generateTangentsChanged  : typing.ClassVar[Signal] = ... # generateTangentsChanged(bool)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., generateTangents: bool | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., texCoordAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., tangentAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def generateTangents(self, /) -> bool: ...
        @generateTangents.setter
        def generateTangents(self, gen: bool, /) -> None: ...
        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...
        @property
        def tangentAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def texCoordAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def updateIndices(self, /) -> None: ...
        def updateVertices(self, /) -> None: ...

    class QSphereGeometryView(PySide6.Qt3DCore.Qt3DCore.QGeometryView):

        generateTangentsChanged  : typing.ClassVar[Signal] = ... # generateTangentsChanged(bool)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., generateTangents: bool | None = ...) -> None: ...

        @property
        def generateTangents(self, /) -> bool: ...
        @generateTangents.setter
        def generateTangents(self, gen: bool, /) -> None: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DCore.Qt3DCore.QGeometryView.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...

    class QSphereMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        generateTangentsChanged  : typing.ClassVar[Signal] = ... # generateTangentsChanged(bool)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., generateTangents: bool | None = ...) -> None: ...

        @property
        def generateTangents(self, /) -> bool: ...
        @generateTangents.setter
        def generateTangents(self, gen: bool, /) -> None: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...

    class QSpriteGrid(PySide6.Qt3DExtras.Qt3DExtras.QAbstractSpriteSheet):

        columnsChanged           : typing.ClassVar[Signal] = ... # columnsChanged(int)
        rowsChanged              : typing.ClassVar[Signal] = ... # rowsChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rows: int | None = ..., columns: int | None = ...) -> None: ...

        @property
        def columns(self, /) -> int: ...
        @columns.setter
        def columns(self, columns: int, /) -> None: ...
        @property
        def rows(self, /) -> int: ...
        @rows.setter
        def rows(self, rows: int, /) -> None: ...

    class QSpriteSheet(PySide6.Qt3DExtras.Qt3DExtras.QAbstractSpriteSheet):

        spritesChanged           : typing.ClassVar[Signal] = ... # spritesChanged(QList<QSpriteSheetItem*>)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, sprites: collections.abc.Sequence[PySide6.Qt3DExtras.Qt3DExtras.QSpriteSheetItem] | None = ...) -> None: ...

        @typing.overload
        def addSprite(self, sprite: PySide6.Qt3DExtras.Qt3DExtras.QSpriteSheetItem, /) -> None: ...
        @typing.overload
        def addSprite(self, x: int, y: int, width: int, height: int, /) -> PySide6.Qt3DExtras.Qt3DExtras.QSpriteSheetItem: ...
        def removeSprite(self, sprite: PySide6.Qt3DExtras.Qt3DExtras.QSpriteSheetItem, /) -> None: ...
        @property
        def sprites(self, /) -> typing.List[PySide6.Qt3DExtras.Qt3DExtras.QSpriteSheetItem]: ...
        @sprites.setter
        def sprites(self, sprites: collections.abc.Sequence[PySide6.Qt3DExtras.Qt3DExtras.QSpriteSheetItem], /) -> None: ...

    class QSpriteSheetItem(PySide6.Qt3DCore.Qt3DCore.QNode):

        heightChanged            : typing.ClassVar[Signal] = ... # heightChanged(int)
        widthChanged             : typing.ClassVar[Signal] = ... # widthChanged(int)
        xChanged                 : typing.ClassVar[Signal] = ... # xChanged(int)
        yChanged                 : typing.ClassVar[Signal] = ... # yChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, x: int | None = ..., y: int | None = ..., width: int | None = ..., height: int | None = ...) -> None: ...

        @property
        def height(self, /) -> int: ...
        @height.setter
        def height(self, height: int, /) -> None: ...
        @property
        def width(self, /) -> int: ...
        @width.setter
        def width(self, width: int, /) -> None: ...
        @property
        def x(self, /) -> int: ...
        @x.setter
        def x(self, x: int, /) -> None: ...
        @property
        def y(self, /) -> int: ...
        @y.setter
        def y(self, y: int, /) -> None: ...

    class QText2DEntity(PySide6.Qt3DCore.Qt3DCore.QEntity):

        colorChanged             : typing.ClassVar[Signal] = ... # colorChanged(QColor)
        fontChanged              : typing.ClassVar[Signal] = ... # fontChanged(QFont)
        heightChanged            : typing.ClassVar[Signal] = ... # heightChanged(float)
        textChanged              : typing.ClassVar[Signal] = ... # textChanged(QString)
        widthChanged             : typing.ClassVar[Signal] = ... # widthChanged(float)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, font: PySide6.QtGui.QFont | None = ..., text: str | None = ..., color: PySide6.QtGui.QColor | None = ..., width: float | None = ..., height: float | None = ..., alignment: PySide6.QtCore.Qt.AlignmentFlag | None = ...) -> None: ...

        @property
        def alignment(self, /) -> PySide6.QtCore.Qt.AlignmentFlag: ...
        @alignment.setter
        def alignment(self, alignment: PySide6.QtCore.Qt.AlignmentFlag, /) -> None: ...
        @property
        def color(self, /) -> PySide6.QtGui.QColor: ...
        @color.setter
        def color(self, color: PySide6.QtGui.QColor | str | PySide6.QtGui.QRgba64 | typing.Any | PySide6.QtCore.Qt.GlobalColor | int, /) -> None: ...
        @property
        def font(self, /) -> PySide6.QtGui.QFont: ...
        @font.setter
        def font(self, font: PySide6.QtGui.QFont | str | collections.abc.Sequence[str], /) -> None: ...
        @property
        def height(self, /) -> float: ...
        @height.setter
        def height(self, height: float, /) -> None: ...
        @property
        def text(self, /) -> str: ...
        @text.setter
        def text(self, text: str, /) -> None: ...
        @property
        def width(self, /) -> float: ...
        @width.setter
        def width(self, width: float, /) -> None: ...

    class QTextureMaterial(PySide6.Qt3DRender.Qt3DRender.QMaterial):

        alphaBlendingEnabledChanged: typing.ClassVar[Signal] = ... # alphaBlendingEnabledChanged(bool)
        textureChanged           : typing.ClassVar[Signal] = ... # textureChanged(Qt3DRender::QAbstractTexture*)
        textureOffsetChanged     : typing.ClassVar[Signal] = ... # textureOffsetChanged(QVector2D)
        textureTransformChanged  : typing.ClassVar[Signal] = ... # textureTransformChanged(QMatrix3x3)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, texture: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture | None = ..., textureOffset: PySide6.QtGui.QVector2D | None = ..., textureTransform: PySide6.QtGui.QMatrix3x3 | None = ..., alphaBlending: bool | None = ...) -> None: ...

        @property
        def alphaBlending(self, /) -> bool: ...
        @alphaBlending.setter
        def alphaBlending(self, enabled: bool, /) -> None: ...
        def setAlphaBlendingEnabled(self, enabled: bool, /) -> None: ...
        @property
        def texture(self, /) -> PySide6.Qt3DRender.Qt3DRender.QAbstractTexture: ...
        @texture.setter
        def texture(self, texture: PySide6.Qt3DRender.Qt3DRender.QAbstractTexture, /) -> None: ...
        @property
        def textureOffset(self, /) -> PySide6.QtGui.QVector2D: ...
        @textureOffset.setter
        def textureOffset(self, textureOffset: PySide6.QtGui.QVector2D, /) -> None: ...
        @property
        def textureTransform(self, /) -> PySide6.QtGui.QMatrix3x3: ...
        @textureTransform.setter
        def textureTransform(self, matrix: PySide6.QtGui.QMatrix3x3, /) -> None: ...

    class QTorusGeometry(PySide6.Qt3DCore.Qt3DCore.QGeometry):

        minorRadiusChanged       : typing.ClassVar[Signal] = ... # minorRadiusChanged(float)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., minorRadius: float | None = ..., positionAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., normalAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., texCoordAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ..., indexAttribute: PySide6.Qt3DCore.Qt3DCore.QAttribute | None = ...) -> None: ...

        @property
        def indexAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def minorRadius(self, /) -> float: ...
        @minorRadius.setter
        def minorRadius(self, minorRadius: float, /) -> None: ...
        @property
        def normalAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def positionAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...
        @property
        def texCoordAttribute(self, /) -> PySide6.Qt3DCore.Qt3DCore.QAttribute: ...
        def updateIndices(self, /) -> None: ...
        def updateVertices(self, /) -> None: ...

    class QTorusGeometryView(PySide6.Qt3DCore.Qt3DCore.QGeometryView):

        minorRadiusChanged       : typing.ClassVar[Signal] = ... # minorRadiusChanged(float)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., minorRadius: float | None = ...) -> None: ...

        @property
        def minorRadius(self, /) -> float: ...
        @minorRadius.setter
        def minorRadius(self, minorRadius: float, /) -> None: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DCore.Qt3DCore.QGeometryView.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...

    class QTorusMesh(PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer):

        minorRadiusChanged       : typing.ClassVar[Signal] = ... # minorRadiusChanged(float)
        radiusChanged            : typing.ClassVar[Signal] = ... # radiusChanged(float)
        ringsChanged             : typing.ClassVar[Signal] = ... # ringsChanged(int)
        slicesChanged            : typing.ClassVar[Signal] = ... # slicesChanged(int)

        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ..., *, rings: int | None = ..., slices: int | None = ..., radius: float | None = ..., minorRadius: float | None = ...) -> None: ...

        @property
        def minorRadius(self, /) -> float: ...
        @minorRadius.setter
        def minorRadius(self, minorRadius: float, /) -> None: ...
        @property
        def radius(self, /) -> float: ...
        @radius.setter
        def radius(self, radius: float, /) -> None: ...
        @property
        def rings(self, /) -> int: ...
        @rings.setter
        def rings(self, rings: int, /) -> None: ...
        def setFirstInstance(self, firstInstance: int, /) -> None: ...
        def setGeometry(self, geometry: PySide6.Qt3DCore.Qt3DCore.QGeometry, /) -> None: ...
        def setIndexOffset(self, indexOffset: int, /) -> None: ...
        def setInstanceCount(self, instanceCount: int, /) -> None: ...
        def setPrimitiveRestartEnabled(self, enabled: bool, /) -> None: ...
        def setPrimitiveType(self, primitiveType: PySide6.Qt3DRender.Qt3DRender.QGeometryRenderer.PrimitiveType, /) -> None: ...
        def setRestartIndexValue(self, index: int, /) -> None: ...
        def setVertexCount(self, vertexCount: int, /) -> None: ...
        @property
        def slices(self, /) -> int: ...
        @slices.setter
        def slices(self, slices: int, /) -> None: ...

    class Qt3DWindow(PySide6.QtGui.QWindow):

        def __init__(self, /, screen: PySide6.QtGui.QScreen | None = ..., arg__2: PySide6.Qt3DRender.Qt3DRender.API = ...) -> None: ...

        def activeFrameGraph(self, /) -> PySide6.Qt3DRender.Qt3DRender.QFrameGraphNode: ...
        def camera(self, /) -> PySide6.Qt3DRender.Qt3DRender.QCamera: ...
        def defaultFrameGraph(self, /) -> PySide6.Qt3DExtras.Qt3DExtras.QForwardRenderer: ...
        def event(self, e: PySide6.QtCore.QEvent, /) -> bool: ...
        @typing.overload
        def registerAspect(self, aspect: PySide6.Qt3DCore.Qt3DCore.QAbstractAspect, /) -> None: ...
        @typing.overload
        def registerAspect(self, name: str, /) -> None: ...
        def renderSettings(self, /) -> PySide6.Qt3DRender.Qt3DRender.QRenderSettings: ...
        def resizeEvent(self, arg__1: PySide6.QtGui.QResizeEvent, /) -> None: ...
        def setActiveFrameGraph(self, activeFrameGraph: PySide6.Qt3DRender.Qt3DRender.QFrameGraphNode, /) -> None: ...
        def setRootEntity(self, root: PySide6.Qt3DCore.Qt3DCore.QEntity, /) -> None: ...
        def showEvent(self, e: PySide6.QtGui.QShowEvent, /) -> None: ...


    @staticmethod
    def setupWindowSurface(window: PySide6.QtGui.QWindow, arg__2: PySide6.Qt3DRender.Qt3DRender.API, /) -> None: ...


# eof
